### ISSUE TITLE
not work in Windows 11

### ISSUE THREAD

**Issue by wecando168** [bittorrent/go-btfs#10]
btfs-windows-amd64.exe Unable to run on the windows 11 operating system. The CMD window appears after startup, and cannot be installed.

AMD Ryzen 7 2700X Eight-Core Processor            3.70 GHz
RAM	32.0 GB

**Comment by daniel-tron** [comment]
Could you provide the log messages on the CMD window?
BTW: It's work well on our Win2019 lab.

**Comment by wecando168** [comment]
Double click the “btfs-windows-amd64.exe” installer, a black command line window will pop up, and then it will close. There is no other response. I tried to use the compatible method, and the same is true. I didn't see the log. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bittorrent/go-btfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 中午11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bittorrent/go-btfs] not work in Windows 11 (Issue #10)





 
Could you provide the log messages on the CMD window?
 BTW: It's work well on our Win2019 lab.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daniel-tron** [comment]
Could you start an empty windows first, then run the btfs-windows-amd64.exe inside it, so after the exe exit, the cmd windows can keep opening, so we can see the message if have. and could you check the 'event viewer' if have error?
BTW: we are setting up a win11 env, need some time.

**Comment by daniel-tron** [comment]
It's working well in our Win11 lab (intel), [snapshot](https://gateway.btfs.io/btfs/QmTV8p7ni9Hp1xEa3WwMw1PVHV9d9u1mrR98cnJZPwBy6D). Coud you help check if have error i 'event viewer'?

**Comment by wecando168** [comment]
Thank you for your support. Today, I accidentally restarted the computer and it was ready to run, but I was prompted how to deal with this problem。

my system info










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bittorrent/go-btfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 下午2:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bittorrent/go-btfs] not work in Windows 11 (Issue #10)





 
It's working well in our Win11 lab (intel), snapshot. Coud you help check if have error i 'event viewer'?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
