### ISSUE TITLE
could not resolve name

### ISSUE THREAD

**Issue by wecando168** [bittorrent/go-btfs#11]
Daemon is ready
but open http://127.0.0.1:5001/hostui
error:btfs resolve -r /btns/16Uiu2HAmU9ysnuasmdyq1rRePYTwHntmyhZdfC9wm4qCPQMAh9Qq/: could not resolve name

**Comment by daniel-tron** [comment]
Please make sure you have public ip and connect to the seed node, or use this workaround:  https://dashboard-test.btfs.io

**Comment by wecando168** [comment]
hao to connect to the seed node?
what can I do?

**Comment by TonyTosol** [comment]
I entered by https://dashboard-test.btfs.io    and it show dashboard but it tel me, that Api endpoint is not acceseble

**Comment by Sophia-yu-kk** [comment]
> I entered by https://dashboard-test.btfs.io and it show dashboard but it tel me, that Api endpoint is not acceseble On Dashboard Discord invite not working, you shold make it persist forever. I opend outside tcp 4001 port to this pc, any other need to be opened?

Discord Address，https://discord.gg/GDWabX3t 
https://docs.btfs.io/v2.0/docs/btfs20-dashboard This is the documentation of dashboard, can you see if it can help you?

**Comment by daniel-tron** [comment]
> hao to connect to the seed node? what can I do?

Make sure you are using testnet configuration, and then BTFS will auto connect to seed node if you network is good.
btfs config profile apply storage-host-testnet

**Comment by daniel-tron** [comment]
> I entered by https://dashboard-test.btfs.io and it show dashboard but it tel me, that Api endpoint is not acceseble On Dashboard Discord invite not working, you shold make it persist forever. I opend outside tcp 4001 port to this pc, any other need to be opened?

You need run below command per readme at https://github.com/bittorrent/go-btfs
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT","GET","POST"]'

**Comment by daddydaycare** [comment]
Same issue. And those commands had no effect.
