### ISSUE TITLE
Upgraded btfs but still have token in  wallet, how can I transfer them out?

### ISSUE THREAD

**Issue by felixishim** [bittorrent/go-btfs#116]
As titled, I have transfer some of my in app walllet BTT to OLDBTT and converted to the new BTTC
but there are still balance in the bittorrent speed wallet, but I also upgraded the wallet already

**Comment by Sophia-yu-kk** [comment]
In the next version, the extraction command for the balance of BTFS 1.0 will be added, thank you very much for your feedback
