### ISSUE TITLE
2.1.1 - Host Age decreased to 5 points

### ISSUE THREAD

**Issue by juchambo** [bittorrent/go-btfs#118]
I have 2 nodes, one from july 2020 and another from january 2021. In the past few days both of them have decreased host age to 5 points. I think this is a bug or something cause nodes can´t get younger....

There were other user with the same problem on the discord channel.

**Comment by jaffsys** [comment]
Same problem to me as well... Commenting to follow up on solution

**Comment by Sophia-yu-kk** [comment]
Thank you very much for your feedback, this issue has been fed back to the development team.

**Comment by Sophia-yu-kk** [comment]
uptime and host score 0 #115
To facilitate problem solving and problem management. These two questions are similar, so we'll just keep one, and this one will be closed, so you can go to the other one to communicate. Thank you very much!
