### ISSUE TITLE
QoL suggestion: Ability to change storage allocation

### ISSUE THREAD

**Issue by Rockster34** [bittorrent/go-btfs#119]
Maybe it's a good quality of life improvement to bring back storage allocation within the UI since changing it in the config is kinda annoying especially since it means you gotta turn off the client itself to update. 

The best option would be to be able to do it in realtime via the UI through the API and directly changing the allocated size without having to restart the BTFS client (I know this also goes for the BTFS dashboard team but I find it more suitable here due to it being an API level feature instead of just a couple UI changes) the best way to secure this process would be with a set password and probably the easiest way would be a random generated key everytime someone makes a new session on the BTFS chain to keep it randomized and harder to guess without too much user input, or by just making a user make a password when they first init the client.

And maybe also let people be able to select drive(s) from the UI while we are at it anyhow just as easy if that is also an option since not everyone wants to be playing around with the command line and it makes it alot more accessible to any new people to the BTFS sphere

**Comment by Sophia-yu-kk** [comment]
Thank you very much for your suggestion, we will optimize it in the subsequent version.
