### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by holychen1234** [bittorrent/go-btfs#12]
[root@iZj6c0u0zcojlroll9t444Z go-btfs]# make install
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go version go1.15.14 linux/amd64
bin/check_go_version 1.15
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir -- https://launchpad.net/~niemeyer/gocheck/trunk . in /root/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
make: *** [plugin/loader/preload.go] Error 1

**Comment by daniel-tron** [comment]
Could you check 'go version'? Our CI process using 1.15 in docker file.

**Comment by holychen1234** [comment]
go version go1.15.14 linux/amd64

**Comment by daniel-tron** [comment]
Found a workaround at [here](https://github.com/smallnest/rpcx/issues/305), could you help check if it work?

go-btfs/go.mod
replace launchpad.net/gocheck v0.0.0-20140225173054-000000000087 => github.com/go-check/check v0.0.0-20180628173108-788fd7840127

**Comment by holychen1234** [comment]
> Found a workaround at [here](https://github.com/smallnest/rpcx/issues/305), could you help check if work for your env?
> 
> go-btfs/go.mod replace launchpad.net/gocheck v0.0.0-20140225173054-000000000087 => github.com/go-check/check v0.0.0-20180628173108-788fd7840127

The problem is solved，install the latest version of 1.17.5,and it works.

**Comment by daniel-tron** [comment]
Cool.
