### ISSUE TITLE
Docker container start with key  "--chain-id 199"

### ISSUE THREAD

**Issue by maxgunchenko** [bittorrent/go-btfs#122]
i run this line and nothing
docker run -d --restart unless-stopped --stop-timeout 300 -p 5001:5001 -v myfolder:/data/btfs --name btfs2 ghcr.io/bittorrent/go-btfs:master

**Comment by Sophia-yu-kk** [comment]
This question has been answered in the BTFS community, thank you very much.

go-btfs:master will be updated every release, if it is the latest, it is not necessary to add the chain-id parameter, the default is the master network
If you don't confirm whether it is the latest one, you can use go-btfs:btfs-v2.1.1 directly.
