### ISSUE TITLE
Command line BTFS storage contracts list host isn't reflected in UI

### ISSUE THREAD

**Issue by Rockster34** [bittorrent/go-btfs#123]
As the title states 

The info this command puts out isn't in sync with the what the UI says for some reason.

![image](https://user-images.githubusercontent.com/13683726/159696156-783c2ee6-93a5-460d-80ec-193a7a393f88.png)

**Comment by Sophia-yu-kk** [comment]
> As the title states
> 
> The info this command puts out isn't in sync with the what the UI says for some reason.
> 
> ![image](https://user-images.githubusercontent.com/13683726/159696156-783c2ee6-93a5-460d-80ec-193a7a393f88.png)

Please provide your node version number, thank you!

**Comment by Rockster34** [comment]
This is version 2.1.1 :)

**Comment by LordMerlin** [comment]
Good afternoon.
I am seeing the same error. The Web interface also shows 20 contracts, but in fact there are 77 of them.
Node version 2.1.1

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, the community has been assisted with questions to feedback.

**Comment by Sophia-yu-kk** [comment]
The BTFS community appreciates your feedback on the issue and will optimize it.

**Comment by Sophia-yu-kk** [comment]
> It seems like they forgot to add V2.1.2 of dashboard in the new version of BTFS while compiling the code
> 
> --EDIT 2--
> 
> it seems like the URL that you use for Dashboard needs to be updated? maybe for future dashboard updates force the user to update the dash if the dash detects that you are on a previous version?

hi，you need to update your dashboard to version 2.1.2. https://github.com/bittorrent/btfs-dashboard/releases/tag/v2.1.2

**Comment by Rockster34** [comment]
It has now :) after going back to /dashboard it redirected properly to the new version. Once again I would still suggest an inline update if the UI shows an out of date version of the dashboard.

**Comment by Rockster34** [comment]
I figured out why the original was limited to 20 contracts as the command line only lists 20 contracts at once. Next to that it's keeping a bunch of contracts that have expired in the list array as well which doesn't really make sense as compensation outstanding is 0 meaning that the list from `btfs storage contracts list host` is inhertitly broken as is right now since it has outdated contracts on it. This could also possibly be one of the reasons why RAM usage is getting so crazy high after multiple days of letting it run 🤔

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, the follow-up will continue to optimize.
