### ISSUE TITLE
Why is the resource occupation of nodes unstable？

### ISSUE THREAD

**Issue by holychen1234** [bittorrent/go-btfs#125]
The official recommend running it on a machine with at least 2 GB of RAM (it’ll do fine with only one CPU core), but nodes should often be forcibly killed because they occupy too much resources,like oom kill.Will the next version upgrade optimize this problem？

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                 
 7625 root      20   0 3975940   1.6g  29824 S 274.8  1.7 113:47.54 btfs

**Comment by Sophia-yu-kk** [comment]
This is a known issue and the BTFS community has fed this back to the development team and it is expected to be optimized in the next release. Thank you very much for your feedback!

**Comment by Sophia-yu-kk** [comment]
This issue will be optimized in V2.1.3.

**Comment by Sophia-yu-kk** [comment]
This issue has been optimized.
