### ISSUE TITLE
Get 10 million BTT as a gift.

### ISSUE THREAD

**Issue by TheBestBadGamer** [bittorrent/go-btfs#126]
I recently received a large sum of money from a BTTC address, simply 10 million BTT. Since I wanted to ask why and whether it is possibly a criminal BTTC address?

BTTC address from which I have the 10 million is:
0x0B6dE2FB2873cbf6220784BDB70F9d4388553621

**Comment by solipsist01** [comment]
Thats called an airdrop. Totally legit.

**Comment by TheBestBadGamer** [comment]
That's what I thought at the beginning. I just wanted to be sure. Thank you.
