### ISSUE TITLE
Now Network Unstable?

### ISSUE THREAD

**Issue by hexter2018** [bittorrent/go-btfs#127]
Now Network Unstable?

**Comment by ZeroCool1974-BR** [comment]
I'm having the same problem:
16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL

**Comment by TheBestBadGamer** [comment]
I also had the same problem but now it works again, they probably fixed it already.

**Comment by Sophia-yu-kk** [comment]
This is a hint on the dashboard of the status of your node in the distributed network. Usually, it is a temporary one and is only used to indicate the current network status. If the page shows network instability for a long time, we recommend you to check the network connection.
