### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by holychen1234** [bittorrent/go-btfs#13]
[root@VM-16-14-centos btfs]# ./btfs init
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/root/go/pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132

**Comment by holychen1234** [comment]
my env:
OS:centos7.6
go version:go1.17.5 linux/amd64

**Comment by rockca** [comment]
Downgrade your go version to 1.15

**Comment by daniel-tron** [comment]
Closed since no update for 2 days.
