### ISSUE TITLE
btfs2.1.1 error

### ISSUE THREAD

**Issue by Alexkkkkk** [bittorrent/go-btfs#132]
Initializing daemon...
go-btfs version: 2.1.1-f76f7e0
Repo version: 10

c:\Users\гыук\AppData\Roaming\BitTorrent\btfs>btfs daemon --chain-id 199
Initializing daemon...
go-btfs version: 2.1.1-f76f7e0
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: D:\BTFS
Peer identity: 16Uiu2HAmKNBUz2Kz9iXbRHDEiwkkB5vKagKEDEbqxPTfb9yx5fkH

Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/169.254.165.179/tcp/4001
Swarm listening on /ip4/169.254.73.19/tcp/4001
Swarm listening on /ip4/192.168.0.104/tcp/4001
Swarm listening on /ip6/2002:b9e5:e91f:10::1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/185.229.233.31/tcp/4001
Swarm announcing /ip4/192.168.0.104/tcp/4001
Swarm announcing /ip6/2002:b9e5:e91f:10::1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Dashboard: http://127.0.0.1:5001/dashboard
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Current host stats will be synced
Current host settings will be synced
Current host settings will be synced
2022-03-30T07:41:11.605+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAmNRJY1LdSidgzYrP1ewPS
whp4aeYhMndUsFBdrLFhy1z7) for cid (Qmf3P92s8VNyEEfcMn71tZt2BPpnA9Xm2KfhcGdoKcEfc
v) not requested
2022-03-30T07:41:11.667+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAmTeBkZGVay6pgZeNLmW2q
pPJk6QJ4nxaFMspehSpF8FG6) for cid (Qmf3P92s8VNyEEfcMn71tZt2BPpnA9Xm2KfhcGdoKcEfc
v) not requested
2022-03-30T07:50:45.873+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAkzHguwStZMEE2VvD1vQd6
H3p38NnnFi8crcGDfEDXV2Hz) for cid (QmcMN8yDzbZZmJAr9AWHv6Ce3wVfE11sAbV8Re5w742Yf
w) not requested
2022-03-30T07:50:45.876+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAkzXRKiW5mtyfL7CKNdoCR
EVwVXeBUuApUDpMFd5JHkHdm) for cid (QmcMN8yDzbZZmJAr9AWHv6Ce3wVfE11sAbV8Re5w742Yf
w) not requested
2022/03/30 10:45:57 Unsolicited response received on idle HTTP channel starting
with "HTTP/0.0 400 Bad Request\r\nSERVER: Linux/2.6.36, UPnP/1.0, Portable SDK f
or UPnP devices/1.6.19\r\nCONTENT-LENGTH: 50\r\nCONTENT-TYPE: text/html\r\n\r\n<
html><body><h1>400 Bad Request</h1></body></html>"; err=<nil>
2022-03-30T13:51:01.516+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAmRC8cVUEpt3KJ3TAbvUSV
g49dZG86bmGBpvas4fN2T9Us) for cid (QmUTp8ydqaQwBRnxSLBPVUxuJurigKRUMy8XXFMXiytbH
z) not requested

**Comment by Sophia-yu-kk** [comment]
It is recommended to restart the node, this problem can be ignored, the subsequent optimization of the error message.
