### ISSUE TITLE
Over Memory

### ISSUE THREAD

**Issue by hexter2018** [bittorrent/go-btfs#133]
#124 
![Screenshot 2022-03-30 192216](https://user-images.githubusercontent.com/38841538/160833339-e4430e32-7bcb-4475-8d66-03ed0916f3a7.png)

**Comment by Sophia-yu-kk** [comment]
Thank you very much for your feedback, it is a known issue.

**Comment by Sophia-yu-kk** [comment]
The problem is being optimized, 125# is a problem with this one, just keep one.
