### ISSUE TITLE
Host Score is dropping

### ISSUE THREAD

**Issue by akinto2006** [bittorrent/go-btfs#142]
My node address is: 16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf

I have observed that ever since I started hosting under mainnet, since March 29, 2022, my host score keeps dropping. I started from v1.6 and transferred to testnet under 2.1.1 and this March to mainnet under 2.1.1. I leave my laptop open 24/7 for this. What gives?

**Comment by Sophia-yu-kk** [comment]
https://scan.btfs.io/#/node/16Uiu2HAkvZ9T8SYSnradx8SbH3s15K5cWCgZLA7kMZBvG99NPFzf
From the scan's point of view, the online hours of the node are not enough. The source of this data is the distributed network.To be based on the data displayed by the scan.
