### ISSUE TITLE
 error, msg: failed to find more valid hosts

### ISSUE THREAD

**Issue by saveriocolla90** [bittorrent/go-btfs#143]
Trying to upload files to the BTFS network through hash value, using command:
`btfs storage upload QmUK9nwtLEiHBJ48HAZHNmSQ53U6ADbRhATxs2tomadwKw`

generate the following error on the shell where btfs daemon host is running:
`entered state: error, msg: failed to find more valid hosts, please try again later`

What that error refers to?

Host has been configured as storage using the following command:
`btfs init -p storage-host`

**Comment by laocheng-cheng** [comment]
Hi, this is testnet or mainnet environment? cloud you provide your peer_id?

**Comment by saveriocolla90** [comment]
Hi, it is the mainnet environment (chain id 199). The peer ID is the following
`16Uiu2HAmAPn7FNTjU5n4U6w4DC4woKFQ2b7x3nMN8GHZKe56rke2`

**Comment by laocheng-cheng** [comment]
Hello, I feel that there is a node network problem. if the link is not to other nodes, there will be failed to find more valid hosts.
