### ISSUE TITLE
windows 2.1.2 upgrade error issue.. how

### ISSUE THREAD

**Issue by chocoball0033** [bittorrent/go-btfs#147]
![aaaa](https://user-images.githubusercontent.com/103118832/161972665-b328eb45-2fc4-41bf-ba1f-abb3f2d73337.PNG)

I get an error saying access is denied only on Windows.
Upgrade is not possible.
What is the cause??

**Comment by saveriocolla90** [comment]
Have you tried to open the command line as administrator mode?

**Comment by chocoball0033** [comment]
> 



> Have you tried to open the command line as administrator mode?

I ran it in admin mode. But I get the same error.

**Comment by chocoball0033** [comment]
;;; 9:30 new update file...  good job.

**Comment by Sophia-yu-kk** [comment]
Yes, another version was subsequently updated and the problem was solved. Thanks for the feedback.
