### ISSUE TITLE
Dashboard language support: Spanish

### ISSUE THREAD

**Issue by simbadMarino** [bittorrent/go-btfs#150]
Hello @daniel-tron, dev team, a community member (@juchambo - Julian) made a great effort to translate the dashboard text so we can have the possibility to switch to Spanish in later versions. Our Spanish community is growing fast and we would love to have Spanish language supported! :) 

Did you know Spanish is at [second place ](https://www.babbel.com/en/magazine/the-10-most-spoken-languages-in-the-world) on the top 10 most spoken languages in the world?

If we implement Spanish we'll be covering already the top 3 most spoken languages ;)

Please feel free to take the attached file. I personally reviewed and corrected a few typos (I'm a native Spanish speaker) and looks OK.

Thank you in advance for considering this update!
[es_ES.zip](https://github.com/bittorrent/go-btfs/files/8439588/es_ES.zip)

**Comment by Sophia-yu-kk** [comment]
This feature is expected to go live in V2.1.4.

**Comment by Sophia-yu-kk** [comment]
'storage_path':'Storage Path',
'change': 'Change',
'change_success':'Change Path Successful !',
'BTFS_10_withdraw': 'BTFS 1.0 Withdraw',
'withdraw10':'Withdraw',
'10_withdraw_description': 'The withdrawal will be sent to Node’s corresponding TRON address.',
'node_tron_addr': 'Node TRON address',
'available': 'Available',
'BTFS_10_withdraw_limit': 'Per withdrawal limit',
'storage_path_confirmation': "Storage Path Confirmation",
'storage_path_info': "Are you sure you want to change BTFS storage to this path ?",

**Comment by Sophia-yu-kk** [comment]
> Hello @daniel-tron, dev team, a community member (@juchambo - Julian) made a great effort to translate the dashboard text so we can have the possibility to switch to Spanish in later versions. Our Spanish community is growing fast and we would love to have Spanish language supported! :)
> 
> Did you know Spanish is at [second place ](https://www.babbel.com/en/magazine/the-10-most-spoken-languages-in-the-world) on the top 10 most spoken languages in the world?
> 
> If we implement Spanish we'll be covering already the top 3 most spoken languages ;)
> 
> Please feel free to take the attached file. I personally reviewed and corrected a few typos (I'm a native Spanish speaker) and looks OK.
> 
> Thank you in advance for considering this update! [es_ES.zip](https://github.com/bittorrent/go-btfs/files/8439588/es_ES.zip)

This section is a new field, can you provide the response in Spanish? Thanks

**Comment by juchambo** [comment]
storage_path':'Ruta de Almacenamiento',
'change': 'Cambiar',
'change_success':'Cambio de ruta exitoso!',
'BTFS_10_withdraw': 'Retirar de BTFS 1.0',
'withdraw10':'Retirar',
'10_withdraw_description': 'El retiro será enviado a la dirección TRON correspondiente al NODO.',
'node_tron_addr': 'Dirección TRON del Nodo',
'available': 'Disponible',
'BTFS_10_withdraw_limit': 'Límite por retiro',
'storage_path_confirmation': "Confirmaciin de la Ruta de Almacenamiento",
'storage_path_info': "Estás seguro que querés cambiar el Almacenamiento BTFSa esta Ruta ?",

**Comment by Sophia-yu-kk** [comment]
> 
Thank you for your support of the BTFS community and have a great day!

**Comment by ZeroCool1974-BR** [comment]
**Portuguese_BR**

'storage_path': 'Pasta de armazenamento',
'change': 'Trocar',
'change_success': 'Pasta trocada com sucesso!',
'BTFS_10_withdraw': 'BTFS 1.0 Sacar',
'withdraw10': 'Sacar',
'10_withdraw_description': 'O saque será enviado para o endereço TRON do servidor correspondente.',
'node_tron_addr': 'Endereço TRON do servidor',
'available': 'Disponível',
'BTFS_10_withdraw_limit': 'Limite de retirada',
'storage_path_confirmation': "Confirmação de alteração de pasta de armazenamento",
'storage_path_info': "Tem certeza que deseja alterar a pasta BTFS para este caminho?",

**Comment by Sophia-yu-kk** [comment]
The issue has been forwarded by the BTFS community to the appropriate department and is awaiting further processing.
