### ISSUE TITLE
Dashboard language translated to pt-BR

### ISSUE THREAD

**Issue by ZeroCool1974-BR** [bittorrent/go-btfs#151]
I want to help providing a translation to pt-BR, I'm brazilian so I can help translate anything to my beloved mother language. Thanks to all Devs for your hard work so far, I really belive in BTFS!

[pt_BR.zip](https://github.com/bittorrent/go-btfs/files/8442013/pt_BR.zip)

**Comment by simbadMarino** [comment]
This is great thank you! The more languages we have the wider our audience :)

**Comment by Sophia-yu-kk** [comment]
According to the development team feedback, the demand has been added to the product requirements pool, the community side will first close this issue, thank you for your support.
