### ISSUE TITLE
Lost Vault balance and contracts after 2.1.2

### ISSUE THREAD

**Issue by jaffsys** [bittorrent/go-btfs#152]
I lost all contracts and Vault balance after upgrading to 2.1.2. Occupied storage remains unchanged

**Comment by simbadMarino** [comment]
Please follow the next instructions to recover your balance, make sure to withdraw your vault balance to your BTTC wallet =)

![attachment](https://user-images.githubusercontent.com/11146636/162498327-823c22b7-25c1-4d9e-9139-c2400f95a0f9.png)

**Comment by jaffsys** [comment]
Hello,

This solution solved the balance recovery issue but my contracts are still zero in 2.1.2

**Comment by Sophia-yu-kk** [comment]
Theoretically, nodes with 8 or more points have a chance to get a contract, but the probability of a single node getting a contract is not fixed.

**Comment by jaffsys** [comment]
I had 29 contracts on 2.1.1

**Comment by jaffsys** [comment]
I had 29 contracts on 2.1.1
