### ISSUE TITLE
btfs2.1.2 constantly error I don't recognize contracts

### ISSUE THREAD

**Issue by Alexkkkkk** [bittorrent/go-btfs#155]
there are already 10 such errors
2022-04-10T12:21:40.856+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAmSipd8vyP2Ck8on6MZAe5
8b3Vu84Dbgg3LQGbXDC5X5is) for cid (QmZf4WapkfexDt16tGUyWFhBJh5BvebVzaP2ANFNLYdYJ
r) not requested

**Comment by Rockster34** [comment]
That error can mainly be ignored :)
