### ISSUE TITLE
I had 29 contracts on 2.1.1

### ISSUE THREAD

**Issue by jaffsys** [bittorrent/go-btfs#158]
I had 29 contracts on 2.1.1

_Originally posted by @jaffsys in https://github.com/bittorrent/go-btfs/issues/152#issuecomment-1095890646_

**Comment by rooie1971** [comment]
think it's a display bug, could you try firefox, with me on chrome 0 contracts on firefox it show correct amount of contracts

**Comment by jaffsys** [comment]
Hi
I am already using firefox :(
I already tried restarting daemon and clearing cookies

**Comment by jaffsys** [comment]
No, it is not solved. Currently it shows 11 contracts and 3.22GB used

**Comment by Sophia-yu-kk** [comment]
btfs storage contracts sync host
btfs storage contracts list host
Execute these two commands, and the returned results are provided below.
Also, provide the peer id please

**Comment by jaffsys** [comment]
Host ID is 16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB

Results is

{"contracts":[{"contract_id":"5d1d4473-bb99-4d5a-a69e-35e31315903d,a4f57a69-aa13-4f3f-9cab-42049eb44ab1","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-11-23T20:43:43.477935Z","end_time":"2022-05-02T20:43:43.477935Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44639809,"shard_hash":"QmSrUG1v143yhwTvmwe7Mc2qrcycjnfH8WnHzs4SKQmBEm","file_hash":"QmR38vdPaR2c7rXcn9sTnp7wZLgsTMaKpgqCHDAGGvSLVi","last_modify_time":"2022-03-19T07:01:08.502827Z"},{"contract_id":"94285c4d-5486-4820-9f1e-885f4fabb360,863d312f-c165-4c70-9680-42feee9bf74c","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-11-23T21:27:46.044077Z","end_time":"2022-05-02T21:27:46.044077Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44602126,"shard_hash":"QmNnaMGnbUhumXJaav9VGBcjQN7XR7Y1AmDJ95xbihSN2y","file_hash":"QmQQvJijgg2H8LyBFWvc1KkUkqMnc8ANYt7uCEZzdQr9sA","last_modify_time":"2022-04-10T12:17:06.333859Z"},{"contract_id":"5d8fd44d-5cfb-4e0b-ae10-e948c6da01d1,860305a0-537c-4518-a8f5-e14adb971cb0","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-11-26T04:53:02.100634Z","end_time":"2022-05-05T04:53:02.100634Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44582665,"shard_hash":"QmUxtZecEe62fCJPdCjw9DVKFxCL4ajeQYo2Ssb6tebQMz","file_hash":"QmYC4FyU3xw6RF4au99yiRyNMxuYedqT7DPXYeKdN2967y","last_modify_time":"2022-04-07T12:40:48.976467Z"},{"contract_id":"68f8dc8d-c796-469b-9a7a-89e00d6625f1,884fd272-ba1a-450b-9210-e2b06bc99f19","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-11-26T09:12:01.202606Z","end_time":"2022-05-05T09:12:01.202606Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44611240,"shard_hash":"QmX5Lkd8jP6MUCx7fWXCxNwtRcHJbDNdBzjJvVtX63nLAa","file_hash":"QmYhUtnEHBG71d7KZgyrJJTiL42GMnChd5NG1N5tizXQQQ","last_modify_time":"2022-04-08T02:15:36.652205Z"},{"contract_id":"4210bdc0-9ccc-4aa3-b55d-347c946d8de0,58db0597-1e9c-46f7-882b-413572f8439b","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-11-26T11:27:54.099308Z","end_time":"2022-05-05T11:27:54.099308Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44601000,"shard_hash":"QmT5bjwCmpPh52ouFwzLzr72mBZdCn15acrU7pHnAgtekB","file_hash":"QmaVukw1xTPv1SuEgycJnmn9r7nCEYPcntKw8UL3wAbQre","last_modify_time":"2022-04-02T11:42:07.270081Z"},{"contract_id":"c1f4328c-f17a-4136-8b54-db9c4ccee2d5,4b4fc5a9-d808-46f0-8186-cae0f498891b","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmFDt399pBQP3DSpFFYzhrgQw1iZWyk5CLj57Jj4ofCZYn","status":8,"start_time":"2021-11-29T12:07:46.406166Z","end_time":"2022-05-08T12:07:46.406166Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44644520,"shard_hash":"QmU69z12hbJVC6zvqY9rMJQ22VDcrALevkJmHrLuZYzWai","file_hash":"QmXNjWdL5uybxdycntpH8o2wY5DeY4Zjo7msX1XeWVpfr3","last_modify_time":"2022-03-28T11:54:34.407918Z"},{"contract_id":"2e0dc561-eab7-4830-9a74-b35dd4db3eda,4457ac81-419d-4c0a-954f-aeb74087bc15","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2021-11-30T17:15:30.580242Z","end_time":"2022-05-09T17:15:30.580242Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44594753,"shard_hash":"Qma59nU8bXT4E8viDhfeppmTwMj4RsrQpktMi4FH9iky34","file_hash":"QmYW1wbxzfvMoe8Eh1tmH2gtXGL1QE77Mzo2Wo9kT2aj1d","last_modify_time":"2022-04-10T07:53:43.659696Z"},{"contract_id":"f2872fcd-7365-4c41-b235-1aac118930c2,3b746c24-ab13-428d-a9de-ef93e836b511","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T06:22:36.866141Z","end_time":"2022-05-15T06:22:36.866141Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44607144,"shard_hash":"QmYZBpi9hxbyb6f2HwGAbqa5j9KnE9zaUms1e68H5MFiQc","file_hash":"QmVpv6miEsMrm6QAoiiNLcf6F3VLtvq9UjFEA7bHkmbAAu","last_modify_time":"2022-04-14T15:07:13.263723Z"},{"contract_id":"04ee93f2-f15b-4257-a226-3d97516bd36c,d30d3364-585b-4811-96b0-809f0e391fe4","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T07:12:08.348526Z","end_time":"2022-05-15T07:12:08.348526Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44660699,"shard_hash":"QmfB7oLitxJjRhEfuDAgiW72YxrkrkmeexHsRYRFTX8CmX","file_hash":"QmdrhyR4i6CRaKGwTeERvZLZdnnnEFZQ7Ak8z4zcw4FiVt","last_modify_time":"2022-03-13T00:34:47.606793Z"},{"contract_id":"3aaee217-bc3b-47d7-98c0-3b6d93e3587e,0ae0f122-860d-477a-9ad4-d31abcc1794d","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T07:33:20.208592Z","end_time":"2022-05-15T07:33:20.208592Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44640219,"shard_hash":"QmVvigRfhDzXW9UYXC3N5SSJEtqZQCSSyfdSTeNHmzsRMS","file_hash":"QmUcuoyFkhoaX9CZrC9PPXo3eeVWzb6yAheC4wKiEjEExx","last_modify_time":"2022-04-14T18:09:07.138384Z"},{"contract_id":"6f92c8a0-529c-4fd4-88da-e21669f5ec6a,6f2d0ed0-4285-4494-ba18-02b8ad626a1f","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T07:47:33.306939Z","end_time":"2022-05-15T07:47:33.306939Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44673089,"shard_hash":"Qmer5mLD3p373J8VsHy4cPrtgtbXbP51AwDupwtST3y5fT","file_hash":"QmPqbZ8rbgM3cCyP996qNJRt18hLgs6XfiFJbhSGCdXbUE","last_modify_time":"2022-04-14T08:29:34.887866Z"},{"contract_id":"cc1a1923-58bd-4cf8-b968-91ad3f968c23,9aadd7b6-0f4c-4ad5-a78d-3e68cd5707cd","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T07:40:26.507185Z","end_time":"2022-05-15T07:40:26.507185Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44678619,"shard_hash":"Qmc2aN74cLk9iNCK9F8ZieGfHcPuwDbwAGhWz9SR4nnm9s","file_hash":"QmdCrt8tC9TYKzsbkJbyH678kVvGNact3DeqxyVmwtBdb5","last_modify_time":"2022-04-14T00:37:14.027382Z"},{"contract_id":"8be78da1-cd72-4b23-b046-615d3081a403,0a8f066a-32d0-41bc-a783-8894c2889b23","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAm8ZzjuM6Hzc18XDKi8PxwuRDV78z62VKuzJJqd9sc9HEF","status":2,"start_time":"2021-12-06T09:42:12.361874Z","end_time":"2022-05-15T09:42:12.361874Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44629160,"shard_hash":"QmTus8L1WMjRb5Mj5rmZEGiKQWa8sob9XvoUPRrtD9BEss","file_hash":"QmWaBUCV84WGSZVvMTgQqFGdR3SrVZ9Hi5Ex42aPXbAPGu","last_modify_time":"2022-03-25T10:31:45.104318Z"},{"contract_id":"7595c30d-de4c-4dc3-91bd-172e495a39a0,b78c2a35-32a6-48ad-9391-51720ce237de","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmFDt399pBQP3DSpFFYzhrgQw1iZWyk5CLj57Jj4ofCZYn","status":2,"start_time":"2021-12-15T22:03:54.364501Z","end_time":"2022-05-24T22:03:54.364501Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44602843,"shard_hash":"QmSQ8hiXyptVTuYi4DUfSK3wX3uZ17mDr4H19JMRaSd15Y","file_hash":"QmYTPqZKarUpCWf4yNbTkr8DFLKH1gqJA7Aqnt29GiWarp","last_modify_time":"2022-04-06T15:42:33.290191Z"},{"contract_id":"7c1c3808-52d4-4389-9c71-2bdea76f7e45,a765433c-842b-42c2-ad03-e68872aea160","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2021-12-20T20:16:34.262817Z","end_time":"2022-05-29T20:16:34.262817Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44591579,"shard_hash":"QmTcftjNEBkfQrXWcUyG5TzmE1SWREjr1krRCHFqDsnvL8","file_hash":"QmNovbbMUx8jpqKKcQ6mefVp28SMPx9R643tPFEQj4LqmB","last_modify_time":"2022-03-24T01:35:05.000451Z"},{"contract_id":"92281348-5167-454d-80e6-34fc54350dd7,4299da41-0dca-4798-8d10-8b58bc1ad2ff","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmFDt399pBQP3DSpFFYzhrgQw1iZWyk5CLj57Jj4ofCZYn","status":2,"start_time":"2021-12-24T00:55:08.319362Z","end_time":"2022-06-02T00:55:08.319362Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44610113,"shard_hash":"QmZSYph9BXAs46Xc5cDM6kZJ5sJ2WJ7TCHQ759vmPMja2N","file_hash":"QmcavigtAUGch38tjkRJ6V8QXzNJP6ELTQu5TxZmTJPuNZ","last_modify_time":"2022-03-25T08:32:50.540629Z"},{"contract_id":"8e03799a-5559-4cc9-afe5-fe140303fdb1,577cf111-0321-47a2-bb37-2345455da865","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2021-12-27T09:57:43.552226Z","end_time":"2022-06-05T09:57:43.552226Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44666843,"shard_hash":"QmYJszmuZkRc6jdLJHXUUpgHuYczzo1hxwjRpVZ38LDRT3","file_hash":"QmUz5hL7Lg5T6Berso4qMa62nFLXoSr672LMDRraZ48EtB","last_modify_time":"2022-03-15T21:57:31.024104Z"},{"contract_id":"a711cab9-be5c-4811-a9de-9f79681fab6b,58c176ff-bb10-41db-8431-6f7227b61bd1","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2021-12-29T12:59:35.053848Z","end_time":"2022-06-07T12:59:35.053848Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44678312,"shard_hash":"QmcHLrMwNjokqxDf9KvhNn9fR2T5iLq431CFfDQbRVXe4f","file_hash":"QmNsfquUaWcdRtXQV1v1kLvfnmF4Ux6wPd9AT7M8YwjRF7","last_modify_time":"2022-04-11T22:51:51.982212Z"},{"contract_id":"6949aef5-2a64-4096-88be-ed72c320ab6f,380762f2-486b-42cc-b5c4-3298f4962adc","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2022-01-06T04:20:34.81689Z","end_time":"2022-06-15T04:20:34.81689Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44651995,"shard_hash":"QmV4X53e4oUfTSzhbCrHCjdZo8uAGJp9UHheWXXPb2Wsma","file_hash":"Qmf8iwe3Yu7iEHvTJRTm6qUZFwdAHXorv4FD2ziNAoX6mf","last_modify_time":"2022-04-10T12:05:13.085526Z"},{"contract_id":"a854efad-84d9-4821-9210-8297d6790447,b85c98ca-7bb7-4d64-ab24-1304855f2305","host_id":"16Uiu2HAmA2Liv4Av6CeGwL57cXakm3jixorrQtdXDiWP3bcmYkvB","renter_id":"16Uiu2HAmEkpEbVib91qtYDRXVMJw8NYd1begFnVcdpjyeLyxMgdQ","status":2,"start_time":"2022-01-15T11:46:06.743171Z","end_time":"2022-06-24T11:46:06.743171Z","next_escrow_time":"0001-01-01T00:00:00Z","compensation_paid":0,"compensation_outstanding":0,"unit_price":125000,"shard_size":44661928,"shard_hash":"QmaexAnKSdv8rCGJ36ZvHTGw2AK8HK51GgmbFLNNPK8cSB","file_hash":"Qma4VJYrw1J7xe1t7q3UbhueGhxWBPWUtjSzu25sFS9D7M","last_modify_time":"2022-04-17T13:35:26.787553Z"}]}

**Comment by Sophia-yu-kk** [comment]
> 

‘btfs storage contracts stat host’
Please execute this command and see the return result, thanks

**Comment by jaffsys** [comment]
{"active_contract_num":62,"compensation_paid":0,"compensation_outstanding":0,"first_contract_start":"2021-11-23T18:16:41.590435Z","last_contract_end":"2022-06-30T07:03:10.669798Z","role":0}

**Comment by Sophia-yu-kk** [comment]
> {"active_contract_num":62,"compensation_paid":0,"compensation_outstanding":0,"first_contract_start":"2021-11-23T18:16:41.590435Z","last_contract_end":"2022-06-30T07:03:10.669798Z","role":0}

Open the dashboard and see what the number of contracts is, please take a screenshot and post it here, thanks.

**Comment by Sophia-yu-kk** [comment]
What I need to confirm is that the number of contracts that have been stored to your feedback has become less after upgrading from V2.1.1 to V2.1.2? Please confirm.

**Comment by jaffsys** [comment]
> 

![image](https://user-images.githubusercontent.com/89365864/164909416-6de29ba2-2d0a-4b8d-bb0a-07f0637bbb4f.png)

**Comment by jaffsys** [comment]
> What I need to confirm is that the number of contracts that have been stored to your feedback has become less after upgrading from V2.1.1 to V2.1.2? Please confirm.

I was able to see 39 contracts in 2.1.1

**Comment by Sophia-yu-kk** [comment]
Hello, thank you very much for your feedback. After confirming, it is normal for the contracts to become less and the expired contracts will be filtered out.
