### ISSUE TITLE
No Vault Address

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#159]
After update from 2.1.1 to 2.1.2, I get no Vault address and daemon is not running.
With command btfs id, I get "VaultAddress": "",

After start daemon, the last message is: "The address of Tron format is:"
Nothing more.
What can I do?

Thanks

**Comment by Sophia-yu-kk** [comment]
It is usually caused by the network. It is recommended to check the network connection and the geographical location of the location for network connection restrictions.

**Comment by chris110110** [comment]
Also I have no dashboard.
Before update everything was working fine.
