### ISSUE TITLE
Error continuously showing up in Terminal

### ISSUE THREAD

**Issue by EffSki** [bittorrent/go-btfs#160]
Hi,

I am on BTFS 2.1.2 and I am continuosly getting the following error coming up in Terminal window.

022-04-12T21:30:49.466+1000	ERROR	tcp-tpt	go-tcp-transport@v0.2.3/tcp.go:42	Failed to enable TCP keepalive: set tcp4 192.168.0.35:1234->94.198.53.136:4021: setsockopt: invalid argument
2022-04-12T22:15:57.293+1000	ERROR	tcp-tpt	go-tcp-transport@v0.2.3/tcp.go:42	Failed to enable TCP keepalive: set tcp4 192.168.0.35:1234->94.198.53.238:4048: setsockopt: invalid argument

Can you please let me know what it is and what to do to fix this.

Cheers
Efraim

**Comment by Sophia-yu-kk** [comment]
This error report can be ignored first, does not affect the contract acquisition, the subsequent display optimization will be carried out, thanks for the feedback.
