### ISSUE TITLE
No payments

### ISSUE THREAD

**Issue by AlexeiKaDev** [bittorrent/go-btfs#161]
Hi. about two month no payments for my contracts.
Host id 16Uiu2HAmHWX8aZC1tSNE7wGfNQFD5VVPaJE798mew1fBH4Gv47wn

**Comment by Sophia-yu-kk** [comment]
Do you mean the airdrop earnings part?

**Comment by AlexeiKaDev** [comment]
No, contracts ,wich i had before. But airdrops also nothing happens.

чт, 14 апр. 2022 г., 6:58 Sophia ***@***.***>:

**Comment by Sophia-yu-kk** [comment]
BTFS2.0 earnings are based on the actual rewards received, distributed reward distribution form, there is no delay in the issuance of rewards.
