### ISSUE TITLE
Error bitswap

### ISSUE THREAD

**Issue by InTeamLife** [bittorrent/go-btfs#164]
Good afternoon.
I constantly encounter this error, tell me if it is critical?
![image](https://user-images.githubusercontent.com/30119373/163429583-96ec443a-a93b-44dc-882d-0d98e27d8738.png)
HOST ID - 16Uiu2HAmBxaJ4FmWdUkzqzo8EKqofZBGyLYptsSeH6pmgFcFArMv

**Comment by Sophia-yu-kk** [comment]
This error report can be ignored, does not affect the contract acquisition, the subsequent optimization of the error report hint.Thank you for your feedback.
