### ISSUE TITLE
Tx bttc pending over 15h 

### ISSUE THREAD

**Issue by mzulfikaaar** [bittorrent/go-btfs#169]
I just sent my btt to other wallet address in tokenpocket, i use default gas and gwei. This is the tx hash, when this tx Will canceled or successful?
https://bttcscan.com/tx/0x431c4fc94b8184922b4a879684dcf013870bd3da6b7fc3fb61c840db6be6de24
I hope you can help me

**Comment by Sophia-yu-kk** [comment]
Hello, thank you very much for your question. After checking, this issue is a chain transfer issue and we recommend you to ask on this channel. https://discord.gg/4SHgd9YV
