### ISSUE TITLE
Change my hosting folder error

### ISSUE THREAD

**Issue by wecando168** [bittorrent/go-btfs#17]
I want to change the storage path. When I enter: btfs storage path G: \ btfs20host, it prompts me that the parameter storage size is missing. What unit does this storage size use? For example, I want to set a storage capacity of 300g or 1t
I did a test and executed the command: btfs storage path G: \ btfs20host 300g
I saw some files copied to the G: \ btfs20host folder
Daemon window prompt:
Received interrupt signal, shutting down...
PS F:\BTFS20> btfs daemon --chain-id 1029
Initializing daemon...
go-btfs version: 2.0. 0-8fbb7c2
Repo version: 10
System version: amd64/windows
Golang version: go1. fifteen point one five

Error: no BTFS repo found in C:\Users\Administrator\. btfs.
please run: 'btfs init'
PS F:\BTFS20> btfs init
Generating TRON key with BIP39 seed phrase...
Master public key: 
XXXXXXXXXXXXXXXXXXXXXXXXXX
Smrpunb
initializing BTFS node at G:\BtfsHost
Error: btfs configuration file already exists!
Reinitializing would overwrite your keys.

**Comment by daniel-tron** [comment]
You can set system environment  BTFS_PATH to customize .btfs folder location.

**Comment by wecando168** [comment]
It seems that this problem has been solved. How should I control the maximum space that can be provided to him




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bittorrent/go-btfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bittorrent/go-btfs] Change my hosting folder error (Issue #17)





 
You can set system environment  BTFS_PATH to customize .btfs folder location.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daniel-tron** [comment]
Try search 'StorageMax' in .btfs/config

**Comment by wecando168** [comment]
Thank you. This problem has been solved. The next problem is that the current system stores files in one folder. If I have two hard disks, can I enable two nodes on the same computer? At present, I see that different ports can be used through the relevant settings of "addresses" in "config", but how to set two environments to specify different paths, Btfs is used by default_ Path specifies the path. Can this name be modified or customized?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bittorrent/go-btfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bittorrent/go-btfs] Change my hosting folder error (Issue #17)





 
Try search 'StorageMax' in .btfs/config
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daniel-tron** [comment]
Technically you can do that, not sure if we change node policy in further. btfs only read the environment when startup, that's mean you can:
1. set env
2. start node 1
3. set env to another path
4. start node 2
-------------------------------------------
btw: we use [this tool](https://github.com/TRON-US/iptb-btfs-plugins) in our test lab to manage multiple node in same vm, you can try it,

**Comment by wecando168** [comment]
OK, thanks. Although the operation is a little troublesome, it seems that this problem can be solved at present!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bittorrent/go-btfs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 晚上11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bittorrent/go-btfs] Change my hosting folder error (Issue #17)





 
Technically you can do that, not sure if we change node policy in further. btfs only read the environment when startup, that's mean you can:
  
set env
 
start node 1
 
set env to another path
 
start node 2
  
 
btw: we use this tool in our test lab to manage multiple node in same vm, you can try it,
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
