### ISSUE TITLE
btfs2.1.3 ERROR

### ISSUE THREAD

**Issue by Alexkkkkk** [bittorrent/go-btfs#173]
Daemon is ready
Experimental.Analytics is overridden by Experimental.StorageHostEnabled
Current host stats will be synced
Current host settings will be synced
2022-05-10T13:14:02.970+0300    ←[31mERROR←[0m  core/commands   commands/wallet.
go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: Es
crowClient: rpc error: code = Canceled desc = context canceled
2022-05-10T13:50:46.304+0300    ←[31mERROR←[0m  core/commands   commands/wallet.
go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: Es
crowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc erro
r: code = Unknown desc =
2022-05-10T14:15:57.575+0300    ←[31mERROR←[0m  core/commands   commands/wallet.
go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: Es
crowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc erro
r: code = Unavailable desc = Service Unavailable: HTTP status code 503; transpor
t: received the unexpected content-type "text/html"
2022-05-10T16:06:03.397+0300    ←[31mERROR←[0m  core/commands   commands/wallet.
go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: Es
crowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc erro
r: code = Unavailable desc = unavailable

**Comment by laocheng-cheng** [comment]
Hi，do you call the command to check the balance?
It looks like the access timed out, you can try a few more times to see.
