### ISSUE TITLE
QoL improvement: Timestamped console log

### ISSUE THREAD

**Issue by Rockster34** [bittorrent/go-btfs#176]
This may be one of the easiest to implement things is to add a timestamp into the console log for i.e file uploads, swaps, errors, etc,.

just to add a bit more troubleshooting into the program since now it's very cluttered at where stuff starts and where it ends especially if you get a dozen contracts in like a short period of time.

**Comment by simbadMarino** [comment]
I second this one! Timestamps is gonna improve debugging!

**Comment by Sophia-yu-kk** [comment]
The community will assist you in providing feedback to the developers on this request. Thank you for your support of the btfs project.
