### ISSUE TITLE
Not access to Dashboard remotely

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#177]
Hello,
I have a VPS - Ubuntu 20.04, located in Germany, i installed BTFS script v. 2.1.3 - BTTC on it, working without issues. I log to the server through PUTTY on my Windows machine - setting a tunnel L5003 127.0.0.1:5003 L8080 127.0.0.1:8080. Problem is when i stop PUTTY, process and signal from server is lost. I tried ssh -L 5003:127.0.0.1:5003 root@my_server but received: bind [127.0.0.1]:5003: Address already in use. When i change port - Unable to connect. How can achieve that, i want to monitor process in my dashboard?

**Comment by Sophia-yu-kk** [comment]
> Hello, I have a VPS - Ubuntu 20.04, located in Germany, i installed BTFS script v. 2.1.3 - BTTC on it, working without issues. I log to the server through PUTTY on my Windows machine - setting a tunnel L5003 127.0.0.1:5003 L8080 127.0.0.1:8080. Problem is when i stop PUTTY, process and signal from server is lost. I tried ssh -L 5003:127.0.0.1:5003 root@my_server but received: bind [127.0.0.1]:5003: Address already in use. When i change port - Unable to connect. How can achieve that, i want to monitor process in my dashboard?

Can you take a screenshot of the dashboard error report?

**Comment by Sophia-yu-kk** [comment]
https://linux.die.net/man/1/autossh 
It is recommended that you use the tool autossh，hope it can helps you and have a nice day~
