### ISSUE TITLE
Error: miss recaptcha code param

### ISSUE THREAD

**Issue by endofthepain** [bittorrent/go-btfs#178]
There any solutions for this case, i cant enter dashboard because need 100 BTT for activated, in here i want withdrawal my old btt 

![Screenshot_440](https://user-images.githubusercontent.com/11496089/174450207-522a8464-e9ee-4d3c-bb93-7c0e46cef232.png)

**Comment by Sophia-yu-kk** [comment]
Upgrading to BTFS version 2.0 requires BTT activation. If you do not wish to spend 100 BTT on BTFS 2.0 activation, you can withdraw your wallet balance via BTFS 1.0.

Note that currently BTFS 1.0 is not available for airdrop rewards.

Thank you for your support.

**Comment by endofthepain** [comment]
It still same error in btfs 1.0

**Comment by endofthepain** [comment]
![Screenshot_441](https://user-images.githubusercontent.com/11496089/174599387-d955116e-49eb-423a-b620-6ca5929684ec.png)

**Comment by Sophia-yu-kk** [comment]
btfs wallet withdraw [--password=<password> | -p] [--] <amount>

set password
btfs wallet password [--password=<password> | -p] [--] <password>

**Comment by endofthepain** [comment]
i have beeen set the password and see my screenshot the error still same 
![Screenshot_442](https://user-images.githubusercontent.com/11496089/174781368-df881e68-c77e-47b1-9799-254a285f4068.png)

**Comment by WalletSupportHelp** [comment]
Kindly open this live chat link to talk to TECHNICAL SUPPORT directly on your issue https://direct.lc.chat/14236062/

**Comment by Sophia-yu-kk** [comment]
btfs wallet withdraw -p 123456 2825971901

**Comment by endofthepain** [comment]
look my screenshot still error :)

**Comment by endofthepain** [comment]
what version of your btfs

**Comment by endofthepain** [comment]
![Screenshot_446](https://user-images.githubusercontent.com/11496089/175143357-9d0bda19-1ceb-4f89-bce5-40a50d5cf1b3.png)

**Comment by Sophia-yu-kk** [comment]
Would it be better if the input is -p=123456? You can try it

**Comment by endofthepain** [comment]
![Screenshot_450](https://user-images.githubusercontent.com/11496089/175279213-f1371134-65aa-4e34-9a1e-2cfc84f0c2ad.png)

**Comment by endofthepain** [comment]
![WhatsApp Image 2022-06-27 at 3 27 20 AM](https://user-images.githubusercontent.com/11496089/175867812-1db04bc5-17b9-4c49-9e83-f15f77d7df43.jpeg)

**Comment by Sophia-yu-kk** [comment]
> ![WhatsApp Image 2022-06-27 at 3 27 20 AM](https://user-images.githubusercontent.com/11496089/175867812-1db04bc5-17b9-4c49-9e83-f15f77d7df43.jpeg)

Is this error after clicking the "btfs1.0 withdraw" button?

**Comment by Sophia-yu-kk** [comment]
You can try compiling the program yourself in a linux environment.

**Comment by pkyriacou** [comment]
An observation: Seems weird that you have 5000+ contracts but the storage used is only 20MB

**Comment by endofthepain** [comment]
> An observation: Seems weird that you have 5000+ contracts but the storage used is only 20MB

its old btfs, i have been shutdown our all server from last year

**Comment by endofthepain** [comment]
![Screenshot_455](https://user-images.githubusercontent.com/11496089/175915252-76b8db2d-db1a-4fac-b8a5-b58013e58c5e.png)
still same error after build from source code

**Comment by Sophia-yu-kk** [comment]
Since this issue depends on other parts, it is temporarily closed in the BTFS repository.
