### ISSUE TITLE
No income for a long time. Can you check it?

### ISSUE THREAD

**Issue by wbkys** [bittorrent/go-btfs#179]
16Uiu2HAmUVD8vr3hfW5zeHRkfvvR8maY82YnrR7K4RT9n4P8Po6o

No income for a long time. Can you check it?

**Comment by Sophia-yu-kk** [comment]
https://scan.btfs.io/#/node/16Uiu2HAmUVD8vr3hfW5zeHRkfvvR8maY82YnrR7K4RT9n4P8Po6o
After querying, the status of this node is normal. Theoretically, a node with a score of more than 8 has a chance to get a contract. Currently there are more nodes in the network and there is more competition. Thank you for your support.
