### ISSUE TITLE
How to recharge a wallet? 

### ISSUE THREAD

**Issue by zvictorp** [bittorrent/go-btfs#182]
Dear community

Please, give me a piece of advice on how to deposit my wallet in order to let the daemon start.

There are two addresses: TRON and BTTC.
All platforms work only with the TRON blockchain.

I have some amount of BTTC on my Binance wallet, but it allows me to deposit only via TRON and BSC.

What should I do?

Thank you.

**Comment by simbadMarino** [comment]
If Binance does not let you withdraw to BTTC network I advice you to withdraw to a TRON/BSC account you control, then bridge to BTTC using the official way (https://wallet.bt.io/bridge)

 **Always remember to send small quantities first to make sure you introduced the right addresses**

E.g. to bridge from TRON to BTTC you should do something like this:
![image](https://user-images.githubusercontent.com/11146636/174805174-adf29700-9331-4205-80a7-45356a7230a9.png)

Receiving address should be your node BTTC Address.
