### ISSUE TITLE
btfs2.1.3

### ISSUE THREAD

**Issue by Alexkkkkk** [bittorrent/go-btfs#183]
2022-07-03T06:35:19.106+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAmUjrAKpZ8bmtC6McrgZof
yv48nY1HVgWoLqfWVr3Ykn6k) for cid (QmRcz2isGG6DrAxEKfY16zmnBwA24j4VL4DRre91cKpnX
b) not requested
2022-07-03T06:51:34.750+0300    ←[31mERROR←[0m  bitswap providerquerymanager/pro
viderquerymanager.go:338        Received provider (16Uiu2HAkuW5W62zA9ksqUkNnKaPE
ceBRuDkmxdtSAxxxDXhGiRw6) for cid (Qma9WHZ1m1ooBF9LvKSZSBkMtZhvCFGqJKqSBT7hza9pf
Z) not requested

**Comment by Sophia-yu-kk** [comment]
“bitswap providerquerymanager/pro
viderquerymanager.go:338 ”
Hello, this error report can be ignored, does not affect the contract acquisition, and will subsequently feedback to the development team for error reporting optimization.
