### ISSUE TITLE
Network Unstable

### ISSUE THREAD

**Issue by TheBestBadGamer** [bittorrent/go-btfs#184]

**Comment by ZeroCool1974-BR** [comment]
I have two nodes with this same error:

16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL
![network_unstable_w4dul](https://user-images.githubusercontent.com/91059173/177065185-8b4e9a67-39e7-498e-a5ae-da77d4b12606.jpg)

16Uiu2HAkv9Lu7ggH8Jtbw5nMFx8kzbFLC1aFwGFQsvuJoJg8pq5G
![network_unstable_8pq5G](https://user-images.githubusercontent.com/91059173/177065191-d42298ca-594e-4127-815e-5597dfcd0fd3.jpg)

**Comment by Sophia-yu-kk** [comment]
Unstable network is a relatively common phenomenon in community feedback, and usually this tip goes away after a few hours.If it still exists, you need to check the connection status of the network, it is difficult to make a specific judgment on our side of the community.
