### ISSUE TITLE
My node keeping restart.

### ISSUE THREAD

**Issue by holychen1234** [bittorrent/go-btfs#186]
btfs: Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by holychen1234** [comment]
> OS：centos7
BTFSversion：2.1.3-69133e5
ISP：China Telecom
error：Jul  6 08:43:32 localhost systemd: Stopped btfs daemon.
Jul  6 08:43:32 localhost systemd: Started btfs daemon.
Jul  6 08:43:32 localhost btfs: Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": dial tcp 0.0.0.0:443: connect: connection refused
Jul  6 08:43:33 localhost btfs: Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by holychen1234** [comment]
> Please provide more information like BTFS version, OS, etc, have you tried with a different ISP?
OS：centos7
BTFSversion：2.1.3-69133e5
ISP：China Telecom
error：Jul 6 08:43:32 localhost systemd: Stopped btfs daemon.
Jul 6 08:43:32 localhost systemd: Started btfs daemon.
Jul 6 08:43:32 localhost btfs: Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": dial tcp 0.0.0.0:443: connect: connection refused
Jul 6 08:43:33 localhost btfs: Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": dial tcp 0.0.0.0:443: connect: connection refused

**Comment by simbadMarino** [comment]
Did your node worked well before? or failed since the start? 

When I was in China I experienced several problems with p2p connections and had to use VPN several times even for crypto wallets to work properly, if it failed since the beginning try using a VPN and start the daemon again.

**Comment by Sophia-yu-kk** [comment]
Changing the RPC address should solve the problem, this issue is closed first, if you have a new problem, you can reopen the issue
