### ISSUE TITLE
Vault: cannot cash

### ISSUE THREAD

**Issue by Andrju81** [bittorrent/go-btfs#187]
Cashing Status
execution reverted: Vault: cannot cash
What does it mean?
![Clip2Net Menu_2022-07-07_04_21_09](https://user-images.githubusercontent.com/40444286/177669657-092a0456-a9f9-4c79-863c-f38d57ee57cb.png)

**Comment by Sophia-yu-kk** [comment]
How exactly did you perform this operation? You can retry to see the result.

**Comment by Andrju81** [comment]
Is the result the same when cashing out CHEQUES in BTFS Dashboard?
![Clip2Net Menu_2022-07-07_16_09_41](https://user-images.githubusercontent.com/40444286/177783808-1690291b-e9df-4994-a8a0-7b4f734f34c6.png)

**Comment by Sophia-yu-kk** [comment]
Please provide the BTTC address of the node, thank you, so that we can further check

**Comment by Andrju81** [comment]
The Node’s BTTC Address 0x5bd894E550269229115d6d34E527d689D75E2894

**Comment by Sophia-yu-kk** [comment]
Hello, I saw a similar question in the community. Changing the rpc will get it fixed.
https://docs.btfs.io/docs/mainnet-rpc-configure
Suggest you try.

**Comment by Andrju81** [comment]
Changing RPC does not solve the problem.

**Comment by Andrju81** [comment]
My HOST ID: 16Uiu2HAkxf4zCbSFGjidcyS4zsvbqcMFAoU13ZzVi7AuCrjMGHvv
HOST ID from which CHEQUE is not cashed: 16Uiu2HAkydqCRFtfhnkLSFph1rAoU29rsqwTmy62A7chvfwQswwC

**Comment by Andrju81** [comment]
More CHEQUE came in from this host, but I still can't cash them?!...

**Comment by Shawn-Huang-Tron** [comment]
@Andrju81 Hi, could you paste the screenshot data list of CASHING LIST 、CASHING HISTORY and CHEQUE DETAIL?

**Comment by Sophia-yu-kk** [comment]
Hello, this is currently a known issue. It has been fed back to the development team and the cause has been found, and will be optimized in subsequent versions. Thank you very much for your support to the project. Have a great day!

**Comment by Shawn-Huang-Tron** [comment]
@Andrju81 Hi，it sounds like that you have recover your host in another machine or catalog by the same private key. Cause we just can see your data after 05.05.2022. But the scan shows that you have another transaction before that:https://scan.btfs.io/#/node/16Uiu2HAkxf4zCbSFGjidcyS4zsvbqcMFAoU13ZzVi7AuCrjMGHvv
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/107823650/181409680-06835344-4622-4e9f-9872-3c4fe68d7d21.png">
