### ISSUE TITLE
The internet crashes after the 6th node

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#188]
After installation on the 7th node of Ubuntu server the internet dies, not even a page can be opened. Net - 100 Mbit, IP - static. Traffic from 4 nodes in the picture as seen is minimal. What could be the problem?

![sent-received](https://user-images.githubusercontent.com/40600216/177756173-d78f73d1-e532-4a53-9479-fe47e7f60b31.png)

**Comment by Sophia-yu-kk** [comment]
Hello, according to the screenshot you provided, the community side for confirmation.

It is normal for p2p to have some data transmission between nodes in order to ensure connectivity.

Thank you for your support.
