### ISSUE TITLE
bttcscan is not working

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#189]
When i try to open link to address of bttcscan to see my transactions, nothing happen, why is that? Links to BTTC Address and Vault Address just not working...

**Comment by Sophia-yu-kk** [comment]
Can you send me the link you can't open to see it? I'll try to help you solve the problem

**Comment by Sophia-yu-kk** [comment]
https://t.me/BitTorrentChain
If it's the BTTC page that won't open, you can give feedback directly inside this group. This issue is about to time out, so close it first on this side.
