### ISSUE TITLE
 btfs storage upload error

### ISSUE THREAD

**Issue by huarong8** [bittorrent/go-btfs#191]
btfs storage upload QmXb6dddvM5hngmuvFg9nxLzbNXfNXHVakTkpHwchCHaoE
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x266ada0]

goroutine 43 [running]:
github.com/bittorrent/go-btfs/core/commands/storage/upload/upload.glob..func8.1(0xc0004fa480, 0xc0004fa480)
	/tmp/go-btfs/core/commands/storage/upload/upload/upload.go:131 +0x40
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc0019c7eb8, 0x3ad7420, 0xc0004fa480, 0x0, 0x3af7aa0, 0xc000c304a8, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:52 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
	/root/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:31
github.com/cenkalti/backoff/v4.Retry(...)
	/root/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.0.2/retry.go:25
github.com/bittorrent/go-btfs/core/commands/storage/upload/upload.glob..func8(0xc00046e5b0, 0x3b1ccc0, 0xc000453a40, 0x2ad9ec0, 0xc001703680, 0x0, 0x0)
	/tmp/go-btfs/core/commands/storage/upload/upload/upload.go:130 +0x28c
github.com/bittorrent/go-btfs-cmds.(*executor).Execute.func2(0xc001703740, 0x4cafba0, 0xc00046e5b0, 0x3b1ccc0, 0xc000453a40, 0x2ad9ec0, 0xc001703680)
	/root/go/pkg/mod/github.com/bittorrent/go-btfs-cmds@v0.2.14/executor.go:80 +0x66
created by github.com/bittorrent/go-btfs-cmds.(*executor).Execute
	/root/go/pkg/mod/github.com/bittorrent/go-btfs-cmds@v0.2.14/executor.go:79 +0x1b2

**Comment by Sophia-yu-kk** [comment]
This requires a btfs node to be started in order to upload.
