### ISSUE TITLE
Feature Request: View BTFS node console output through BTFS dashboard

### ISSUE THREAD

**Issue by pkyriacou** [bittorrent/go-btfs#192]
Some of us are running BTFS nodes as services on our servers, and do not have a direct console to look at. Console output can be very useful for debugging or monitoring the state of our nodes. It would be much better to have a console built into the BTFS dashboard and also allow the possibility of executing BTFS commands directly through the dashboard.

I have created a concept image of how this would look like
![image](https://user-images.githubusercontent.com/4070784/178521525-ad398045-fa8d-443c-bdb3-0101ff61d953.png)

I'm unsure if this should be posted here or the btfs-dashboard repository, please let me know if I should move it.

**Comment by Sophia-yu-kk** [comment]
Thank you very much for your idea, the community has already sent your idea back to the development team. Have a great day!
