### ISSUE TITLE
testnet environment  failed to find more valid hosts, please try again later

### ISSUE THREAD

**Issue by linyintao2010** [bittorrent/go-btfs#194]
can not upload file show failed to find more valid hosts, please try again later,I try lots of time but all fail.

exec below command：
btfs init -p storage-host-testnet
btfs daemon --chain-id 1029
and valut have wbtt，the address have btt to。
all operation in testnet environment。
peer id 16Uiu2HAmNR3xSySFQAuJ5xcwAnUPJXfqurWrqo9kU4vw6uiCz3jx
can you help solve this problem?

![image](https://user-images.githubusercontent.com/30648802/179210334-2188339a-91af-4134-a238-73f2eb559769.png)

**Comment by Sophia-yu-kk** [comment]
It could be a network problem, or it could be due to the insufficient number of nodes in the current test network, there is no way to be completely sure. If you want to upload files to BTFS network, we suggest you can use nfthub, a platform where uploading files is free, https://nft.btfs.io

**Comment by linyintao2010** [comment]
> 



> It could be a network problem, or it could be due to the insufficient number of nodes in the current test network, there is no way to be completely sure. If you want to upload files to BTFS network, we suggest you can use nfthub, a platform where uploading files is free, https://nft.btfs.io

i can see here have lots of node. than i think it is not a network problem, see below img.

![image](https://user-images.githubusercontent.com/30648802/179463661-d5b00b0c-69c4-4a69-9244-edb34cbcc787.png)

![image](https://user-images.githubusercontent.com/30648802/179463697-5873cc85-81ac-4525-8ad7-517c43b817a5.png)

i want to use btfs to upload file,and then how to solve next ? thanks

**Comment by simbadMarino** [comment]
If you want to store the files you have to use mainnet otherwise you risk losing your files unexpectedly. How much files do you want to store and for how long?



Sent from myMail for iOS


Monday, 18 July 2022 2:35 -0500 from ***@***.***  ***@***.***>:

**Comment by linyintao2010** [comment]
> 
I would like to learn more about BTFS use btfs client by testing the network。Where is a free test environment available use btfs client？Is the test network normal now? What are the requirements for joining the test network。How can I connect to the test network

exec below command:
1、btfs init -p storage-host-testnet
2、btfs daemon --chain-id 1029 --> Proceed to Send testnet tokens to client address in this step
3、Upload my files using BTFS CLI. not work，show failed to find more valid hosts, please try again later.
![image](https://user-images.githubusercontent.com/30648802/179654324-e7f9109b-0e86-45f7-a3ae-8034a38db5fb.png)

thanks

**Comment by simbadMarino** [comment]
Please create a main net environment and I can sponsor you some basic testing with real BTT. I cannot help right now with test net as I'm not using it anymore...  its super cheap to use the main net that it does not even make sense to use the testnet for small to mid size files hehe.

Once you create a main net BTTC address using BTFS give me your address and will send you some thousands BTT to test out :)

Happy to see more people joining!

**Comment by linyintao2010** [comment]
> Please create a main net environment and I can sponsor you some basic testing with real BTT. I cannot help right now with test net as I'm not using it anymore... its super cheap to use the main net that it does not even make sense to use the testnet for small to mid size files hehe.
> 
> Once you create a main net BTTC address using BTFS give me your address and will send you some thousands BTT to test out :)
> 
> Happy to see more people joining!

I'm glad to be part of the BTFS family,I will use BTFS in the main network environment。
I've turned on BTFS daemon and my address is 0x9e346a73e40f6ec656fa047d3c3cbc7c2e23436b。
thanks
