### ISSUE TITLE
Mainnet RPC Configure

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#195]
Hello, i have 3 nodes with configuration:

```
"ChainInfo": {
    "ChainId": 199,
    "CurrentFactory": "0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7",
    "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
    "Endpoint": "https://rpc.bittorrentchain.io/"
  },

```
but on [https://docs.btfs.io/docs/mainnet-rpc-configure](url) "CurrentFactory" is not the same:

```
$ cd ~/.btfs

$ cat config
{
  "ChainInfo": {
    "ChainId": 199,
    "CurrentFactory": "0x9AF4bEc1A30BeC47756Ecef4cf43B91592121bC9",
    "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
    "Endpoint": "https://rpc.bt.io/"
  },
}
```

Which one is the latest, 0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7 or 0x9AF4bEc1A30BeC47756Ecef4cf43B91592121bC9?

Note: When i change in the config with the second "CurrentFactory" address and restart daemon it reverted to the first one, which is strange...
I updated Endpoint to the latest - https://rpc.bittorrentchain.io/.

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/mainnet-rpc-configure
Hello, you can refer to this document, the document provides three rpc alternate. There is no latest, different regions at different times will apply different rpc.
