### ISSUE TITLE
CHEQUES are not cashed in full?!...

### ISSUE THREAD

**Issue by Andrju81** [bittorrent/go-btfs#201]
When cashing out CHEQUES in BTFS Dashboard, there was a partial cashing out of CHEQUES and not a full one!?...
My HOST ID: 16Uiu2HAmH8xCNBgVHnwrhn1ehyzg49zs8C3FwCAwGzkKdsqY9BmS
HOST IDs from which CHEQUE is not cashed in full: 16Uiu2HAm4nyZTd8usst9JQ5RZC3h9zFWGV5Wzz5cNT2Rgq8itqq2 16Uiu2HAmVDy9pcyHNfzBt9Q14vZ5XMGZKDRZnMeLLnVUtcsrgLWP
![Clip2Net Menu_2022-07-22_04_32_46](https://user-images.githubusercontent.com/40444286/180342552-3ab0726e-0a70-4601-8508-c4d72f7c0247.png)
![Clip2Net Menu_2022-07-22_04_26_59](https://user-images.githubusercontent.com/40444286/180342632-86406b42-67c6-499d-8aa4-071ee3503027.png)
![Clip2Net Menu_2022-07-22_04_29_45](https://user-images.githubusercontent.com/40444286/180342634-4c70cdc5-4a5e-4461-8c94-52334c6d1af6.png)
![Clip2Net Menu_2022-07-22_04_30_39](https://user-images.githubusercontent.com/40444286/180342635-7df4aa62-9ec7-48f3-884e-94dc9c0017a6.png)

**Comment by Sophia-yu-kk** [comment]
This is a known issue with the display, and the community has fed back to the development team. Optimization will be done later. Thank you very much for your feedback.
