### ISSUE TITLE
Issues on running btfs deamon in cloud

### ISSUE THREAD

**Issue by SergeySeroshtan** [bittorrent/go-btfs#213]
Hi team.
I'm experimenting with btfs deployment to a cloud.
When run `btfs daemon` on ubuntu I get next errors from time to time:
1.  init settlement err:  init vault service: vault init: 503 Service Temporarily Unavailable
```
Error: init vault service: vault init: 503 Service Temporarily Unavailable: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
```
2. init settlement err:  init swap service error
3. When at least deamon is up, then I have issues with uploading a file to storage.
```
session: 0a5e4ceb-d5ad-47cc-a30f-fdc1a4ae2623 entered state: error, msg: failed to find more valid hosts, please try again later
```

Can you help?

**Comment by simbadMarino** [comment]
Are you running the `btfs daemon` Command as `btfs daemon  —chain id 199`?

Looks to me as you are not selecting BTFS mainnet to run the daemon and upload . Please share the specific steps you followed to initialize and then run the daemon to help more ;)

**Comment by SergeySeroshtan** [comment]
1. `# btfs config show`
```
  "ChainInfo": {
    "ChainId": 199,
    "CurrentFactory": "0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7",
    "Endpoint": "https://rpc.bittorrentchain.io/",
    "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA"
  },
```

2. `# btfs daemon --chain-id 199`
```
Initializing daemon...
go-btfs version: 2.1.3-0510b77
Repo version: 10
System version: amd64/linux
Golang version: go1.15.15
Repo location: /root/.btfs
Peer identity: XXX
the address of Bttc format is:  XXXX
the address of Tron format is:  XXXX
Guide: http://127.0.0.1:5001/hostui
self vault: XXXX
init settlement err:  init swap service error

Error: init swap service error
```

**Comment by Shawn-Huang-Tron** [comment]
@SergeySeroshtan Hi,Is your server's network stable? It sounds like that sometimes it can work but sometimes it failed?
And have you change any config or something else in you btfs?

**Comment by pkyriacou** [comment]
Hmm, are you maybe using a web proxy? If the proxy is having issues serving you the content from the RPC endpoint, this may be the reason you're getting the message.

**Comment by SergeySeroshtan** [comment]
Thanks [Shawn-Huang-Tron](https://github.com/Shawn-Huang-Tron).
The endpoint https://bttc.trongrid.io/ works as a charm. Rest of them do not work.
Is there some helthcheck for endpoints. Maybe you know about some difference in configuration of this RPC nodes?

**Comment by Sophia-yu-kk** [comment]
About the difference of RPC node configuration, it is not very clear on BTFS community side. We suggest you to ask in BTTC channel, thank you very much for your support, there will be relevant staff to help you https://discord.com/channels/491685925227724801/496927712426983435
