### ISSUE TITLE
How to install new version to Ubuntu server

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#216]
Today i see, that my host score fail to 9 because the host version, mine is 2.1.3 - BTTC. How to update to 2.2.0 - BTTC. My system is Ubuntu server 20.04 TLC ?

**Comment by pkyriacou** [comment]
1. Go here: https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.2.0
2. Download the package according to the architecture you're using (amd64 if using 64bit x86 architecture CPU, arm64 if using arm 64bit CPU, run `uname -a` to figure which one it is). If your server is terminal based, use `wget`.
3. `chmod +x` the downloaded file to make it executable
4. Stop the BTFS daemon
5. Replace btfs executable with the one downloaded
6. Start the BTFS daemon
