### ISSUE TITLE
Uncashed cheques appear as cashed

### ISSUE THREAD

**Issue by pkyriacou** [bittorrent/go-btfs#217]
One of my nodes had 3 cheques to cash. I tried cashing all 3 cheques but only 1 of them was actually cashed. I did not receive any WBTT for 2 of the cheques, but now they appear as cashed and I can't cash them.

It should be noted that when trying to cash the cheques, my node wallet had only 20BTT. The UI said that I needed 75BTT for gas fees but it still let me continue. The cashing operation used around 10BTT. I'm not sure if this caused the issue.

BTFS Version at the time of cashing: 2.2.0 but BTFS UI Dashboard was mistakenly set to 2.1.3 URI (QmZM3CcoWPHiu9E8ugS76a2csooKEAp5YQitgjQC849h4b) during the cashing process.

Screenshot from current state of the cheques:
![image](https://user-images.githubusercontent.com/4070784/182188431-9d476eed-4e64-4333-9763-c71be1a87fcc.png)

**Comment by Sophia-yu-kk** [comment]
This is a known issue and will be optimized subsequently, thank you very much for your feedback. Have a nice day!
