### ISSUE TITLE
The coin has not been mined, and the balance is getting smaller and smaller

### ISSUE THREAD

**Issue by wbkys** [bittorrent/go-btfs#219]
![image](https://user-images.githubusercontent.com/12574291/184278932-97a344c6-d781-4406-84fb-4b5a7346c838.png)

**Comment by Sophia-yu-kk** [comment]
The transaction fee looks like the commission for online proof contracts, for online proof contracts you can refer to https://docs.btfs.io/docs/btfs20-architecture#online-proof-contract.
