### ISSUE TITLE
How can i send btt to binance?
I tried few times but it is never arrived.
Thanks

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#220]

**Comment by simbadMarino** [comment]
You need to find out your BTTC address in binance, if you are using binance US BTT is not available there. Please make sure to choose BTTC network and not BSC network, binance will show you the BTT wrapped version on BSC by default (shame on them 😒)

**Comment by chris110110** [comment]
I undersrand but you can only choose BNB or Tron network.
I tried both and nothing work.
Earlier with Tron Wallet it was working but with Metamask not.
The same if i transfer directly from btfs.

**Comment by simbadMarino** [comment]
Got it, then I think your best bet (if you do not want to use another exchange like poloniex ) will be to use the BitTorrent bridge ( https://bt.io/bridge/) you will need to have your metamask wallet connected to the site and then send the BTT to your binance BSC BTTC address…

**Comment by ZeroCool1974-BR** [comment]
You can send BTT to gate.io using BTTC own chain and then withdraw to Tron network (~700k BTT fee), the bridge is way too expensive (~40 TRX) and I don't recommend unless you have TRX staked for energy.

**Comment by chris110110** [comment]
Thanks i will try and let you know if it work.
Regards,
Chris
