### ISSUE TITLE
btfs process running issues

### ISSUE THREAD

**Issue by XMANlsl** [bittorrent/go-btfs#221]
My 2.2.0 version of the btfs process will have a handup status after a period of time after starting to run and then force shutdown, the log shows as follows
"
Daemon is ready
Current host stats will be synced
Current host settings will be synced
InrHandler receive signal: hangup
Start handle signal
Error: canceled

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)"

**Comment by Shawn-Huang-Tron** [comment]
The log shows that the btfs daemon is stopped by yourself(or your OS).How you start your btfs daemon? If you start it in the front end,close the terminal may causes this error.

**Comment by XMANlsl** [comment]
I use nohup btfs daemon & to start in the background, and there is a keep alive script. However, it jumps to close the log soon after startup. I have run the program for more than a year, and there was no problem before. This problem occurred recently.

**Comment by Shawn-Huang-Tron** [comment]
The log indicate that it's interrupted by receving signal.It will help to find out the reason if you can paste your script and tell us your operation step.
