### ISSUE TITLE
Cant withdrawn BTT + No online proof

### ISSUE THREAD

**Issue by MyNameIs2StrikesInYourHead** [bittorrent/go-btfs#222]
Hello,

Since 2.1.3, I can't withdrawn my funds (9M BTT) in one of my node.
I hoped that after the upgrade in 2.2.0 it would have works out, but it's still not working.

When I try to withdraw my 9M BTT to my wallet, it says that the transfer is successful (I tried in GUI + in CLI).
But the funds are still stuck on my node, when I show the balance (GUI + CLI) the funds are still there and couldn't be transfered !

![unknown](https://user-images.githubusercontent.com/111739430/185884652-d97cd8f3-72bd-42f4-90d5-d83a27dc049c.png)
![unknown (1)](https://user-images.githubusercontent.com/111739430/185884655-8b50a943-b9da-48e8-a9e7-5ce11d92941d.png)
![2022-08-22 10_23_50-87 98 155 157_30204 - Remote Desktop Connection](https://user-images.githubusercontent.com/111739430/185884657-2ad0ffed-6790-468a-abf7-45fae6844e3c.png)

The other issue is about the online proof, no online proof has been sent since the upgrade (2-3 weeks ago)... i don't know if it's related to the issue as described above.
![2022-08-22 21_42_25-87 98 155 157_30204 - Remote Desktop Connection](https://user-images.githubusercontent.com/111739430/186005207-18b8d16f-503e-4382-b304-9c147d3ed825.png)

![2022-08-22 21_43_18-87 98 155 157_30204 - Remote Desktop Connection](https://user-images.githubusercontent.com/111739430/186005374-8b522c33-0a4b-4a21-a213-9bedf3074238.png)

Thank you very much for your help !

**Comment by simbadMarino** [comment]
I would suggest to manage all your wallet related transactions on metamask, simply copy/paste your pk from the btfs settings menu to metamask app and move your funds using that wallet.

Use main net config as per https://doc.bt.io/v1/doc/network.html#mainnet-chainid-0xc9-decimal-199 to configure your metamask

**Comment by Shawn-Huang-Tron** [comment]
@MyNameIs2StrikesInYourHead Could you provide your transaction hash?

**Comment by MyNameIs2StrikesInYourHead** [comment]
> @MyNameIs2StrikesInYourHead Could you provide your transaction hash?

Hello,

I've just relaunched a withdrawn, here's the hash: 0x0a306ed084a07b2c1e62dd16315aee9e217794ccd8ac8b091fec03e16d5f87b1

**Comment by Shawn-Huang-Tron** [comment]
@MyNameIs2StrikesInYourHead Can you check that your network can work?You can try to ping BTTC's RPC address.

**Comment by MyNameIs2StrikesInYourHead** [comment]
@Shawn-Huang-Tron 
Hello, I tried to ping an address in China, below the result:

By the way, my post is opened in the internet, I did a telnet and it's working well. I don't know what's going on with this host...
![2022-08-27 11_10_54-87 98 155 157_30204 - Remote Desktop Connection](https://user-images.githubusercontent.com/111739430/187023674-739f136a-9252-4455-a264-9d785f840ea9.png)

I've got the adresse here:

![2022-08-27 11_10_54-87 98 155 157_30204 - Remote Desktop Connection](https://user-images.githubusercontent.com/111739430/187023729-ef0bbc60-3f9e-486b-b882-c32fe5db1afd.png)

**Comment by Shawn-Huang-Tron** [comment]
@MyNameIs2StrikesInYourHead I can see your data by the nodeId that you provide. The online proof is seems like normal.And your btt balance is not 9M anymore:https://scan.btfs.io/#/node/16Uiu2HAmRKHw3iCzdTeRbhBzfMQLDsopHBaN3M8jY8RrEJ5dLcXW

**Comment by MyNameIs2StrikesInYourHead** [comment]
@Shawn-Huang-Tron Hello, I think it's a mistake, this is not my node, what you pasted is the node I tried to ping.

Here's my node: https://scan.btfs.io/#/node/16Uiu2HAmPCJVBc92DnNVQDGtEfrdS9beGWd6Gifn2XQFfEggzc9G

And there's no Online Proof History

**Comment by Shawn-Huang-Tron** [comment]
Pls paste your config information here so that i may help to location this issue.
ps: Remember don't show your private key.

**Comment by MyNameIs2StrikesInYourHead** [comment]
@Shawn-Huang-Tron 

{
  "ChainInfo": {
    "ChainId": 199,
    "CurrentFactory": "0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7",
    "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
    "Endpoint": "https://rpc.bittorrentchain.io/"
  },
  "Identity": {
    "PeerID": "16Uiu2HAmPCJVBc92DnNVQDGtEfrdS9beGWd6Gifn2XQFfEggzc9G",
    "PrivKey": "",
    "Mnemonic": ""
  },
  "Datastore": {
    "StorageMax": "34 GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "HashOnRead": false,
    "BloomFilterSize": 0
  },
  "Addresses": {
    "Swarm": [
      "/ip4/0.0.0.0/tcp/40204",
      "/ip6/::/tcp/40204",
      "/ip4/0.0.0.0/udp/40204/quic",
      "/ip6/::/udp/40204/quic"
    ],
    "Announce": [],
    "NoAnnounce": [],
    "API": "/ip4/127.0.0.1/tcp/5001",
    "Gateway": "/ip4/127.0.0.1/tcp/8080",
    "RemoteAPI": "/ip4/127.0.0.1/tcp/5101"
  },
  "Mounts": {
    "FuseAllowOther": false,
    "BTFS": "/btfs",
    "BTNS": "/btns"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": true,
      "Interval": 10
    }
  },
  "Routing": {
    "Type": "dht"
  },
  "Ipns": {
    "RepublishPeriod": "",
    "RecordLifetime": "",
    "ResolveCacheSize": 128
  },
  "Bootstrap": [
    "/ip4/15.184.66.135/tcp/4001/p2p/16Uiu2HAmBQcXzrgo9MVD8xZwt4CrLzPRK1yKAVM7eY9GhXMJYHmC",
    "/ip4/54.255.27.251/tcp/4001/p2p/QmURPwdLYesWUDB66EGXvDvwcyV44rVRqV2iGNqKN24eVu",
    "/ip4/13.213.254.73/tcp/4001/p2p/QmX7RZXh27AX8iv2BKLGMgPBiuUpEy8p4LFXgtXAfaZDn9",
    "/ip4/3.66.57.90/tcp/4001/p2p/16Uiu2HAmFT6NXQkzDZXHxuFC4qFt6D1ALf57AkJV9U54HoafX7FX",
    "/ip4/3.69.104.217/tcp/4001/p2p/16Uiu2HAm2v2NBTLYmzVnLJoNbLCmdn29Gv8qLixHCJNeE81rUUYe",
    "/ip4/3.126.224.22/tcp/4001/p2p/16Uiu2HAmNngtNogFpcAUdc6wdSDmb8ZZQjjoDDWaatBXW1rHsYpu",
    "/ip4/35.158.193.90/tcp/4001/p2p/16Uiu2HAmLY4kyhMuoBntyXSt2YssZCHjefHEAXrYVc6acB7KEBh3",
    "/ip4/52.221.82.136/tcp/4001/p2p/QmYqCq3PasrzLr3PxtLo5D6spEAJ836W9Re9Eo4zUou45U",
    "/ip4/3.1.76.240/tcp/4001/p2p/16Uiu2HAmQfh6CYSWG1MM1DnzJ9duM8jxqn6vxNbjGBsmzc3kkctp",
    "/ip4/3.7.220.224/tcp/4001/p2p/16Uiu2HAmRVtFaXksAqb8W4Fyr8g5jkggeGDFdVcp8dQ724NMvpcR",
    "/ip4/3.109.125.91/tcp/4001/p2p/16Uiu2HAkzggX1jKwc1xen5qNPQ5RKNkXQqmH2PYAKGd8JZ15YQmK",
    "/ip4/65.1.217.86/tcp/4001/p2p/16Uiu2HAmGwDdvK4jAi1Ahga3zkiuW6HFZKKFNWtqVUFXvaSCNjdg",
    "/ip4/34.213.53.108/tcp/4001/p2p/QmWm3vBCRuZcJMUT9jDZysoYBb66aokmSReX26UaMk8qq5",
    "/ip4/15.184.174.48/tcp/4001/p2p/16Uiu2HAm6Bkxj81JQxa67aja7UWznjTgzAAVzPAqZMVD6oGpw7ST",
    "/ip4/15.184.96.102/tcp/4001/p2p/16Uiu2HAmFVWTvouWpQTRjMb4bUaidfLzsH2RVogcGHb6RwvPSxuT",
    "/ip4/35.161.203.220/tcp/4001/p2p/QmWJWGxKKaqZUW4xga2BCzT5FBtYDL8Cc5Q5jywd6xPt1g",
    "/ip4/35.84.213.199/tcp/4001/p2p/QmbVFdiNkvxtc7Nni7yBWAgtHg8MuyhaZ5mDaYR2ZrhhvN",
    "/ip4/35.84.151.38/tcp/4001/p2p/QmQVQBsM7uoJy8hATjTm51uSAkx2y3iGLhSwA6LWLa7iQJ",
    "/ip4/13.232.5.9/tcp/4001/p2p/16Uiu2HAmSkFDwHU3snrYD2ib5wWeKcsuFMZWEPt31z5YVJ8ktw1p",
    "/ip4/15.184.108.65/tcp/4001/p2p/16Uiu2HAkzRyGYEba2B3SBXdwp328LNFhRG4qhJVZrN6tsJK5KKu5"
  ],
  "Gateway": {
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "RootRedirect": "",
    "Writable": false,
    "PathPrefixes": [],
    "APICommands": [],
    "NoFetch": false,
    "NoDNSLink": false,
    "PublicGateways": null
  },
  "API": {
    "HTTPHeaders": {}
  },
  "Swarm": {
    "AddrFilters": null,
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": false,
    "EnableRelayHop": false,
    "SwarmKey": "/key/swarm/psk/1.0.0/\n/base16/\n64ef95289a6b998c776927ed6e33ca8c9202ee47df90141d09f5ffeeb64b8a66",
    "EnableAutoRelay": true,
    "Transports": {
      "Network": {},
      "Security": {},
      "Multiplexers": {}
    },
    "ConnMgr": {
      "Type": "basic",
      "LowWater": 600,
      "HighWater": 900,
      "GracePeriod": "20s"
    }
  },
  "AutoNAT": {},
  "Pubsub": {
    "Router": "",
    "DisableSigning": false
  },
  "Peering": {
    "Peers": null
  },
  "Services": {
    "StatusServerDomain": "https://status.btfs.io",
    "OnlineServerDomain": "https://online.btfs.io",
    "HubDomain": "https://hub.btfs.io",
    "EscrowDomain": "https://escrow.btfs.io",
    "GuardDomain": "https://guard.btfs.io",
    "ExchangeDomain": "https://exchange.bt.co",
    "SolidityDomain": "grpc.trongrid.io:50052",
    "FullnodeDomain": "grpc.trongrid.io:50051",
    "TrongridDomain": "https://api.trongrid.io",
    "EscrowPubKeys": [
      "CAISIQPAfB2Mt2ic+n3JcL4vrKXxBCmB0iNh+5BYiXdJNWed/Q=="
    ],
    "GuardPubKeys": [
      "CAISIQJ16EiwvGko4SaBEEUFyMdNZp1vKsTLgIXCY6fRa3/Obg=="
    ]
  },
  "Provider": {
    "Strategy": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Experimental": {
    "FilestoreEnabled": false,
    "UrlstoreEnabled": false,
    "ShardingEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": true,
    "P2pHttpProxy": false,
    "StrategicProviding": false,
    "StorageHostEnabled": true,
    "StorageClientEnabled": true,
    "Analytics": true,
    "RemoveOnUnpin": false,
    "HostsSyncEnabled": false,
    "HostsSyncFlag": true,
    "HostsSyncMode": "SCORE",
    "DisableAutoUpdate": false,
    "HostRepairEnabled": false,
    "HostChallengeEnabled": false,
    "ReportOnline": true,
    "ReportStatusContract": true
  },
  "UI": {
    "Host": {
      "Initialized": true,
      "ContractManager": {
        "LowWater": 100,
        "HighWater": 300,
        "Threshold": 10000000
      }
    },
    "Renter": {
      "Initialized": false
    },
    "Wallet": {
      "Initialized": false
    }
  },
  "Plugins": {
    "Plugins": null
  }
}

**Comment by Shawn-Huang-Tron** [comment]
Try to change your rpc address by following:

**Comment by MyNameIs2StrikesInYourHead** [comment]
Hello, I tried to change with the recommenced endpoint as specified in your doc, but I can't withdraw my funds and my node has still no online proof...  But the host seems like working really nice, weird issue.

    "Endpoint": "https://bttc.trongrid.io/"
