### ISSUE TITLE
Online Proof discourages new users

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/go-btfs#230]
The Online Proof bleeds your account unnecessarily if you get no contracts, which further discourages new users from joining. With the update to 2.2.0, my contracts have dropped from constant mid 20s to 0. I usually leave a few hundred BTT for gas. With 0 contracts and constant heartbeat checks, I'll actually be close to 0 BTT left in my wallet.

**Comment by Sophia-yu-kk** [comment]
Thank you very much for your feedback and comments. Online proof contracts exist for the whole network to be more distributed and decentralized. In this process is required to consume gas fees, the team will continue to optimize and progress, and hopefully make the BTFS network more robust.

**Comment by MilNoslen** [comment]
> Thank you very much for your feedback and comments. Online proof contracts exist for the whole network to be more distributed and decentralized. In this process is required to consume gas fees, the team will continue to optimize and progress, and hopefully make the BTFS network more robust.

I mean yes I get it promotes decentralization and authentication, but imagine the user who's new.

Either they get TRX and then have to figure it out how to swap it to BTT, or they buy BTT directly.
Then imagine they're told they have to bridge it, which costs TRX. If they didn't know what gas is, So now they have to buy TRX again.

So now they bridge it, and somehow they figure out how to setup BTFS. They have a low score, takes a while to hit 10 or "Happy Face" now in the new UI. Now their money essentially gets drained with heartbeat.
