### ISSUE TITLE
After upgrading the version 2.2.1, all my node scores become 0

### ISSUE THREAD

**Issue by holychen1234** [bittorrent/go-btfs#238]
{"host_stats":{"online":true,"storage_used":419593910,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345668096,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":1,"age_level":3,"version_level":1,"active_level":3,"level":2},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":1078563247,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345668096,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":3,"age_level":3,"version_level":3,"active_level":3,"level":3},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":642441804,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345668096,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":1,"age_level":3,"version_level":1,"active_level":3,"level":2},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":102181585,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345635328,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":3,"age_level":2,"version_level":1,"active_level":1,"level":2},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":374066112,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345635328,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":2,"age_level":3,"version_level":1,"active_level":3,"level":2},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":283642232,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345635328,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":1,"age_level":3,"version_level":3,"active_level":3,"level":2},"renter_stats":{"reserved":""}}
{"host_stats":{"online":true,"storage_used":194652725,"storage_cap":100000000000,"storage_disk_total":563934511104,"storage_disk_available":511345598464,"uptime":0,"score":0,"uptime_score":0,"age_score":0,"version_score":0,"speed_score":0,"upload_speed_score":0,"download_speed_score":0,"uptime_weight":0.6,"age_weight":0.2,"version_weight":0.1,"speed_weight":0,"upload_speed_weight":0,"download_speed_weight":0,"last_updated":"2022-09-07T01:55:43.727790825Z","active_score":0,"active_weight":0.1,"uptime_level":1,"age_level":3,"version_level":3,"active_level":3,"level":2},"renter_stats":{"reserved":""}}

**Comment by Sophia-yu-kk** [comment]
After the V2.2.1 upgrade, the score statistics have changed, and it is recommended to refer to this document.https://docs.btfs.io/docs/node-reputation
You can check the latest score of the node on the scan, thank you for your feedback.
