### ISSUE TITLE
2.2.1版本的一些节点手动上报合约正常，但是这些节点不会自动上报。

### ISSUE THREAD

**Issue by neicedai** [bittorrent/go-btfs#239]
比如这个16Uiu2HAmF1R5aT7guTinEos5WJe8cAoDpbWfsNvev6jdhhgAMQQ8
手动上报一切正常，就是不会自动上报

**Comment by laocheng-cheng** [comment]
您好，手动上报是怎么触发呢？
自动上报是指节点启动，两天后一直没有上报，对么？

**Comment by neicedai** [comment]
./btfs statuscontract report_online_server

./btfs statuscontract report_status_contract 
这两条命令手动上报的

**Comment by laocheng-cheng** [comment]
明白了，自动上报是满一天上报一次，比较缓慢，您有等多久呢？

**Comment by neicedai** [comment]
应该超过30 小时

**Comment by laocheng-cheng** [comment]
帮忙看下这个命令的返回：
./btfs statuscontract config

**Comment by neicedai** [comment]
{
	"ReportStatusSeconds": 54817,
	"LastReportTime": "2022-09-05T21:32:21.051061771+08:00"
}
16Uiu2HAmVbR93PmgenvR2PvqsisUoC7CS1MCrMAsCATs5YEb3NEj
这个节点我5号上报了一次，之后就没有上报了

**Comment by laocheng-cheng** [comment]
您好，从链上看下这个节点之前的上报都是正常的，最近一两天上报不连续。会不会是网络问题上报失败，有没有报错看到呢？
1.建议启动后，观察下错误日志；
2.再观察两天看看有没有正常上报。

另外，这个问题我也记录下来，后面再讨论分析一下，非常感谢反馈。

**Comment by neicedai** [comment]
我看过了没有上报错误的日志，应该就是没上报

**Comment by neicedai** [comment]
我再报告一个更奇怪的节点，这个节点浏览器里看不到分数，但是用命令查询有上报记录。
{
	"ReportStatusSeconds": 63054,
	"LastReportTime": "2022-09-06T19:36:16.644753072+02:00"
}

{
	"LastSignedInfo": {
		"peer": "16Uiu2HAmSD1fqpE79GE3UGwdRKYoqkb71i1K9MWr7hdHfSHm5ged",
		"created_time": 1659492736,
		"version": "2.2.1",
		"nonce": 847,
		"bttc_address": "0x8d96978a1216560701a0b1ea1191b378e2179603",
		"signed_time": 1662542192
	},
	"LastSignature": "0xf96c5953f1a0542973f0c025097dd14212ff28a6d1c33b7f1db8491adc93c6b25d6bfae2ad59a8f1a3157cbb58664208066a26670eff82231bbe92261269e82300",
	"LastTime": "2022-09-07T11:16:32.831366039+02:00"
}
节点id：16Uiu2HAmSD1fqpE79GE3UGwdRKYoqkb71i1K9MWr7hdHfSHm5ged
浏览器里没有上报记录

**Comment by neicedai** [comment]
我发现有些节点手动上报也不行，会报错
./btfs statuscontract report_status_contract
Error: context deadline exceeded
但是用命令查询签名和上报记录都是有的，这些节点只有删除了statestore这个目录后才会重新上报，但是Nonce值会重新计算

**Comment by neicedai** [comment]
> 您好，从链上看下这个节点之前的上报都是正常的，最近一两天上报不连续。会不会是网络问题上报失败，有没有报错看到呢？ 1.建议启动后，观察下错误日志； 2.再观察两天看看有没有正常上报。
> 
> 另外，这个问题我也记录下来，后面再讨论分析一下，非常感谢反馈。

我发现有些节点手动上报也不行，会报错
./btfs statuscontract report_status_contract
Error: context deadline exceeded
但是用命令查询签名和上报记录都是有的，这些节点只有删除了statestore这个目录后才会重新上报，但是Nonce值会重新计算

**Comment by KenianShi** [comment]
应该不是网络问题，我也存在这个问题。目前只有手动上报

**Comment by Sophia-yu-kk** [comment]
The problem has been recorded, and will be discussed and optimized subsequently. Please use English for subsequent issue submissions to facilitate communication in a diverse community. Thanks for your understanding and support.
