### ISSUE TITLE
fails to install - 

### ISSUE THREAD

**Issue by daddydaycare** [bittorrent/go-btfs#24]
Working on previously closed issue#11. :btfs resolve -r /btns/16Uiu2HAmU9ysnuasmdyq1rRePYTwHntmyhZdfC9wm4qCPQMAh9Qq/: could not resolve 
 Not sure how to fix that and ticket closed doesnt look like they solved that. And the proposed solution didnt work.
Ok see the issue right before me is basically having same issues.  I think I will spin up another VM in a few days and rinse repeat. Might just be too early yet.  Had just started the v1 then I read about this , so was interested.  Previous post almost Identical.

FYI Might be nice to have a script to copy to install all the dependencies on a clean install of a linux distro. and just everything in order in one place.

**Comment by daniel-tron** [comment]
User below URLs as workaround, they are identical with btns address in error.
https://dashboard-test.btfs.io
https://gateway-test.btfs.io/btfs/QmRwxtQfzpfaLKYfg3qhxsFfpRm3J3qLXJxDofsLV8ydXq

**Comment by daddydaycare** [comment]
How does going here solve the problem. It still doesn't connect?  Getting to a dashboard that says your not connected doesnt kick the can very far.

**Comment by daniel-tron** [comment]
Need update the url and click submit in setting.

**Comment by TheEagle-Crypto** [comment]
> Need update the url and click submit in setting.

I have the same issue... 
Cant access the WEB UI, get this error:
btfs resolve -r /btns/16Uiu2HAmU9ysnuasmdyq1rRePYTwHntmyhZdfC9wm4qCPQMAh9Qq/: could not resolve

as your advice, when I went to: https://dashboard-test.btfs.io
Dashborad opens, but I dint under how to update the URL? 

In the setting when I click "SUBMIT" it gives an error message:
Setting Failed, Please Check If You Are Using A Valid API URL!

**Comment by daniel-tron** [comment]
by default use http://localhost:5001 is ok, if you node is not local, try telnet ip 5001, you can't connect it if even can't telnet.
