### ISSUE TITLE
2.2.1的空投合约命中率问题

### ISSUE THREAD

**Issue by boringw** [bittorrent/go-btfs#240]
您好，升级2.2.1之后，我9.6w在线超级节点，一天只收到一百多个空投合约，全网才140w超级节点在线，怎么会这么少
2.2.1的空投合约选择节点是怎么样的逻辑呢？

**Comment by Sophia-yu-kk** [comment]
The BTFS community communicates in English, please use English when submitting issues, thank you very much for your understanding and support.
