### ISSUE TITLE
Uptime Score

### ISSUE THREAD

**Issue by TheBestBadGamer** [bittorrent/go-btfs#241]
My uptime score is 0% even though I even gave BTTC and the gas fees are deducted.
Could support see why that is?

My ID: 16Uiu2HAkvKbyTzHWK2Tkpxbghtkuk1yW7iHTMbkwLABJKJia7Xjk

**Comment by Sophia-yu-kk** [comment]
https://scan.btfs.io/#/node/16Uiu2HAkvKbyTzHWK2Tkpxbghtkuk1yW7iHTMbkwLABJKJia7Xjk

These are the parameters displayed by the node in the scan for your reference.

The online time you mentioned is 0, I guess it is seen on the dashboard, this piece will cause misunderstanding, it is already a known problem, and will be optimized later. Thank you for your feedback.
