### ISSUE TITLE
BTFS runs then immediately shuts down

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#244]
I downloaded both the 64 and 32 bit Windows pre-built versions and they both open a Terminal window, show the text as described on here, then the window does not stay open - the application exits and I cannot go to the Dashboard.

**Comment by Cr-opas** [comment]
you need run `btfs.exe -init` for cmd and send screenshot here.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190508300-f340265f-c0bc-45bf-9521-420151c4cea3.png)

**Comment by oldcityws** [comment]
I figured out that I would have to run it from the terminal and not just double-click the file to run the file.

That admonition needs to appear in the instructions for download and install / use of the prebuilt binaries, otherwise a key is generated and who knows what passcode it had generated? _/(o.O)\_

**Comment by Cr-opas** [comment]
ok, now run `btfs daemon --chain-id 199` and send screenshots here

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190509734-5214d55f-3bba-409c-8a45-ce87ae03e674.png)

**Comment by Cr-opas** [comment]
> 

you can see it in config file is here C:\USERS\RMi\.btfs\

**Comment by Cr-opas** [comment]
try check and kill all process btfs.exe, or port 8080 busy other appl.

**Comment by oldcityws** [comment]
I had bittorrent client running with BTFS enabled.  Killed it.  I will try that command again.

**Comment by oldcityws** [comment]
How do I find out what is hogging 8080?

**Comment by oldcityws** [comment]
I've got Resource Monitor up and it appears nothing was on 8080.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190512286-941ada83-2511-4e81-9c05-e022f6b21e67.png)

Still getting this error -____-

**Comment by oldcityws** [comment]
I went into my Windows Defender firewall and cleared all three copies of BTFS for unrestricted communications.  Then I realized I had THREE copies of this executable.  So I deleted all but the one that is located in the bittorrent program folder.  I repeated the step to run the application from Terminal and still get this same error.

**Comment by Cr-opas** [comment]
use `netstat` command, will try change gateway port in config file btfs

**Comment by Cr-opas** [comment]
also try to run the application in the console running as administrator

**Comment by oldcityws** [comment]
Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    127.0.0.1:1027         kubernetes:1028        ESTABLISHED
  TCP    127.0.0.1:1028         kubernetes:1027        ESTABLISHED
  TCP    127.0.0.1:5354         kubernetes:8203        ESTABLISHED
  TCP    127.0.0.1:5354         kubernetes:8204        ESTABLISHED
  TCP    127.0.0.1:7250         kubernetes:7249        TIME_WAIT
  TCP    127.0.0.1:7255         kubernetes:7254        TIME_WAIT
  TCP    127.0.0.1:7260         kubernetes:7259        TIME_WAIT
  TCP    127.0.0.1:7265         kubernetes:7264        TIME_WAIT
  TCP    127.0.0.1:7270         kubernetes:7269        TIME_WAIT
  TCP    127.0.0.1:7279         kubernetes:7278        TIME_WAIT
  TCP    127.0.0.1:7286         kubernetes:7285        TIME_WAIT
  TCP    127.0.0.1:7292         kubernetes:7291        TIME_WAIT
  TCP    127.0.0.1:7301         kubernetes:7300        TIME_WAIT
  TCP    127.0.0.1:7306         kubernetes:7305        TIME_WAIT
  TCP    127.0.0.1:7516         kubernetes:7515        TIME_WAIT
  TCP    127.0.0.1:7741         kubernetes:7742        ESTABLISHED
  TCP    127.0.0.1:7742         kubernetes:7741        ESTABLISHED
  TCP    127.0.0.1:7743         kubernetes:7744        ESTABLISHED
  TCP    127.0.0.1:7744         kubernetes:7743        ESTABLISHED
  TCP    127.0.0.1:8203         kubernetes:5354        ESTABLISHED
  TCP    127.0.0.1:8204         kubernetes:5354        ESTABLISHED
  TCP    127.0.0.1:8237         kubernetes:8238        ESTABLISHED
  TCP    127.0.0.1:8238         kubernetes:8237        ESTABLISHED
  TCP    127.0.0.1:8239         kubernetes:8240        ESTABLISHED
  TCP    127.0.0.1:8240         kubernetes:8239        ESTABLISHED
  TCP    127.0.0.1:8241         kubernetes:8242        ESTABLISHED
  TCP    127.0.0.1:8242         kubernetes:8241        ESTABLISHED
  TCP    127.0.0.1:8243         kubernetes:8244        ESTABLISHED
  TCP    127.0.0.1:8244         kubernetes:8243        ESTABLISHED
  TCP    127.0.0.1:8245         kubernetes:8246        ESTABLISHED
  TCP    127.0.0.1:8246         kubernetes:8245        ESTABLISHED
  TCP    127.0.0.1:8247         kubernetes:8248        ESTABLISHED
  TCP    127.0.0.1:8248         kubernetes:8247        ESTABLISHED
  TCP    192.168.1.105:2729     unknown2e59e72b24bc:53320  ESTABLISHED
  TCP    192.168.1.105:2791     68.183.104.109:https   ESTABLISHED
  TCP    192.168.1.105:3402     104.16.214.191:https   ESTABLISHED
  TCP    192.168.1.105:5346     198.199.67.29:https    ESTABLISHED
  TCP    192.168.1.105:6014     lb-140-82-114-25-iad:https  ESTABLISHED
  TCP    192.168.1.105:6084     104.16.213.191:https   ESTABLISHED
  TCP    192.168.1.105:7145     52.46.157.7:https      ESTABLISHED
  TCP    192.168.1.105:7238     unknownaccb51fd0fca:http  ESTABLISHED
  TCP    192.168.1.105:7296     lb-140-82-112-3-iad:https  ESTABLISHED
  TCP    192.168.1.105:7993     52.226.139.121:https   ESTABLISHED
  TCP    192.168.1.105:8064     17.179.252.2:https     CLOSE_WAIT
  TCP    192.168.1.105:8188     17.57.144.149:5223     ESTABLISHED
  TCP    192.168.1.105:8842     104.45.188.91:https    CLOSE_WAIT
  TCP    192.168.1.105:8843     72.21.91.29:http       CLOSE_WAIT
  TCP    192.168.1.105:9119     a96-7-218-42:https     CLOSE_WAIT
  TCP    192.168.1.105:9121     server-13-32-230-17:https  CLOSE_WAIT
  TCP    192.168.1.105:9457     149.154.175.51:https   ESTABLISHED
  TCP    192.168.1.105:10769    216.239.36.145:https   ESTABLISHED
  TCP    192.168.1.105:11143    ec2-23-20-169-126:https  ESTABLISHED
  TCP    192.168.1.105:12292    unknownaccb51fd0fca:7681  ESTABLISHED
  TCP    192.168.1.105:13070    a1370dc23e25e46ce:https  ESTABLISHED
  TCP    192.168.1.105:14491    216.239.36.145:https   ESTABLISHED
  TCP    192.168.1.105:14619    ec2-54-84-219-106:https  ESTABLISHED
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:2227  [2620:149:a41:51b::e]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8053  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8055  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8057  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8058  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8059  g2600-1402-d800-068d-0000-0000-0000-02a1:https  ESTABLISHED
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8060  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8061  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8062  [2620:149:a41:40a::a]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8165  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8172  [2620:149:a41:409::11]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8175  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8185  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8190  [2620:149:a41:409::11]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8193  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8194  [2620:149:a41:409::11]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8195  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8196  [2620:149:a41:409::11]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8197  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8227  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8228  [2620:149:a41:40f::9]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8229  g2600-1402-d800-068a-0000-0000-0000-02a1:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8230  [2620:149:a41:409::11]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8232  [2620:149:a41:40f::12]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8298  rr-in-f188:5228        ESTABLISHED
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8299  rr-in-f188:5228        ESTABLISHED
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:8844  [2606:4700::6812:19f3]:http  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:10885  [2620:149:a41:518::8]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:11644  [2620:149:a41:40b::6]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:50a5:e496:ffc5:cba4]:11645  [2620:149:a41:40b::6]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:6562  [2620:149:a41:409::f]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:6624  [2620:149:a41:409::10]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7020  dfw28s29-in-x13:https  ESTABLISHED
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7217  yt-in-f17:https        TIME_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7276  pnatla-ac-in-x0a:https  ESTABLISHED
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7284  ym-in-f94:https        ESTABLISHED
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7310  [2620:149:a41:408::f]:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:7311  yt-in-f17:https        ESTABLISHED
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:9125  g2600-1402-9800-001b-0000-0000-6878-8113:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:9126  g2600-1402-9800-001b-0000-0000-6878-8113:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:9128  g2600-1402-9800-0593-0000-0000-0000-1011:https  CLOSE_WAIT
  TCP    [2600:1700:4241:b670:d1a0:fbe4:45be:ffb0]:9129  g2600-1402-9800-058b-0000-0000-0000-1011:https  CLOSE_WAIT

**Comment by oldcityws** [comment]
> also try to run the application in the console running as administrator

I did but it popped up a second window to run the program and BAM, gone.

**Comment by oldcityws** [comment]
I navigated to CMD directly, ran as admin, cd'd to the folder, and ran it and it ran significantly slower... and gave me the same error.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190517667-e5482eba-4e83-486a-9607-e40a3e354fdb.png)

**Comment by Cr-opas** [comment]
you use antivirus or firewall?

**Comment by Cr-opas** [comment]
A socket error can be caused by the antivirus or firewall software. Basically, a needed socket connection is being denied. Socket error is a message which implies that a port is blocked and/or unreachable

**Comment by oldcityws** [comment]
Windows Defender - I specifically exempted the program from restrictions.

**Comment by Cr-opas** [comment]
Port 8080 is an alternate HTTP port.  Many programs can use it, and if the computer is connected to a domain, this port can be blocked by group policies.  This port is also often used by proxy servers.  The problem is that this port is closed, busy or prohibited for you.

**Comment by oldcityws** [comment]
I turned off Firewall and still get that error.  Hrm.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190530214-72e40fa8-ef55-415e-af3b-8de15cc468a1.png)
I cancelled a pending java update install notice and closed a few of the things I found running and now it is different -  [see screen grab].

**Comment by oldcityws** [comment]
so I went to the dashboard and... not connected.
![image](https://user-images.githubusercontent.com/42473932/190530875-b9739dee-2548-4765-a787-a174b6d34671.png)

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/btfs20-dashboard#settings

**Comment by simbadMarino** [comment]
> so I went to the dashboard and... not connected.
> ![image](https://user-images.githubusercontent.com/42473932/190530875-b9739dee-2548-4765-a787-a174b6d34671.png)

IF still failing go to settings and just click on Submit button, then go back to your dashboard, all should be good now ;)

**Comment by oldcityws** [comment]
> > so I went to the dashboard and... not connected.
> > ![image](https://user-images.githubusercontent.com/42473932/190530875-b9739dee-2548-4765-a787-a174b6d34671.png)
> 
> IF still failing go to settings and just click on Submit button, then go back to your dashboard, all should be good now ;)

Thank you for providing this solution!  I ended up posting a whole issue about the failure in the dashboard section of this board and someone gave me those same instructions earlier today, and it worked.
