### ISSUE TITLE
Host score not updating

### ISSUE THREAD

**Issue by Rchua72** [bittorrent/go-btfs#246]
I am running 2.2.1 and the btfs process has been running for 5 days now but the host score is still not updated.  Please see screenshot.  The btfs process has been running since September 14.
![BTFSHostScoreIssue](https://user-images.githubusercontent.com/6827300/190935119-0ae8325a-c7a8-4f98-81b7-3f8c6a7a4c93.jpg)

**Comment by Sophia-yu-kk** [comment]
This is the document on fractions, please refer to, 
https://docs.btfs.io/docs/node-reputation
