### ISSUE TITLE
ERROR   report-status-contract

### ISSUE THREAD

**Issue by chrisbg69** [bittorrent/go-btfs#247]
Hello, my system is Ubuntu server 22.04 TLC, i have a 10 nodes there, updated to the last version - 2.2.1 - BTTC. For 2 weeks I have neither contracts nor drops, from time to time the following errors appear, what can I do?

![error-status](https://user-images.githubusercontent.com/40600216/192091975-b5e54295-d0fc-44df-9943-d17712192a0d.png)

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/mainnet-rpc-configure
If you encounter a screenshot error, we suggest you refer to this document.
