### ISSUE TITLE
Sudden failure to start

### ISSUE THREAD

**Issue by wbkys** [bittorrent/go-btfs#250]
Initializing daemon...
go-btfs version: 2.2.1-5dbd537
Repo version: 10
System version: amd64/linux
Golang version: go1.15.15
Repo location: /btt
Peer identity: address 
the address of Bttc format is:  address 
the address of Tron format is:  address 
Guide: http://127.0.0.1:5001/hostui

Error: Could not connect to blockchain rpc, please check your network connection.Post "https://rpc.bittorrentchain.io/": read tcp 116.255.162.xxx:42134->52.7.235.42:443: read: connection reset by peer

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/mainnet-rpc-configure
refer this link please

**Comment by wbkys** [comment]
Thank you Only https://bttc.trongrid.io/ available
