### ISSUE TITLE
High gas fee for online proof contract

### ISSUE THREAD

**Issue by rgouzal** [bittorrent/go-btfs#251]
I was before used to host my storage for long time but I was not getting any earnings or rewards and I lost a lot of BTT tokens so I decided to stop running the node cause of electricity I am paying in addition to keep the node running. So I decided to stop for now until this is solved.

Is there any solution for this or it is done by design to take 40 BTT daily even if storage not being used?

**Comment by Sophia-yu-kk** [comment]
Hello, thank you very much for your support of the BTFS project.

Online proof contracts are contracts that interact with the chain and interact with the chain and need to consume gas fees, this is an unchangeable fact in a decentralized network.

For online proof contracts, you can refer to this document.
https://docs.btfs.io/docs/btfs20-architecture#online-proof-contract
