### ISSUE TITLE
[BUG]Error: Could not connect to blockchain rpc

### ISSUE THREAD

**Issue by wbkys** [bittorrent/go-btfs#252]
Error: Could not connect to blockchain rpc, please check your network connection.Post "https://44.194.131.138:443/": net/http: TLS handshake timeout

all RPC

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/mainnet-rpc-configure refer this link please

**Comment by wbkys** [comment]
It doesn't work
