### ISSUE TITLE
Contracts Activity & Queue Status [Feature]

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#254]
It is unclear HOW people are able to get contracts - is there some kind of queue?
I suggest, for transparency a Contracts Activity Monitor so we can see that there are indeed contracts on the system.

**Describe the solution you'd like**
In the contracts menu, we should be able to see active contract by ID.
If we are in a queue for receiving / being assigned a contract, then we should see our position in line.

**Describe alternatives you've considered**
The only alternative is checking our earnings, and at the current rate, it is disheartening.

**Additional context**
Seeing activity on the system will encourage people to keep their nodes up / monitored.

There are online file share systems available for attorneys and others needing to transfer gig-plus size files.  Perhaps integrating a USD payment system whereby a portion of the actual payout is converted to BTT for hosts... can be used to introduce mainstream netizens to the value of this network.  If they see payment options in USD and BTT they will realize that the digital currency is available for payments, and seek to buy / use it.  Also, the speed of the network available should play into who gets what contracts.  So faster network users should get contracts first, I hope.

**Comment by Sophia-yu-kk** [comment]
Thank you for your feedback, will discuss your comments and suggestions.
