### ISSUE TITLE
Two contract per month

### ISSUE THREAD

**Issue by Cr-opas** [bittorrent/go-btfs#264]
What is the algorithm for obtaining new contracts for a node? For two months, the node has consistently received 24 contracts per month (about 1.04 gigabytes of space per month is occupied). This month, the node received only two contracts (167 megabytes), the node works around the clock with a maximum rating. Perhaps I need to configure something so that my node receives contracts again?
Operating system Winserver 2008 R2
BTFS file version 2.2.1.1-0a04db0
Repo ver. 10
Sys ver. amd64/windows
golang ver. 1.15.15
Host ID 16Uiu2HAm8oWtSajohMY8DueyjQwr9gcSdgrmYoyLJHU9PUbGYsaw
![btfs node](https://user-images.githubusercontent.com/112861208/202153464-833f47f1-957e-4a08-b8d7-1d79c2ccf77f.png)

**Comment by oldcityws** [comment]
I am wondering the same - I've had my own node running since September and have gotten zero contracts.

Join the Discord channel and suggest what I did... we need transparency regarding how contracts are allocated - I wish we could see the queue system and where we are at regarding chances of getting a contract.

**Comment by chrisbg69** [comment]
Neither contracts nor drops, it's been a month and a half, Linux server 22.04.1 LTS, 25 nodes, updated to the latest version - 2.2.1.1 - BTTC.

**Comment by Sophia-yu-kk** [comment]
Nodes with 8 or more points have a chance to get a contract, but individual nodes' earnings are not fixed and there is no promise related to individual nodes' earnings.

We will discuss the suggestions carefully. Thank you for your feedback.
