### ISSUE TITLE
BTFS node complains about insufficient BTT, but wallet has funds.

### ISSUE THREAD

**Issue by kingsumos** [bittorrent/go-btfs#266]
BTT node shows the messsage:
cannot continue until there is sufficient (100 Suggested) BTT (for Gas) available on 0x6e70992137cc8acd335d04c5309eea26aab7a583

Tried following the doc: https://docs.btfs.io/v1.0/docs/deposit-btt-to-btfs to get the "BTT Crypto Wallet Address" which is  TL3ADcnn9j8LPvAaZK459pxdrN5hYS31MC
(tranfered funds to this address, both TRX and BTTC... BTW after sending 10 TRX only 1 TRX left in the wallet, looks 9 TRX vanished to cover "fees" which is kinda funny)

Anyway, I have tried "btfs wallet deposit <amount>" with no luck, some RPC error shows after few minutes
The "btfs wallet balance" shows:
{"BtfsWalletBalance":102000000,"BttWalletBalance":0}

But "btfs wallet transactions" shows status "pending"
[{"id":"7091551","time_create":"2022-11-24T19:19:27.367824794Z","amount":100000000,"from":"BTT Wallet","to":"BTFS Wallet","status":"Pending"},{"id":"7091533","time_create":"2022-11-24T14:00:58.254453029Z","amount":1000000,"from":"BTT Wallet","to":"BTFS Wallet","status":"Pending"},{"id":"7091531","time_create":"2022-11-24T13:46:24.873910248Z","amount":1000000,"from":"BTT Wallet","to":"BTFS Wallet","status":"Pending"}]

Any hint?

I have opened this wallet using the TronLink Pro wallet and it seems healthy...

**Comment by kingsumos** [comment]
One of the transcations I have tried using the deposit command:
https://tronscan.org/#/transaction/de124931fb0123339e7ec2d31c8edeaa3b5be0658e423d2193933e7bacd063cb?lang=en

**Comment by Sophia-yu-kk** [comment]
Please note that activation of the account address is using BTT tokens on the BTTC chain.
