### ISSUE TITLE
[Docker image missing shared library]

### ISSUE THREAD

**Issue by solipsist01** [bittorrent/go-btfs#285]
**Describe the bug**
when i build the dockerfile from master

when i run the image:
Changing user to btfs
btfs: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory

also image ghcr.io/bittorrent/go-btfs:btfs-v2.3.0
has this problem

**Comment by daniel-tron** [comment]
Updated image ghcr.io/bittorrent/go-btfs:btfs-v2.3.0 with below code change.
https://github.com/bittorrent/go-btfs/commit/46b46ba57db139cc524c520244bfaa4f9a224f1c

**Comment by solipsist01** [comment]
i rebuilt the image, it works brilliantly.
also, i noticed that 2.3.0 has a much lower cpu usage footprint. Nice !
