### ISSUE TITLE
BTFS v.2.3.0 does not run on Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-197-generic x86_64)

### ISSUE THREAD

**Issue by Andrju81** [bittorrent/go-btfs#286]
After updating BTFS to version v.2.3.0, it does not start on Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-197-generic x86_64) with errors:
![Clip2Net Menu_2022-12-13_20_19_51](https://user-images.githubusercontent.com/40444286/207404836-bff0cbae-1344-4b79-8a6d-8bbbf6bf48ef.png)

**Comment by imstevez** [comment]
The binary build from a linux platform whitch version is higher than yours, so you can try build from the source by yourself.
The go 1.18 is needed.

**Comment by Yrp** [comment]
Please pull the executable again
https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.3.0

**Comment by simbadMarino** [comment]
@imstevez @Yrp , would you please point to the exact golfing release we need to use to build from source? Is it the one pointed in the attached picture?  
<img width="1003" alt="Screen Shot 2022-12-19 at 9 03 19" src="https://user-images.githubusercontent.com/11146636/208455870-2be1b164-3fbd-4399-8dc7-588c455050d0.png">
