### ISSUE TITLE
BTFS 2.3.0 does not run on Windows 64bit [BUG]

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#287]
I renamed the new file btfs.exe as was done in the past, copied it into the btfs folder, and now it does not run at all.  It immediately starts, shows some HTML code, then immediately quits.

**Comment by oldcityws** [comment]
init settlement err:  init vault service: vault init: 503 Service Temporarily Unavailable: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
                font-size: 0.9em;
                font-family: sans-serif,helvetica;
                margin: 0;
                padding: 0;
            }
            :link {
                color: #c00;
            }
            :visited {
                color: #c00;
            }
            a:hover {
                color: #f50;
            }
            h1 {
                text-align: center;
                margin: 0;
                padding: 0.6em 2em 0.4em;
                background-color: #294172;
                color: #fff;
                font-weight: normal;
                font-size: 1.75em;
                border-bottom: 2px solid #000;
            }
            h1 strong {
                font-weight: bold;
                font-size: 1.5em;
            }
            h2 {
                text-align: center;
                background-color: #3C6EB4;
                font-size: 1.1em;
                font-weight: bold;
                color: #fff;
                margin: 0;
                padding: 0.5em;
                border-bottom: 2px solid #294172;
            }
            h3 {
                text-align: center;
                background-color: #ff0000;
                padding: 0.5em;
                color: #fff;
            }
            hr {
                display: none;
            }
            .content {
                padding: 1em 5em;
            }
            .alert {
                border: 2px solid #000;
            }

            img {
                border: 2px solid #fff;
                padding: 2px;
                margin: 2px;
            }
            a:hover img {
                border: 2px solid #294172;
            }
            .logos {
                margin: 1em;
                text-align: center;
            }
            /*]]>*/
        </style>
    </head>

    <body>
        <h1><strong>nginx error!</strong></h1>

        <div class="content">

            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>

            <div class="alert">
                <h2>Website Administrator</h2>
                <div class="content">
                    <p>Something has triggered an error on your
                    website.  This is the default error page for
                    <strong>nginx</strong> that is distributed with
                    Fedora.  It is located
                    <tt>/usr/share/nginx/html/50x.html</tt></p>

                    <p>You should customize this error page for your own
                    site or edit the <tt>error_page</tt> directive in
                    the <strong>nginx</strong> configuration file
                    <tt>/etc/nginx/nginx.conf</tt>.</p>

                </div>
            </div>

            <div class="logos">
                <a href="http://nginx.net/"><img
                    src="/nginx-logo.png"
                    alt="[ Powered by nginx ]"
                    width="121" height="32" /></a>

                <a href="http://fedoraproject.org/"><img
                    src="/poweredby.png"
                    alt="[ Powered by Fedora ]"
                    width="88" height="31" /></a>
            </div>
        </div>
    </body>
</html>


Error: init vault service: vault init: 503 Service Temporarily Unavailable: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is temporarily unavailable</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
                font-size: 0.9em;
                font-family: sans-serif,helvetica;
                margin: 0;
                padding: 0;
            }
            :link {
                color: #c00;
            }
            :visited {
                color: #c00;
            }
            a:hover {
                color: #f50;
            }
            h1 {
                text-align: center;
                margin: 0;
                padding: 0.6em 2em 0.4em;
                background-color: #294172;
                color: #fff;
                font-weight: normal;
                font-size: 1.75em;
                border-bottom: 2px solid #000;
            }
            h1 strong {
                font-weight: bold;
                font-size: 1.5em;
            }
            h2 {
                text-align: center;
                background-color: #3C6EB4;
                font-size: 1.1em;
                font-weight: bold;
                color: #fff;
                margin: 0;
                padding: 0.5em;
                border-bottom: 2px solid #294172;
            }
            h3 {
                text-align: center;
                background-color: #ff0000;
                padding: 0.5em;
                color: #fff;
            }
            hr {
                display: none;
            }
            .content {
                padding: 1em 5em;
            }
            .alert {
                border: 2px solid #000;
            }

            img {
                border: 2px solid #fff;
                padding: 2px;
                margin: 2px;
            }
            a:hover img {
                border: 2px solid #294172;
            }
            .logos {
                margin: 1em;
                text-align: center;
            }
            /*]]>*/
        </style>
    </head>

    <body>
        <h1><strong>nginx error!</strong></h1>

        <div class="content">

            <h3>The page you are looking for is temporarily unavailable.  Please try again later.</h3>

            <div class="alert">
                <h2>Website Administrator</h2>
                <div class="content">
                    <p>Something has triggered an error on your
                    website.  This is the default error page for
                    <strong>nginx</strong> that is distributed with
                    Fedora.  It is located
                    <tt>/usr/share/nginx/html/50x.html</tt></p>

                    <p>You should customize this error page for your own
                    site or edit the <tt>error_page</tt> directive in
                    the <strong>nginx</strong> configuration file
                    <tt>/etc/nginx/nginx.conf</tt>.</p>

                </div>
            </div>

            <div class="logos">
                <a href="http://nginx.net/"><img
                    src="/nginx-logo.png"
                    alt="[ Powered by nginx ]"
                    width="121" height="32" /></a>

                <a href="http://fedoraproject.org/"><img
                    src="/poweredby.png"
                    alt="[ Powered by Fedora ]"
                    width="88" height="31" /></a>
            </div>
        </div>
    </body>
</html>

**Comment by oldcityws** [comment]
I left the name as-is on the download and got the above stuff after the boot sequence items showing account data.

**Comment by oldcityws** [comment]
I reverted back to "btfs 2.2.0 and get a PriceOracleAddress is None in config file" error
Same error for 2.2.1
Then after I load 2.3.0, I get a whole bunch of HTML code after an init settlement error: init vault service: vault init: 503 Service Temorarily Unavailable
Trying 2.2.1.1 gives me the "btfs 2.2.0 and get a PriceOracleAddress is None in config file" error
btfs.exe will no longer work, it quits as soon as it executes even when daemonized.
Using the longer name of btfs-windows-amd64.exe works.
But then it does kick out errors.

**Comment by laocheng-cheng** [comment]
HI, If can't upgrade to 2.3.0, you can roll back the old version.
if notice err:"PriceOracleAddress is None in config file", it need to add the PriceOracleAddress parameter to the config configuration.

"ChainInfo": {
...
"PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
...
}

**Comment by oldcityws** [comment]
Where exactly is that config file?

**Comment by imstevez** [comment]
<BTFS_PATH>/config

**Comment by imstevez** [comment]
init settlement err: init vault service: vault init: 503 Service Temporarily Unavailable

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207504537-28dea3e5-2154-40fe-8f6b-40181f2f5e77.png)
I edited the config file by simply renaming it config.yaml and added in the text as shown in the pic.

**Comment by oldcityws** [comment]
Here is the names of the files: see pic 
![image](https://user-images.githubusercontent.com/42473932/207504693-aa846b22-1031-4f76-b259-fe1a06cd8d85.png)

**Comment by imstevez** [comment]
Or you can retry again the v2.3.0
This error is a network error.
"init settlement err: init vault service: vault init: 503 Service Temporarily Unavailable"

**Comment by laocheng-cheng** [comment]
sorrry, if you roll back the old version, set the whole ChainInfo:

  "ChainInfo": {
    "ChainId": 199,
    "CurrentFactory": "0x763d7858287B9a33F4bE5bb3df0241dACc59BCc7",
    "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
    "Endpoint": "https://rpc.bittorrentchain.io/"
  },

**Comment by imstevez** [comment]
![image](https://user-images.githubusercontent.com/31301354/207505294-1c1e9e87-482a-4ceb-9eeb-790b94aa6c4a.png)

**Comment by oldcityws** [comment]
What should the config file have for the new version?  Because I tried that and it failed both ways: with the original config file with original text and names, with the files renamed btfs.exe and config.yaml.

**Comment by imstevez** [comment]
The Old version have this line:
"PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
And the new version does not

the conifig file name must be "config", not "config.yaml"

**Comment by imstevez** [comment]
If you want roll back the v2.1.1，you need add this line
```"PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",```
 after the line
 ```"ChainInfo": {```

**Comment by oldcityws** [comment]
I'm trying to get 2.3.0 to work.

**Comment by oldcityws** [comment]
@imstevez you left your pneumonic phrase in the pic.  You need to delete that pic.

**Comment by oldcityws** [comment]
I've given up on 2.3.0

I checked the 2.2.1 config file and it has the following:

version: 2.2.1
md5: 171727a321556977f7e77a68e4597a80
autoupdateFlg: true
sleepTimeSeconds: 86400
beginNumber: 0
endNumber: 100

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207511692-db712e38-4ba4-4a65-a35e-625def393ff2.png)
... is what the files now look like.
![image](https://user-images.githubusercontent.com/42473932/207511789-e1274d1c-f2e8-4bee-a688-2221ea863c59.png)
... is what the config file now looks like.

And it does not work.  I think I screwed something up.

**Comment by imstevez** [comment]
Just use the original config.

**Comment by oldcityws** [comment]
I tried, and now it's all broken.  It starts and is gone even when I try to daemonize it,

**Comment by oldcityws** [comment]
Maybe I have to restart my whole computer?

**Comment by imstevez** [comment]
Delete these lines and try again.
![image](https://user-images.githubusercontent.com/31301354/207523415-e1bf2641-a1fe-427d-aa15-8b20a85e8b4c.png)

**Comment by imstevez** [comment]
recover this file, and rename it to config.yaml

**Comment by oldcityws** [comment]
file recovered, as original, and properly named.
exe is named btfs.exe as was before.

Something's still not working, it starts and is gone too fast for me to capture anything.

**Comment by oldcityws** [comment]
It gets to the hostui line and exits right at that point.

**Comment by imstevez** [comment]
Run CMD and execute
``` echo %BTFS_PATH%```
and check the output.

**Comment by oldcityws** [comment]
It supplies the following: %BTFS_PATH%

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207524997-fdeb1dfd-0820-48ba-bd2f-12b48073fb82.png)

**Comment by imstevez** [comment]
recover the btfs.exe to the original version

**Comment by oldcityws** [comment]
Okay, I wonder how long that will take?  I restarted and it looks like nothing has YET upgraded.

**Comment by oldcityws** [comment]
I do notice that if I create a CMD file and then a shortcut to that set in Advanced on Properties to run as Administator, I finally see the PriceOracleAddress error.

![image](https://user-images.githubusercontent.com/42473932/207531519-70d2c86e-0a3f-4316-b073-ec802733b35e.png)

**Comment by imstevez** [comment]
Because your BTFS is integrated in the Bittorrent client, so the upgrade to new version should be done by the bittorrent client.

**Comment by imstevez** [comment]
This error means the client is version 2.2.1 and you can enter the folder: c:\Administrator\.btfs, and there is a config file named 'config'

**Comment by oldcityws** [comment]
Huh.  Okay.  When I run the bittorrent client, I cannot connect to hostui, but if I run daemonized BTFS from CMD, I *can* access hostui web URL.

**Comment by imstevez** [comment]
Backup this folder c:\Users\RMi\.btfs

**Comment by oldcityws** [comment]
Definitely will do.

**Comment by imstevez** [comment]
add this line
```"PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",```
after the line
```"ChainInfo": {```

**Comment by oldcityws** [comment]
Aha, okay, that makes a lot of sense now.

**Comment by imstevez** [comment]
Restart bittorrent client

**Comment by oldcityws** [comment]
And restarted

**Comment by imstevez** [comment]
Check the hostui

**Comment by imstevez** [comment]
If it does not works, show me the config file screenshot(only a few lines changed above)

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207534954-2ee6a7f3-1fb4-4dbe-bd7a-889441653390.png)

**Comment by imstevez** [comment]
The config file now is ok

**Comment by imstevez** [comment]
![image](https://user-images.githubusercontent.com/31301354/207535522-e03239f9-8284-4855-90da-5c6eb6f2ff42.png)

click here

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207535824-c71cb294-ab94-46b4-b57b-2643cd20a0e8.png)

**Comment by imstevez** [comment]
Wait a minute, and refresh the page

**Comment by oldcityws** [comment]
That item does not exist.
However, C:/Users/RMi/AppData/Roaming/bittorrent/btfs/config.yaml does exist.

**Comment by imstevez** [comment]
Wait some minutes, it seems the bittorrent is upgrading the btfs.

**Comment by oldcityws** [comment]
ok

**Comment by oldcityws** [comment]
And it's dead,  Dashboard refreshed and blank page.  Not sure how long it takes to update.  I do know that I've had to run BTFS via CMD in order to keep it up and running, and that's how I had been running it.

**Comment by imstevez** [comment]
You can Run BTFS via CMD
```btfs id```

**Comment by imstevez** [comment]
Show me the files in this folder:
```C:/Users/RMi/AppData/Roaming/bittorrent/btfs/```

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207541493-96380331-7cc9-4675-bf30-705e33edde82.png)

**Comment by imstevez** [comment]
And show the content of config.yaml

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207541729-e0a13368-3162-4931-8a1e-44b8e8b80fae.png)

**Comment by imstevez** [comment]
It has been upgrade to 2.2.1.1
And restart the bittorrent client, it will upgrade to 2.3.0

**Comment by imstevez** [comment]
You can try run ```btfs daemon``` via CMD

**Comment by oldcityws** [comment]
It looks like it works beautifully when run from CMD, just the version gets a hit to the score so far.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/207543596-77faf363-b1ab-421b-b854-fdab3c5f72f9.png)
![image](https://user-images.githubusercontent.com/42473932/207543729-68c4b018-a69c-48a4-a030-55e7c3e878e3.png)

**Comment by imstevez** [comment]
Yes, it's ok with v2.2.1.1

**Comment by oldcityws** [comment]
I'm surprised BTFS itself did not come with an internal update function, or some kind of updater app that does the work of the update.  Would be a lot more user-friendly that way.  I'm sure more people would run dedicated nodes on their boxes if there was an updater separate from bittorrent client.  Because BTFS has never run for me when I've had the client up.  It's only through CMD that I've been able to keep BTFS up for long periods of time.

**Comment by imstevez** [comment]
Yes, I think so too, and the official may provide Windows users with upgraders or upgrade scripts in the future.

**Comment by oldcityws** [comment]
That would be the best way to go, considering the file path that I was completely unaware of until you helped me, thank you so much!

**Comment by oldcityws** [comment]
Offering a dedicated hosting / mining node is how a lot of coins work - consumer platform or wallet [bittorrent as an example], and then full node only [btfs only running, as an example here].
