### ISSUE TITLE
Install instructions / upgrade instructions needed[Feature]

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#288]
I tried to upgrade from 2.1.1 to 3.0 and did what I did last time - dropped the exe into the btfs folder and now it's broken.

We need platform-specific explainers on how to upgrade and/or install successfully.

I've tried both the original name and the simple btfs.exe name and neither works.

**Comment by laocheng-cheng** [comment]
HI, If can't upgrade to 2.3.0, you can roll back,  need to add the PriceOracleAddress parameter to the config configuration.

"ChainInfo": {
  ...
  "PriceOracleAddress": "0x0064d80C42b6E2cE3aC92eaD445B3D83C510c7AA",
  ...
 }

**Comment by imstevez** [comment]
You can try btfs2.3.0 again as the following steps: 
1. download the latest btfs-windows-amd64.exe to any location
2. stop the running BTFS process
3. start cmd, switch to the new version btfs-windows-amd64.exe location
4. run btfs-windows-amd64.exe daemon

**Comment by oldcityws** [comment]
I double-clicked the executable after stopping the running BTFS process, exactly as you suggested, and it opened and then disappeared.  Then when I executed it in CMD with daemon command, I get the following error:

init settlement err:  init swap service error , CheckNewPrice 503 Service Temporarily Unavailable

**Comment by oldcityws** [comment]
I saw a blurb in the release notes that the vault contract should be updated for the new version.  Maybe that has something to do with this not working?  I'm just tossing spaghetti at a wall here, trying to think through what could cause this error.

**Comment by imstevez** [comment]
You are right, this error is caused by a network error calling the BTTC RPC interface. And I think you can replace the RPC endpoint from ```https://rpc.bittorrentchain.io/``` to ```https://rpc.bt.io/```， then try again.
__Note:__
Edit the BTFS config file: ``````

**Comment by oldcityws** [comment]
IT WORKS!  
![image](https://user-images.githubusercontent.com/42473932/207777654-5fdbe179-5728-4324-a74f-042dd1b1ee43.png)
