### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Cr-opas** [bittorrent/go-btfs#289]
**Describe the bug**
Error when trying to send proof online
**To reproduce**
1. Run the BTFS node executable file, wait for an attempt to send a transaction online proof
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/112861208/207530952-d70280cf-55ae-4aa6-8377-6ee72a57743d.png)
**Desktop (please complete the following information):**
  - OS: Windows 2008R2
  - Version: 2.3.0

**Comment by chrisbg69** [comment]
![Screenshot 2022-12-14 100744](https://user-images.githubusercontent.com/40600216/207541116-b074b870-e39e-4105-9645-6f6a22c75118.png)

Same here.

**Comment by Sophia-yu-kk** [comment]
This error report can be ignored.
