### ISSUE TITLE
升级到 2.3.0版本，onlineProof 并没有自动执行

### ISSUE THREAD

**Issue by KenianShi** [bittorrent/go-btfs#292]
升级到 2.3.0版本，onlineProof 并没有自动执行

**Comment by Sophia-yu-kk** [comment]
Hello, first of all, thank you very much for your message. However, the BTFS community is international and requires you to leave your message in English, thank you for your support and understanding.

**Comment by KenianShi** [comment]
Since it is international, it naturally needs to support Chinese
