### ISSUE TITLE
Host score dropped after updating to 2.3.0v

### ISSUE THREAD

**Issue by AlexGGWP** [bittorrent/go-btfs#294]
Hello my node score dropped to 0 after updating to version 2.3.0 and node stopped sending online prove. 

After the update the node has been running for 7 days non stop. But the score never changes: 

![Screenshot 2023-01-07 203358](https://user-images.githubusercontent.com/19946697/211165546-6012cf3a-b0e0-42cd-a71f-5077c78481e2.png)

It appears that is updating regularly as shown on the screenshot above but still the score is not affected. 

![Screenshot 2023-01-07 202014](https://user-images.githubusercontent.com/19946697/211165026-65e30e16-60b7-4a1e-80f3-d8f597310a94.png)

As you can see in the screenshot above no errors are reported in the terminal. I dug around the dashboard to see if the node was sending online prove but it appears it is not for some reason. What could be the issue here?

![Screenshot 2023-01-07 201803](https://user-images.githubusercontent.com/19946697/211164948-dbb66fbd-e8d5-4ec0-81ed-b2d96dc11480.png)

Node ID: 16Uiu2HAm8NLU7qghHf3YiswtE8S5p6Jnuc1FwE5yuYB62xwYRdhy
OS: Windows 10

**Comment by Richard2GitHub** [comment]
Hi, have you tried to visit the dashboard in the private window of your browser? The cache of the browser may cause it. You can check as follow steps:
1. create a new private window in your browser.
2. visit 'http://your-ip-and-port/dashboard' page(you may need to restart your daemon).
3. if you still can not see the score info, try to see what the response of the API:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/122080967/211236712-4d355510-46f3-4943-94d0-109ffd4da25e.png">

**Comment by AlexGGWP** [comment]
Hi @Richard2GitHub I did what you suggested and indeed it worked. I guess the browser had some cache stuck.

![Screenshot 2023-01-07 201803](https://user-images.githubusercontent.com/19946697/211289480-6fe21aae-7515-430d-a7bb-78c737f9901a.png)

Now I can see the score, however it appears the node is not sending online proof. It says that the node had sent only one.

![Screenshot 2023-01-09 123831](https://user-images.githubusercontent.com/19946697/211289602-361f7a86-1ab5-4a10-b910-fd7e95d59dbe.png)

**Comment by FRiceSchoolAcct** [comment]
> Hi @Richard2GitHub I did what you suggested and indeed it worked. I guess the browser had some cache stuck.
> 
> ![Screenshot 2023-01-07 201803](https://user-images.githubusercontent.com/19946697/211289480-6fe21aae-7515-430d-a7bb-78c737f9901a.png)
> 
> Now I can see the score, however it appears the node is not sending online proof. It says that the node had sent only one.
> 
> ![Screenshot 2023-01-09 123831](https://user-images.githubusercontent.com/19946697/211289602-361f7a86-1ab5-4a10-b910-fd7e95d59dbe.png)

The  'ONLINE PROOF DATA' add 1 per day. In fact, it adds 1 per 24 hours. Tomorrow, it will be 2.

**Comment by Richard2GitHub** [comment]
@AlexGGWP  The ‘last updated’ time update per 2 hours for all users will not be affected by your node’s online proof. The online proof displayed in the screenshots on the dashboard is related to your node’s online status.

**Comment by AlexGGWP** [comment]
It appears that the issue has been resolved. Now I see that there are more proofs which is great. Thanks for the assistance guys!
