### ISSUE TITLE
security vulnerability

### ISSUE THREAD

**Issue by itsunixiknowthis** [bittorrent/go-btfs#295]
Hello,

Where is the correct place to report security vulnerabilities?

**Comment by penn202000** [comment]
Hi, I think the answer would be 'btfs-developer@bittorrent.com'; it's listed on page 'https://docs.btfs.io/docs/faq-1'.

**Comment by itsunixiknowthis** [comment]
Good idea.

go-btfs devs, can you confirm that you received an email from itsunixiknowthis@zohomail.com to btfs-developer@bittorrent.com

**Comment by Richard2GitHub** [comment]
Got it, I'll forward this msg to the devs. They'll contact you via email.

**Comment by Richard2GitHub** [comment]
Hi, @itsunixiknowthis,  It's a known issue; the devs will answer you via email. So, I'll close this GitHub issue now.
