### ISSUE TITLE
[BUG] Error in command line

### ISSUE THREAD

**Issue by Cr-opas** [bittorrent/go-btfs#296]
I see this error to command line? 
```
2023-01-28T05:31:55.220+0300    <[31mERROR<[0m  core/commands   commands/wallet.
go:248  wallet get balance failed, ERR: Failed to get ledger balance, reason: Es
crowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc erro
r: code = Unknown desc =
every day, SendOnlineDaily, time:2023-01-28 18:01:39.5297134 +0300 +03 m=+107101
7.940142701
```
What its mean?

**Comment by Richard2GitHub** [comment]
Hi, @Cr-opas. Are you using API to withdraw from the ledger? If not, you can ignore this msg. Some change in the ledger causes it.

**Comment by Cr-opas** [comment]
Okay, thanks. I am not use ledger and i not trued make withdrawal in this time, maybe someone was try crack me, idk.

**Comment by Richard2GitHub** [comment]
OK, then you can ignore the error msg. I'll close this GitHub issue.

**Comment by serveriukai** [comment]
The same error using linux cli, with installed version 2.3.1:
$ btfs wallet balance
Error: Failed to get ledger balance, reason: EscrowClient: rpc error: code = Unknown desc = ledger error:LedgerClient: rpc error: code = InvalidArgument desc =

**Comment by Richard2GitHub** [comment]
Thank you for your feedback, it is a deprecated function and you can ignore it. AFAIK it will be fixed in the next version.
