### ISSUE TITLE
Discord invite error and not able to join

### ISSUE THREAD

**Issue by RowdyMuncher** [bittorrent/go-btfs#297]
Hello Sophia, I have been a node tester and user virtually since it started with access to BTFS on Discord yet now for the past year I am unable to join. I followed the link provided above and I a always denied. Screenshot provided bellow. I really would like to be given access again or what ever is wrong be fixed as i have spent years of time and money and continue to do so. Please can you get this fixed.
![CleanShot 2023-02-04 at 13 29 48](https://user-images.githubusercontent.com/44824397/216748729-afeba944-6a3d-4269-b785-46a4b25b683a.png)

**Comment by Richard2GitHub** [comment]
Hi, @RowdyMuncher Please try this invite: https://discord.gg/VmMjp2gvAB. 
There are many reasons to cause this 'Unable to accept invite'; you can view them from google. I tried the above link with a new discord account and successfully joined the server.
