### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by theguy39** [bittorrent/go-btfs#301]
**Describe the bug**
Memory leak

**To Reproduce**
the memory just keeps growing now matter what it goes up and up if you have 4GB or 32GB 
even on new miner seems like a leak to me, nothing else open 6 computers, all different generations and Windows 7/10 
Just leave the miner on for 1 day half ram is used up 2 day if you make it 99.9% is and the crash from memory, 32GB take longer but Ive tried everything to limit this.

**Expected behavior**
Not exceed an expected range of RAM or have a setting to auto restart if it does exceed X RAM

**Screenshots**
not really applicable dont think, got 6 miners all doo it old to new PC's 

**Desktop (please complete the following information):**
 - OS: Windows 7/ Windows 10
 - Version 2.3.0

**Additional context**
I think this one is obvious im not on here much maybe there is a fix but havent found it

**Comment by Shawn-Huang-Tron** [comment]
Could you see how many peers you are going to connect in your dashboard? Click peers then you will see it in your dashboard when your memory is higher more than 4G.
We have found some memory leak and will fix it. But we need to confirm that you are the same issue.

**Comment by theguy39** [comment]
Ok that might be an issue lol the old pcs im using are 3-4 GB RAM MAX,  since the requirements said 2GB thought it would stop there

**Comment by theguy39** [comment]
I did notice the new rig now seems to stop at 3.4 which would explain it and ill let you know just reset them all so cant tell you peers when  there high right now, but will do. Should be posted by tomorrow when there high up again

**Comment by oldcityws** [comment]
I think my own computer (Windows) is having the same issue, and I think I set it so that excess memory usage would result in HDD space functioning as memory in lieu of RAM - this is called the pagefile function.  I was left with 500MB available after running BTFS long enough.  Fun times, fun times... @Shawn-Huang-Tron THANK YOU for digging into this issue!

**Comment by Shawn-Huang-Tron** [comment]
Next release we will fix some memory issues. But maybe we need to focus on the windows to see if the same issues it is. So if possiible, paste your connected peers when ram is in high level. @oldcityws

**Comment by Richard2GitHub** [comment]
Since the next release will fix some memory issues, I'm going to close this issue for now, but please feel free to reopen it if you have any further concerns or questions.

**Comment by theguy39** [comment]
Sounds good to me do you know when the next issue update is coming up

**Comment by theguy39** [comment]
As advised for now I will wait for the next revision as I'm told it should be along shortly. Please let me know if there is any reason a certain setting should be lower default when running 15-25 year old Dual / Quad Core 2 duos and AMD CPU's with much lower 
L1,l2,l3 cache and many other things like this that could be a factor Don't know if this one even is but just an example! Thanks
