### ISSUE TITLE
Contract assignment status number - transparency is needed!

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/go-btfs#302]
**Is your feature request related to a problem? Please describe.**
The problem is that people are running nodes for months and it seems that only people already with contracts are getting new contracts while newer node owners are running for months seeing activity on their nodes but no contracts.  Can we have some kind of ranking where we can see how close we are to getting a contract?  Our score does not show how many contracts have been assigned in what timeframe, nor does it tell us anything about how strong the possibility of getting an assignment / contract is.

**Describe the solution you'd like**
I would like to see nodes assigned a queue number and/or some kind of explanation as to HOW nodes are assigned contracts.  It is extremely frustrating running a node and seeing my network usage go to 10MBS and no contract listed.

**Describe alternatives you've considered**
No alternative exists that I can see.

**Additional context**
Node owners who are running these nodes on their machines need to see some kind of mechanism or transparency or they will burn out in frustration and take BTFS off of their systems.  It would be neat to see some kind of ranking preference put towards people who have never HAD a storage contract as priority over those who have repeated storage contracts.  Without transparency, and contracts, newer node owners have zero incentive to stay in the game, so to speak.  Transparency is what gives legitimacy to any system.

**Comment by Richard2GitHub** [comment]
Hi, @oldcityws

**Comment by Richard2GitHub** [comment]
Hi, oldcityws; thank you very much for supporting the BTFS project.
As long as the node exceeds 8 points, it has a chance to gain revenue. Because of the large base of Hosts that meet the conditions, the probability of a Host getting a contract is uncertain. Later on, as the BTFS community expands and uses increase, etc., the number of contracts will increase accordingly.
