### ISSUE TITLE
[Feature] Cash all cheques command.

### ISSUE THREAD

**Issue by Rockster34** [bittorrent/go-btfs#308]
Since BTFS web UI is having some issues with showing uncashed cheques and having to cash cheques via the command line is absolutely horrid hence having a feature like cashing all uncashed cheques would be really nice to have also for people that don't have access to the webUI.

**Comment by brianbc2021** [comment]
Hello, @Rockster34; I think this is what you want:  https://github.com/bittorrent/go-btfs/blob/master/scripts/batch_cash.sh.

**Comment by Rockster34** [comment]
> Hello, @Rockster34; I think this is what you want: https://github.com/bittorrent/go-btfs/blob/master/scripts/batch_cash.sh.

This is about withdrawing from the vault from what I seen I am more aiming at a simple command for the command line more intergrated for other people that don't wanna run a bash next to the already running BTFS terminal.
