### ISSUE TITLE
2023-04-09T07:29:06.321+0200    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

### ISSUE THREAD

**Issue by Raimis999** [bittorrent/go-btfs#309]
2023-04-09T07:29:06.321+0200    ←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

What is this? in version 2.3.0 never haed this issue

**Comment by Richard2GitHub** [comment]
Hi, @Raimis999   Sorry for the late response, Could you tell me your environment and the reproduction steps?
Environment info:
1. OS and its version(such as 'Ubuntu 20.04 x64')
2. go-btfs 2.3.1 (source code or binary file)
3. Does this node have public IP? Or is it sharing one public IP with some other nodes?

**Comment by Raimis999** [comment]
> Hi, @Raimis999 Sorry for the late response, Could you tell me your environment and the reproduction steps? Environment info:
> 
>     1. OS and its version(such as 'Ubuntu 20.04 x64')
> 
>     2. go-btfs 2.3.1 (source code or binary file)
> 
>     3. Does this node have public IP? Or is it sharing one public IP with some other nodes?

1.Windows 10 64bit (build 19044)
2. btfs 2.3.1 binary
3. Yes has

With 2.3.0 didnt had any errors, with all other versions also.

**Comment by Richard2GitHub** [comment]
Thank you for bringing this issue to our attention. Based on our investigation, we have identified that the issue you are experiencing is related to upstream issues. We are closely monitoring those issues and will update our code as soon as those issues are resolved. In the meantime, you may want to follow the upstream issue tracker to stay updated on the progress:
https://github.com/libp2p/go-libp2p-kad-dht/issues/837
https://github.com/libp2p/go-libp2p/issues/2253

Please let us know if you have any further questions or concerns.
