### ISSUE TITLE
[WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.

### ISSUE THREAD

**Issue by Ramneek619** [bittorrent/go-btfs#310]
This error keeps reappearing on the cmd prompt in windows
![btfs-bug](https://user-images.githubusercontent.com/79496657/231328598-e0ee777c-8bc3-4a6e-9098-1f5b282d0815.png)

**Comment by Richard2GitHub** [comment]
Hi, @Ramneek619  please check this: https://github.com/bittorrent/go-btfs/issues/307

**Comment by ergoz** [comment]
Sorry, my fault, i didnt set BTFS_PATH.

**Comment by ValeZAA** [comment]
Do you use Vmware? That app makes its own interfaces lower metric than Erhernet or wifi and thus breaks multicast.
