### ISSUE TITLE
can I use btfs share file via myself vps

### ISSUE THREAD

**Issue by wacdev** [bittorrent/go-btfs#313]
ask a question, I want to use a torrent server to share files.

I have a vps server, but no BTT coins.

Can I directly run `btfs bittorrent serve -f 'xxx.mp4,xxx.jpeg'` to share files on the bittorrent network?

Do I still need to configure the port to open tcp or udp?

**Comment by brianbc2021** [comment]
I don't think so.  Your node is not online if you don't install your node first, so other nodes can not find it, much less to find the files you share.

**Comment by CrCati** [comment]
Hi, @wacdev  you can check this: https://docs.btfs.io/docs/install-run-btfs20-node

**Comment by simbadMarino** [comment]
it is possible to store files on you own node, however you still need BTT tokens in your BTFS wallet.
