### ISSUE TITLE
[Feature]Error: Could not connect to blockchain rpc, please check your network connection.Post "https://bttc.trongrid.io/": dial tcp: lookup bttc.trongrid.io on [::1]:53: read udp [::1]:49734->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by TonyReggae** [bittorrent/go-btfs#315]
Error: Could not connect to blockchain rpc, please check your network connection.Post "https://bttc.trongrid.io/": dial tcp: lookup bttc.trongrid.io on [::1]:53: read udp [::1]:49734->[::1]:53: read: connection refused
——————————————————————————————————————————————
Why?

**Comment by TonyReggae** [comment]
go-btfs version: 2.3.1-c0fbaee

**Comment by CrCati** [comment]
This may help you:   https://docs.btfs.io/docs/mainnet-rpc-configure
