### ISSUE TITLE
[BUG] [WARN] mdns: Failed to set multicast interface: setsockopt: An invalid argument was supplied.

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/go-btfs#316]
![Screenshot_423](https://github.com/bittorrent/go-btfs/assets/35152528/023c7795-ef75-4fb8-bc77-b25b4f3ad813)

**Comment by CrCati** [comment]
You can edit the item in this file ./btfs/config :
<img width="276" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/9f90d15f-56ed-4d7e-bc60-3ecc2faaab6f">

**Comment by MilNoslen** [comment]
I'm sorry, did you read what I said in this post and my old post from April?

"I see a config file with no extension in the folder, and I can open it in notepad to edit it. I changed it to false, but I'm still getting the WARN mdns."

**Comment by MilNoslen** [comment]
![Screenshot_424](https://github.com/bittorrent/go-btfs/assets/35152528/53c2eb4a-b0cd-47cf-bc71-95d94f2721a2)

**Comment by CrCati** [comment]
Hi, @MilNoslen It's a warning-level message related to node discovery within the local network. You can ignore it. If you don't want to see the WARN log, try the 'btfs log level all error' command. This command will set the log level to error; it will suppress warn level log.
