### ISSUE TITLE
[BUG] No Peers in BTFS Dashboard

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/go-btfs#317]
Describe the bug
No Peers in BTFS Dashboard, I've had another issue that wasn't resolved. Almost 2 months now I have no new contracts which is unusual. I've had constant 5-10 contracts a month. Ever since the new update, nothing.

To Reproduce
Starting BTFS.exe, checking the #/admin/peers

Expected behavior
Show connected peers

Screenshots
![Screenshot_422](https://github.com/bittorrent/go-btfs/assets/35152528/82c401e8-870a-4f21-b1de-b7cab4496973)

Desktop (please complete the following information):

OS: Edition Windows 10 Home
Version 22H2
Installed on ‎5/‎28/‎2021
OS build 19045.2728
Experience Windows Feature Experience Pack 120.2212.4190.0

Version go-btfs version: 2.3.1-c0fbaee

Additional context
First time happening for me. Upgraded from 2.3.0 to current

**Comment by CrCati** [comment]
Hi, @MilNoslen how about the other submenu? Depending on your network condition, the peer's page takes longer than others to display the content. For me, it takes 10s-1min sometimes.

<img width="1634" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/f8ce589d-aecc-496c-9cc3-af03777a2d8a">

**Comment by MilNoslen** [comment]
Other submenus are fine, I left tab open and it populated the peers.
