### ISSUE TITLE
Error: failed to unmarshal json. invalid character '*' looking for beginning of value

### ISSUE THREAD

**Issue by TheEagle-Crypto** [bittorrent/go-btfs#33]
hello, 

As per the guide here: https://github.com/bittorrent/btfs-dashboard
I tried running the command in window PowerShell:
`btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'`

I get error message: 
Error: failed to unmarshal json. invalid character '*' looking for beginning of value

Same issue with the another command:
`btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT","GET","POST"]'`

Error Message:
Error: failed to unmarshal json. invalid character 'P' looking for beginning of value

**Comment by daniel-tron** [comment]
PowerShell escape character is different.
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"*\"]'
btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"PUT\", \"GET\", \"POST\"]'

**Comment by TheEagle-Crypto** [comment]
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'

This is same as before, its giving same error.

**Comment by daniel-tron** [comment]
`PowerShell escape character is different.
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"*\"]'
btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"PUT\", \"GET\", \"POST\"]'`
![image](https://user-images.githubusercontent.com/3644140/148554900-b8375d6d-2b06-4190-afb6-ca030a6ef12c.png)

**Comment by daniel-tron** [comment]
sorry, updated my above comment, GitHub changed the display without code block escape.
