### ISSUE TITLE
[BUG]BTFS 2.3.2 CPU utilization issues since update

### ISSUE THREAD

**Issue by DongRyeok** [bittorrent/go-btfs#333]
Hello

Since I updated BTFS to 2.3.2, I have the following issues.

1. The following error message is continuously displayed

"2023-06-28T14:49:34.912+0900 [31mERROR[0m dht go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode"

2. When you run the BTFS client, the BTFS client continues to maintain CPU utilization at 100%

The BTFS running OS is Windows 10 x64 19045.3086.

**Comment by CrCati** [comment]
Hi, @DongRyeok, thanks for your feedback. The 'ignoring incoming dht message while not in server mode' is a known issue; we've recorded it.
As to the CPU utilization, is it a spike value or a crest value? What's the connection value of this node? Several Windows users have provided feedback that the CPU utilization would be around 50%.

**Comment by DongRyeok** [comment]
It's the crest value.

When I check CPU usage on task manager, it goes up and down by 10% to 75%.

However, the task manager, which used to have a few percent CPU utilization for the BTFS process, always shows 100 percent CPU utilization. (It's the same that they said they're using 10% and they're using 20%.)

This causes the system to become very slow and cannot do anything else.

When you exit the BTFS process, CPU utilization is reduced to 20%-30%. (The CPU utilization in the idle state of my system is usually 20% to 30%.)

The number of node connections is maintained between 8000 and 9000.

**Comment by CrCati** [comment]
Hi, @DongRyeok; The CPU consumption of the nodes is related to the number of connections. Currently, due to the upgrade, the connections of your node might be higher than 8000. However, with the upgrade of other nodes in the BTFS network, the connections of your node will decrease, which will also release some CPU resources.

Regarding the 'uncached' WBTT, could you please provide your HOST ID and BTTC Vault Contract Address here? If you are concerned about address leakage, you can verify your transactions at bttcscan.com, just like this example: https://bttcscan.com/token/0x23181f21dea5936e24163ffaba4ea3b316b57f3c?a=0x338a5d83fbba29bf4497963ee85730e5ab249465
<img width="1403" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/02752780-1afb-4725-829f-f5769f3be8fb">
<img width="1367" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/2a288258-e6e8-448a-93a3-0e638ef1828a">

**Comment by DongRyeok** [comment]
transactions link : https://bttcscan.com/token/0x23181f21dea5936e24163ffaba4ea3b316b57f3c?a=0x1a1e78B60e59BFAb65FeF2E8e47B838c21A37adC

![1](https://github.com/bittorrent/go-btfs/assets/137982069/702bbdf0-0c96-4570-93a0-1e630f894a04)
![2](https://github.com/bittorrent/go-btfs/assets/137982069/4dae2409-de11-4465-9300-d1aed0fbedd3)

**Comment by CrCati** [comment]
Hi, @DongRyeok; thanks for your feedback; I've forwarded your feedback to the community developer. Right now, do you happen to have a new cheque to cash? If you get a new cheque, try to cash out the two cheques, and the result should be successful.

**Comment by DongRyeok** [comment]
Okay. I'll try to exchange it when I get a new cash

**Comment by CrCati** [comment]
Hi, @DongRyeok; could you share the complete 'Cashing List,' 'Cashing History,' and 'Cheque Detail' info with me? And what's your vault address?
<img width="1461" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/6a1e5715-24fb-4cde-8a90-de23cfb057b0">

**Comment by DongRyeok** [comment]
My Host ID : 16Uiu2HAmQCv4TA2t9vqGUWmQe921g2nL3CvBehu935WwZEDoj6rb

My Vault adress : 0x1a1e78B60e59BFAb65FeF2E8e47B838c21A37adC

![CList](https://github.com/bittorrent/go-btfs/assets/137982069/56b21d19-0054-48fd-bba1-b8b97d23c91c)
![c4](https://github.com/bittorrent/go-btfs/assets/137982069/07aa4513-d322-4495-ae88-60fa16684a26)
![c1](https://github.com/bittorrent/go-btfs/assets/137982069/26fe9255-f57d-430b-84a4-6b2011eb68f4)
![c2](https://github.com/bittorrent/go-btfs/assets/137982069/6794e9cf-c12d-47c2-b337-2b51a633260b)
![c3](ht
![d1](https://github.com/bittorrent/go-btfs/assets/137982069/acd96117-87d4-4ec4-a6ba-0fc385a9d6fd)
![d2](https://github.com/bittorrent/go-btfs/assets/137982069/f034f80d-8cdf-4e23-ac34-bc6ae8c75080)
![d3](https://github.com/bittorrent/go-btfs/assets/137982069/20558952-8d7a-4405-9f0a-2f893bcd49c3)
![d4](https://github.com/bittorrent/go-btfs/assets/137982069/0e850c72-c95a-49e6-8eed-164d8a8dbd8b)
![d5](https://github.com/bittorrent/go-btfs/assets/137982069/c0e123eb-c292-44be-9d2a-c694d9340359)
![d6](https://github.com/bittorrent/go-btfs/assets/137982069/0abc19fb-deca-43a8-b53f-20e4fc615d69)
![d7](https://github.com/bittorrent/go-btfs/assets/137982069/967dce20-ad1b-45c0-a381-2fc78a1ee8f2)
![d8](https://github.com/bittorrent/go-btfs/assets/137982069/eccba1ca-1b8b-43f8-991e-bae59f5d8119)
![d9](https://github.com/bittorrent/go-btfs/assets/137982069/c0bf099a-3551-49e1-83bb-f8f5e260995d)
![d10](https://github.com/bittorrent/go-btfs/assets/137982069/22c354d6-56a6-4d07-8a45-a2c4965cb860)
tps://github.com/bittorrent/go-btfs/assets/137982069/edfd5c52-2d59-4ad9-bcfb-6cfd4e7440f6)

**Comment by CrCati** [comment]
Hi, @DongRyeok; thank you for your feedback; based on our investigation, that's display issue may happen on some nodes. I've forwarded this issue to the community developers; they'll fix it in the next version.

**Comment by DongRyeok** [comment]
Thank you for your answer.

Should I wait until the next version of the patch without having to do anything else?

**Comment by CrCati** [comment]
Hi, @DongRyeok; you don't have to do anything; ignore this display issue.

**Comment by CrCati** [comment]
I'll close this GitHub issue now; if you have more information to share, please feel free to reopen it.
