### ISSUE TITLE
Sorry for my late answer.

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#336]
Sorry for my late answer.
I was on Business Trip.
So i tested your commands today and i got this messages.
Whats the issue?
![Screenshot_20230630_121059_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/562c6710-c487-4010-9438-7195525223e0)

Thanks a lot for your help.
Regards,
Chris

_Originally posted by @chris110110 in https://github.com/bittorrent/go-btfs/issues/323#issuecomment-1614446398_

**Comment by CrCati** [comment]
Hi, @chris110110; that's ok. The command execution failed. Please try `btfs pin rm bafkqc.....` and `btfs block rm bafkqc...`

**Comment by chris110110** [comment]
Ok i did.
I get an error.

![Screenshot_20230630_141051_RVNC Viewer.jpg](https://github.com/bittorrent/go-btfs/assets/59182112/db5e29d6-3dc4-4c17-9dc2-588285eae763)

**Comment by CrCati** [comment]
Hi, @chris110110; sorry for the delayed response. I've reached out to the community developer, and it appears that 'bafkqc4as...' is an invalid cid with an incorrect format. v2.3.1 and v2.3.2 nodes will not generate cids in this format. To address this issue, could you please consider migrating this node or reinstalling this node in another directory? If there are any BTT or WBTT tokens associated with your address, please make sure to transfer them to another address before proceeding with the migration or reinstallation.

**Comment by CrCati** [comment]
I'll close this GitHub issue now; if you have more information to share, please feel free to reopen it.
