### ISSUE TITLE
Little wrong version number on btfs dashboard 2.3.2

### ISSUE THREAD

**Issue by dipol0** [bittorrent/go-btfs#337]
OS - Ubuntu 22.04 x64
BTFS 2.3.2 for 64 bit linux - https://github.com/bittorrent/go-btfs/releases/download/btfs-v2.3.2/btfs-linux-amd64
UI show wrong version in blue label, but left panel show correct version (and btfs scan too)

![Выделение_630](https://github.com/bittorrent/go-btfs/assets/32021806/ec2d6b85-2a78-495c-911f-a3d3097d595c)

**Comment by CrCati** [comment]
Hi, @dipol0; thank you for your feedback. You're right, and that's a known issue; the community developer has already fixed it and merged the code. Currently, the version info on dashboard.btfs.io has been corrected.
<img width="1035" alt="image" src="https://github.com/bittorrent/go-btfs/assets/122080967/7009a20e-01db-4a4f-aae4-978f1d2e44a2">

**Comment by dipol0** [comment]
And now 2.3.3 vs 2.3.4 on dash ERROR:

![Выделение_285](https://github.com/bittorrent/go-btfs/assets/32021806/7819a548-ccce-4963-a420-5e8d21bd9a4d)
