### ISSUE TITLE
Node becomes stuck/stale?

### ISSUE THREAD

**Issue by digbicks** [bittorrent/go-btfs#338]
Hi I am experiencing some weird behavior on one of my nodes. 

The node id is: 16Uiu2HAm8NLU7qghHf3YiswtE8S5p6Jnuc1FwE5yuYB62xwYRdhy

The issue is that the node in question became (or _is_ not really sure) somewhat stale (for lack of better words). By "stale" I mean there are no changes to the node: besides it's score (of course based on the time the node is online etc.). No new contracts for months, no error is shown, no air drops, no gas fee has been taken but the node is still running and sends prove which is kind of weird since it is supposed to take gas fee.  It looks to me as if the node is stuck in a state where it does basically nothing. 

First I thought it needed to get to a high score to get contracts and earn air drops. No such a thing even with 100% score on the dash board for months. I have inserted a certain amount of BTT so the node could run but there are no changes to that amount, meaning no gas fees are payed? Which really confuses me and gets me to think that the node is stuck. On another node all the gas fees are taken accordingly and I can see the amount being reduced from my total as expected.

I tried restarting - no luck. 

Am I missing something or is the node actually stuck/stale?

**Comment by CrCati** [comment]
Hi, @digbicks， this node 16Uiu2HAm8NLU7qghHf3YiswtE8S5p6Jnuc1FwE5yuYB62xwYRdhy is v2.3.1 node, and from the ['Online Proof Details' info](https://scan.btfs.io/#/node/16Uiu2HAm8NLU7qghHf3YiswtE8S5p6Jnuc1FwE5yuYB62xwYRdhy), this node is running normally. I suggest that you upgrade the node to v2.3.2. Airdrops to nodes are random, and nodes' earnings are related to their geographical location and influenced by storage supply and demand.

**Comment by digbicks** [comment]
Hi @CrCati thank you for your answer. Now that you mentioned the version I see the following:
on the console:
![Screenshot 2023-07-04 162412](https://github.com/bittorrent/go-btfs/assets/6688467/f300eb62-32c0-4c9c-9efc-94e4e84c29f6)
on the dashboard:
![Screenshot 2023-07-04 162501](https://github.com/bittorrent/go-btfs/assets/6688467/a9f630ea-fb4b-4826-89a4-7d06a41bcd0c)
and again in the console:
![Screenshot 2023-07-04 162534](https://github.com/bittorrent/go-btfs/assets/6688467/22ade8ef-81d8-4d90-81cc-ce9c3ffa509d)

which is again weird. And as far as the OnlineProof goes why I do not see any gas fees being payed? Do I need to do something to make the node be more "noticeable" for more contracts?

**Comment by FRiceSchoolAcct** [comment]
Hi, @digbicks; thank you for your feedback; you're right; that's [ an issue](https://github.com/bittorrent/go-btfs/issues/337 ). And the community developers have already fixed it. Regarding the gas fee, currently, there is no gas fee for reporting heartbeats to online proof for nodes. So, you do not see any gas fees being paid on your node is normal.

**Comment by CrCati** [comment]
Hi, [@digbicks](https://github.com/digbicks); thank you for your feedback; you're right; that's [an issue](https://github.com/bittorrent/go-btfs/issues/337). And the community developers have already fixed it. Regarding the gas fee, currently, there is no gas fee for reporting heartbeats to online proof for nodes. So, you do not see any gas fees being paid on your node is normal.
