### ISSUE TITLE
[BUG] caught panic: runtime error: slice bounds out of range [:19] with capacity 1

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/go-btfs#340]
**Describe the bug**
caught panic: runtime error: slice bounds out of range [:19] with capacity 1
goroutine 2503483111 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.SelectWithSimopenOrFail.func1()
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/client.go:103 +0x58
panic({0x26c3f20, 0xc017c6a4f8})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc0b72b09c0, {0xc05920ab90, 0x10?, 0x1})
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc04ebcd770)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x385c7e0, 0xc04ebcd770})
        pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x21b2748ca18?, 0xc0b72b09c0})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x21b2748ca18?, 0xc0b72b09c0?})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.SelectWithSimopenOrFail({0xc000cbfae0?, 0x2, 0x2}, {0x21b2748c9e8?, 0xc0b72b09c0})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/client.go:128 +0x1e5
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:327 +0x167
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112

**To Reproduce**
Start BTFS.exe
Allow it to run its course
Receive error a day or two later

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Edition	Windows 10 Home
Version	22H2
Installed on	‎5/‎28/‎2021
OS build	19045.3155
Experience	Windows Feature Experience Pack 1000.19041.1000.0

go-btfs version: 2.3.2-58978cb

**Additional context**

**Comment by CrCati** [comment]
Hi, @MilNoslen; thank you for your feedback. Is this error reoccurring every time after you start your node and keep running for 1 or 2 days? And what's the go version of your node?

**Comment by MilNoslen** [comment]
> go-btfs version: 2.3.2-58978cb
Repo version: 10
System version: amd64/windows
Golang version: go1.18

Since this current uptime, every two days. I had one heartbeat inbetween.

**Comment by MilNoslen** [comment]
> Hi, @MilNoslen; thank you for your feedback. Is this error reoccurring every time after you start your node and keep running for 1 or 2 days? And what's the go version of your node?

caught panic: runtime error: slice bounds out of range [:24] with capacity 1
goroutine 2138731373 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate.func1()
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:202 +0x58
panic({0x26c3f20, 0xc02ac74930})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc0a3f8fa80, {0xc0481703ac, 0x1?, 0x1})
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc04ba55b90)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x385c7e0, 0xc04ba55b90})
        pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x21b2748ca18?, 0xc0a3f8fa80})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x21b2748ca18?, 0xc0a3f8fa80?})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0xc019b3df68?, {0x21b2748c9e8?, 0xc0a3f8fa80})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:213 +0x146
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:322 +0x97
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112
        
        
The previous "caught panic" after my 2023-7-17 heartbeat

**Comment by CrCati** [comment]
Got it. I'll forward these messages to the community developers.

**Comment by MilNoslen** [comment]
Today

caught panic: runtime error: slice bounds out of range [:24] with capacity 1
goroutine 141891281 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate.func1()
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:202 +0x58
panic({0x21f3f20, 0xc04307dc38})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc08f872980, {0xc07bec4ed1, 0x1?, 0x1})
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc03700c820)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x338c7e0, 0xc03700c820})
        pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x2222d2e0798?, 0xc08f872980})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x2222d2e0798?, 0xc08f872980?})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0xc081b92a01?, {0x2222d2e0768?, 0xc08f872980})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:213 +0x146
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:322 +0x97
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112

**Comment by simbadMarino** [comment]
hey @MilNoslen , is this causing a complete crash on btfs? or it continues execution? I'm trying to correlate it with my issue https://github.com/bittorrent/go-btfs/issues/346

**Comment by yu-btc** [comment]
1

**Comment by yu-btc** [comment]
Hello, this error/tip will not affect the contract acquisition at all, so please don't worry about it. Regarding the optimisation and friendliness of the prompt's text, it will be continuously optimised and improved through the BTFS technical community. Thank you very much for your question and suggestion.
