### ISSUE TITLE
Peer Connections

### ISSUE THREAD

**Issue by chris110110** [bittorrent/go-btfs#343]
Hi,

Why do i have 2000 and more peer connections, even if high water is set to 600 and lower?
Low water 10;
High water 150;
Graceperiod 30s;

Port is open in router....
If i close the Port in router, i get only 80-100 connections.....which is clear.
But if i open it, i get so much connections, and my router is going to crash.

I testet the high water mark up to 1000. But i always get 2000 and much more connections.
I also testet with high water 600 and graceperiod 1s;
No change, i always get so much connections and my router restart.....

Do you have a idea?

Kind regards,
Chris

**Comment by CrCati** [comment]
Hi, @chris110110; if you're using v2.3.2,  you can set the maximum number of connections: `btfs config Swarm.ResourceMgr.Limits.System --json '{"StreamsInbound": 1000, "ConnsInbound":5000}'`. Reducing the connections of this node will decrease the connections to other nodes; then, this node may have less chance to get contracts.
Regarding the port, if you close the port in your router, the other nodes will connect to your node via NAT, that'll decrease the connections for sure. And if you set some rules for your network in your router, such as rate limit, firewall, or networking QoS, that may also affect the connections.

**Comment by chris110110** [comment]
Hi,
thank you for your help.
I tried the command but i get "Command not found"
And i use 2.3.2
And i set up a brand new node.

Do you have any ideas?
Regards,
Chris

**Comment by chris110110** [comment]
Hi again,

I can set the Max number of connections now!
Thank you very much for your help.

Kind regards,
Chris

**Comment by CrCati** [comment]
Since it's solved, I'll close this issue now; please feel free to reopen it if you have any further questions.
