### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by JeanCarloEM** [bittorrent/go-btfs#345]
An official Docker image that accompanies releases would be most welcome!

I suppose the fact that you don't have to build your own docker image is an allied fact, ease of deployment which will result in more adoption, plus the fact that with a smoother update the nodes tend to be less prone to crashes than a resettlement.

**Comment by CrCati** [comment]
Thank you for taking the time to submit this feature request. Your detailed explanation of the potential benefits, including ease of deployment and smoother updates, is greatly appreciated. I'll forward this request to the dev team to discuss it.
