### ISSUE TITLE
[BUG] panic: runtime error: index out of range [1] with  length 1 

### ISSUE THREAD

**Issue by simbadMarino** [bittorrent/go-btfs#346]
**Describe the bug**
github.com/markbates/hepa/filters dependency v0.17.0 in go.mod is causing debugging issues while running for iOS and Android (haven't tested if same happens for Windows or Linux)

**To Reproduce**
1. Build btfs 2.3.1 OR 2.3.2 from source
2. Run btfs init or btfs daemon using debugging capabilities (in my case I used Xcode and Android Studio)

**Expected behavior**
BTFS crashes at debug session start:

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/markbates/pkger/internal/takeon/github.com/markbates/hepa/filters.glob..func1()
	/Users/simbadmarino/go/pkg/mod/github.com/markbates/pkger@v0.17.0/internal/takeon/github.com/markbates/hepa/filters/env.go:15 +0x2b0
github.com/markbates/pkger/internal/takeon/github.com/markbates/hepa/filters.init()
	/Users/simbadmarino/go/pkg/mod/github.com/markbates/pkger@v0.17.0/internal/takeon/github.com/markbates/hepa/filters/env.go:42 +0x1c
(lldb) 

**Screenshots**
<img width="1212" alt="image" src="https://github.com/bittorrent/go-btfs/assets/11146636/a90f0bdd-d992-46e7-82ec-2dcfa390087d">

**Desktop (please complete the following information):**
 - OS: iOS 16.6 OR Android 11
 - Version 2.3.1 /2.3.2

**Additional context**
If I update markbates/pkger to latest latest version v0.17.1 fixes this issue, apparently it is caused by a known issue on hepa library described here: https://github.com/markbates/pkger/pull/102 

Recommended actions:  

Update pkger version in https://github.com/bittorrent/go-btfs/blob/58978cbfe94926668e30295782cd0c57b7633449/go.mod#L96 to github.com/markbates/pkger v0.17.1

**Comment by CrCati** [comment]
Hi, @simbadMarino. Thank you for your feedback. iOS and Android are not supported yet; you can build the source code according to your needs. If this issue happens in  Windows or Linux, please feel free to open a new issue or comment on this issue.

**Comment by simbadMarino** [comment]
Thanks, will fix at my end solely then hehe, best regards, closing issue
