### ISSUE TITLE
Enable "API Endpoint" URL format with SSL and no port

### ISSUE THREAD

**Issue by JeanCarloEM** [bittorrent/go-btfs#347]
When logging into the dashboard for the first time and setting the "API Endpoint" setting to httpS and not specifying the port, i get the error message "Invalid API URL Format!"

As i am using "go-btfs" in Kubertnetes with Traefik, all traffic from port 5001 is internal routed through port 443 (https) with certificate let's encrypt.

I ask that the URL format check allow for a default httpS://my-domain.com/ including the missing port specification.

Thanks!

**Comment by CrCati** [comment]
Hi, @JeanCarloEM. As for the specific routing configuration you've mentioned (port 5001 internally routed through port 443 with Let's Encrypt), it does not appear to be the direct cause of this error. Is the http://xxx format working well for your node? Any error message for this format?

**Comment by JeanCarloEM** [comment]
Hi @CrCati, thanks for your attention. It doesn't work, I suppose that traefik itself automatically redirects port 80 to 443, not being possible to access it only on port 80. The information displayed on the console is "request blocked"

**Comment by CrCati** [comment]
That may caused by your K8s settings. Does the 'http://' format work well if you deployed a node on your host?

**Comment by JeanCarloEM** [comment]
It doesn't work, because the error I mentioned happens when configuring the field. That is, the error does not occur when accessing the API that has nothing to do with Kubernetes, Docker and much less with traefik, but with a directive programmed in the dashboard. Is there any validation javascript function on the "submit" button that checks if the entered URL is valid. I assume it's some REGEX because it's the most common, but there are other ways to validate a field.

I actually located where the validation is done, although I'm not sure if that's the only place it's done. But REGEX is not used.

Maybe I should open this issue on bittorrent/btfs-dashboard, after all I don't know what level of affinity between the developers of the tools. But anyway...

File "src/utils/checks.js"

File _"btfs-dashboard/src/utils/checks.js"_, on function ```urlCheck()``` from line 21:

```javascript
export const urlCheck = (url) => {
    try {
        if (url.indexOf('http://') < 0 || !url.split(":")[2]) {
            Emitter.emit('showMessageAlert', {message: 'api_invalid', status: 'error', type: 'frontEnd'});
            return false;
        } else {
            return true;
        }
    } catch (e) {
        console.log(e)
    }
};
```

The check specifically takes place on line 23:
```javascript
        if (url.indexOf('http://') < 0 || !url.split(":")[2]) {
```

I suggest something like this:
```javascript
        if (/^https?\:\/\/(localhost|[\w\d]+(\.[\w\d]+)+)(\:\d{3,6})?\/?$/i.test(url)){
```

**Comment by CrCati** [comment]
You're great! AFAIK, https is not supported for now; I'll forward your suggestion and solution to the community development team for consideration in future releases. Your feedback is valuable to us. You're welcome to modify the source code available in the latest release and compile your own version with HTTPS support.
