### ISSUE TITLE
 To successfully connect to the BTFS node, you will need to enable the CORS

### ISSUE THREAD

**Issue by daddydaycare** [bittorrent/go-btfs#36]
Hi Again,
I switched from linux to a windows machine because I couldnt connect to the node.
I am having same issue on windows.  Below is what was written to solve the problem.
How do you go about doing this on a windows install?
THanks 

To successfully connect to the BTFS node, you will need to enable the CORS. Follow below commands and then restart the BTFS node.

btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
btfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT","GET","POST"]'

**Comment by daniel-tron** [comment]
Refer to [issue 33](https://github.com/bittorrent/go-btfs/issues/33).
or 
Just modify the .btfs/config directly
> 
```

"API": {
  "HTTPHeaders": {
    "Access-Control-Allow-Methods": [
      "PUT",
      "GET",
      "POST"
    ],
    "Access-Control-Allow-Origin": [
      "*"
    ]
  }
}
```

**Comment by daddydaycare** [comment]
the command line didnt work. but i went in and changed manually, since that is not a full example i just cut and past and replaced the existing section and added a comma. still doesnt work.

**Comment by daniel-tron** [comment]
the sample in [issue 33](https://github.com/bittorrent/go-btfs/issues/33) is using PowerShell, anyway i wrote an [article for you](https://github.com/bittorrent/go-btfs/wiki/Enable-API-CORS-for-dashboard).
below is my node configration.
![image](https://user-images.githubusercontent.com/3644140/149733333-e253640d-1cf6-420e-8b44-63c8bf2d48f2.png)
