### ISSUE TITLE
[BUG] Can't build with GO v.1.21.1

### ISSUE THREAD

**Issue by dipol0** [bittorrent/go-btfs#381]
**Describe the bug**
Can't build with GO v.1.21.1

**To Reproduce**
1. Execute command 'make -j$(nproc) build'
2. See error:

```
plugin/loader/preload.sh > plugin/loader/preload.go
go version go1.21.1 linux/amd64
bin/check_go_version 1.18
go fmt plugin/loader/preload.go >/dev/null
go build "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/bittorrent/go-btfs".CurrentCommit=5af9d820f" -o "cmd/btfs/btfs" "github.com/bittorrent/go-btfs/cmd/btfs"
# github.com/lucas-clemente/quic-go/internal/qtls
../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
make: *** [cmd/btfs/Rules.mk:22: cmd/btfs/btfs] Ошибка 1
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version Linux 5.15.0-83-lowlatency Ubuntu SMP PREEMPT Fri Aug 18 13:09:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - GO Version 1.21.1

**Additional context**
With GO v.1.18.+ - all fine, but manual recomended use latest version - 1.21.1
Additionaly when i start BTSF node it make only max 4096+ connectiona and my software router on VM "is high" (CPU Load 100%):
![Выделение_039](https://github.com/bittorrent/go-btfs/assets/32021806/56411a92-4527-4d42-9fa0-9aaa21c5c9a6)

**Comment by CrCati** [comment]
Hi, @dipol0, thanks for your feedback! About the "The version of quic-go you're using can't be built on Go 1.20 yet." [This is because the Go standard library TLS implementation, crypto/tls, doesn't expose the APIs necessary for QUIC.](https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions). As to the CPU load, what's the number of peers for this node? And does the CPU fluctuate from 40%~100% instead of always 100%?

**Comment by dipol0** [comment]
@CrCati ,

1. If i understand i need use GO version - 1.18 - yes?
2. Now dashboard show 3000+, but some time 4095 (its MAX)
![Выделение_040](https://github.com/bittorrent/go-btfs/assets/32021806/028d0221-a6e4-4f12-a942-39972d7f12f8)

In config file i set recommended parameters:

```
    "ConnMgr": {
      "Type": "basic",
      "LowWater": 10,
      "HighWater": 900,
      "GracePeriod": "10s"
    },
    "ResourceMgr": {
      "Limits": {
        "System": {
          "Streams": 0,
          "StreamsInbound": 96000,
          "StreamsOutbound": 0,
          "Conns": 0,
          "ConnsInbound": 3000,
          "ConnsOutbound": 0,
          "FD": 0,
          "Memory": 0
        },
```
3. If i stop node CPU Load is slow down.... (but node working? cpu load up to 100% all time)
(pic - cpu load if node NOT running)
![Выделение_043](https://github.com/bittorrent/go-btfs/assets/32021806/d2174827-602b-42d5-8ce9-2884fd0b88c0)

**Comment by simbadMarino** [comment]
You can compile up to go v1.19.9, at least this is what I'm using right now and working fine :)

**Comment by dipol0** [comment]
I think close issue about GO version ))

**Comment by CrCati** [comment]
> You can compile up to go v1.19.9, at least this is what I'm using right now and working fine :). I'm courious on how are you getting so much peer connections, I usually can't have more than 100 and already did the port forwarding.. any advice on how to reach more peers? specially I'd like to know if there is a way to speed up the peers discovery when starting my daemon. @CrCati @dipol0 any advice or command I can use?

According to its [README](https://github.com/quic-go/quic-go/blob/master/README.md), 1.20 should be OK.

**Comment by CrCati** [comment]
> @simbadMarino I found 2 controversial hints ))
> 
>     1. https://github.com/bittorrent/go-btfs#notices
> 
>     2. https://docs.btfs.io/docs/faq-1 (see - "How to configure the recommended number of network connections in BTFS v2.3.1, and what are the recommended configuration values?")
> 
> 
> i use first at now but have only 4095 connections (show in dashboard). May be network config limits (no go-btfs) - i dont known.
> 
> **UPD** additionaly i change hard soft limits in /etc/security/limmits.conf and get more then 4095 connections )) (you may try - https://sysadminxpert.com/configure-ulimit-values-permanently-on-linux/)
> 
> ![Выделение_045](https://user-images.githubusercontent.com/32021806/271662942-dd4a29ab-7006-4ca2-a988-c07be5776598.png)
> 
> @simbadMarino 1 set in config _ResourceManager_ section _"ConnsInbound": 0,_ 2 update (increase) hard soft limits (see link below)

'{"ConnsInbound":0}' will unblock the inbound connections to improve connectivity.
