### ISSUE TITLE
S3-API does not support metadata  for PutObject operation

### ISSUE THREAD

**Issue by mantlik** [bittorrent/go-btfs#383]
**Describe the bug**
Metadata headers are not supported for PutObject operation. This causes failures for rclone, a popular file synchronization tool.

**To Reproduce**
1. With latest version of rclone with the btfs data source defined as S3 - other with proper access keys in the configuration
execute
rclone --dump-headers copy test.data btfs:testbucket/test.data
    
2. See error
Rclone produces error
2023/10/01 10:00:28 ERROR : test.data: Failed to copy: NotImplemented: A header you provided implies functionality that is not implemented

And the following error appears in the btfs server log:
Oct  1 10:00:28 fm-ubuntu btfs[1944652]: s3-api: | 2023-10-01T10:00:28-04:00 | <PUT > | /borg/test.data | PutObjectHandler | <nil> | param x-amz-meta- is unsported |  249.734µs

**Proposed fix**
The following simple code changes fixed the issue for me:
```
diff --git a/s3/api/requests/parsers.go b/s3/api/requests/parsers.go
index 37c6f89c4..93487ae3f 100644
--- a/s3/api/requests/parsers.go
+++ b/s3/api/requests/parsers.go
@@ -106,7 +106,7 @@ func parseLocationField(vars map[string]string, query url.Values, headers http.H
                return
        }
        if !supp && has {
-               err = ErrWithUnsupportedParam{name}
+               err = ErrWithUnsupportedParam{ft.Name}
                return
        }
        if requ && !has {
diff --git a/s3/api/requests/parsers_object.go b/s3/api/requests/parsers_object.go
index 68916bf97..f43936954 100644
--- a/s3/api/requests/parsers_object.go
+++ b/s3/api/requests/parsers_object.go
@@ -24,6 +24,7 @@ var putObjectSupports = fields{
        "Expires":         true,
        "ContentMD5":      true,
        "ChecksumSHA256":  true,
+       "Metadata":        true,
 }
```

The first change in the file parsers.go is not required to fix the issue, but provides the proper name of the field which is causing the issue instead of misleading "x-amz-meta-".

**Comment by CrCati** [comment]
Thanks for your feedback! I'll forward the code changes to the community dev team to assess.

**Comment by CrCati** [comment]
Hi, @mantlik. The feature to support more header formats is on the way. You can try 'aws-cli get-object' for now. I'll close this GitHub issue now; if you have more information to share, please feel free to reopen it.

**Comment by Motophan** [comment]
if it doesnt support deletion could the api just hide the file and wait for it to fall off the network?
