### ISSUE TITLE
[BUG]Some contract status anomalies， status is DRAFT

### ISSUE THREAD

**Issue by boringw** [bittorrent/go-btfs#395]
Looking at the console logs a while ago, I noticed that one node took 6 contracts in one day，But https://scan.btfs.io/ still shows Miners Ranking with a maximum of only 60M.(one contract 40-50M,6 contract at least 200M)
so I added logs and after some time realized it was a contract status exception

if contract status exception listing command will not display the contract,  I changed the command code so that contracts with an abnormal status can be displayed.

command:   `btfs storage contracts list host -o escrow_time,desc -s 6`
Command Result:
`{
    "contracts":[
        {
            "contract_id":"59ce7a89-a864-4369-af03-b691de551f8f,88e18711-8349-4eb6-a5f4-ce4effdecd2a",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":2,
            "start_time":"2023-10-10T06:06:38.821272Z",
            "end_time":"2023-11-09T06:06:38.821272Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5298463,
            "shard_hash":"QmNM5yYH7PYUhLCGCyp7oW4x5iPEQjevsLvFJw7isw9VWF",
            "file_hash":"QmNM5yYH7PYUhLCGCyp7oW4x5iPEQjevsLvFJw7isw9VWF",
            "last_modify_time":"2023-10-10T06:07:26.9393Z"
        },
        {
            "contract_id":"c61ab451-4c44-4171-a9d5-5aad8dd93663,c380989e-8b12-45e5-a5ad-f82459db9b94",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":0,
            "start_time":"2023-10-10T03:33:02.248697083Z",
            "end_time":"2023-11-09T03:33:02.248697083Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5468447,
            "shard_hash":"QmdhcnJ5bpvGt15wjFC38MfZmwC2GafkNTyaEJWSUvdj2G",
            "file_hash":"QmdhcnJ5bpvGt15wjFC38MfZmwC2GafkNTyaEJWSUvdj2G",
            "last_modify_time":"2023-10-10T03:33:02.594381887Z"
        },
        {
            "contract_id":"aac33b31-7200-42e7-88aa-7daf9ac0364f,092b536e-c6eb-4335-b792-bd77ec18091d",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":0,
            "start_time":"2023-10-10T03:23:26.212240962Z",
            "end_time":"2023-11-09T03:23:26.212240962Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5643613,
            "shard_hash":"QmUpXmNwjmUC7FQA1r5WTownhvQ4ZMDpAHHzXJz511sF6E",
            "file_hash":"QmUpXmNwjmUC7FQA1r5WTownhvQ4ZMDpAHHzXJz511sF6E",
            "last_modify_time":"2023-10-10T03:23:26.496798547Z"
        },
        {
            "contract_id":"9df7a6d5-c3da-458e-a114-96eec98cd988,3df32f6a-5cf1-415f-88a9-b20dca3c6ce5",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":0,
            "start_time":"2023-10-10T05:15:26.49553Z",
            "end_time":"2023-11-09T05:15:26.49553Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5587293,
            "shard_hash":"Qmd8dyEZh5BLvfhXcCrJum4zsS37chnU1FbYog9Sjwjg4H",
            "file_hash":"Qmd8dyEZh5BLvfhXcCrJum4zsS37chnU1FbYog9Sjwjg4H",
            "last_modify_time":"2023-10-10T05:15:37.113509Z"
        },
        {
            "contract_id":"3d2a7786-6cd3-439e-b3c5-038e6ec3abe2,490c5c74-7e49-46c6-8847-ffd78ce34f1e",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":0,
            "start_time":"2023-10-10T03:20:16.321831029Z",
            "end_time":"2023-11-09T03:20:16.321831029Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5345567,
            "shard_hash":"QmNvpinFeFxzMr6yMkBSqoUmLZiWNtBLMsvyq51msSaNrf",
            "file_hash":"QmNvpinFeFxzMr6yMkBSqoUmLZiWNtBLMsvyq51msSaNrf",
            "last_modify_time":"2023-10-10T03:20:16.9608126Z"
        },
        {
            "contract_id":"0949be77-ac60-4ce2-899c-4cfee2f3cd8d,7c98ddfd-5416-47d1-ba78-86d3899b15e4",
            "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",
            "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",
            "status":0,
            "start_time":"2023-10-10T03:26:38.183093901Z",
            "end_time":"2023-11-09T03:26:38.183093901Z",
            "next_escrow_time":"0001-01-01T00:00:00Z",
            "compensation_paid":0,
            "compensation_outstanding":0,
            "unit_price":125000000,
            "shard_size":5347615,
            "shard_hash":"QmeegZc3Pd4xPpLCNGW6fnUeNVi8QS3yeT4ovHFa9JQPo7",
            "file_hash":"QmeegZc3Pd4xPpLCNGW6fnUeNVi8QS3yeT4ovHFa9JQPo7",
            "last_modify_time":"2023-10-10T03:26:38.51512748Z"
        }
    ]
}
`

This was a problem discovered a little earlier, so the contract time was then
can see that of the 6 contracts, only one status is 2, indicating that the upload has been completed, and the other status is 0, indicating DRAFT status.
But according to the logs the uploading of these contracts was completed

I have a lot of nodes, every day there are a large number of contract status anomalies, resulting in much less airdrop income, almost can not afford to pay the server fee, I hope to deal with it, thank you!

**Comment by yu-btc** [comment]
Hi, I've seen your feedback.，the BTFS tech community has been looking at it. We will contact you if we need your help.

Good luck!

**Comment by yu-btc** [comment]
> Looking at the console logs a while ago, I noticed that one node took 6 contracts in one day，But https://scan.btfs.io/ still shows Miners Ranking with a maximum of only 60M.(one contract 40-50M,6 contract at least 200M) so I added logs and after some time realized it was a contract status exception
> 
> if contract status exception listing command will not display the contract, I changed the command code so that contracts with an abnormal status can be displayed.
> 
> command: `btfs storage contracts list host -o escrow_time,desc -s 6` Command Result: `{     "contracts":[         {             "contract_id":"59ce7a89-a864-4369-af03-b691de551f8f,88e18711-8349-4eb6-a5f4-ce4effdecd2a",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":2,             "start_time":"2023-10-10T06:06:38.821272Z",             "end_time":"2023-11-09T06:06:38.821272Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5298463,             "shard_hash":"QmNM5yYH7PYUhLCGCyp7oW4x5iPEQjevsLvFJw7isw9VWF",             "file_hash":"QmNM5yYH7PYUhLCGCyp7oW4x5iPEQjevsLvFJw7isw9VWF",             "last_modify_time":"2023-10-10T06:07:26.9393Z"         },         {             "contract_id":"c61ab451-4c44-4171-a9d5-5aad8dd93663,c380989e-8b12-45e5-a5ad-f82459db9b94",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":0,             "start_time":"2023-10-10T03:33:02.248697083Z",             "end_time":"2023-11-09T03:33:02.248697083Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5468447,             "shard_hash":"QmdhcnJ5bpvGt15wjFC38MfZmwC2GafkNTyaEJWSUvdj2G",             "file_hash":"QmdhcnJ5bpvGt15wjFC38MfZmwC2GafkNTyaEJWSUvdj2G",             "last_modify_time":"2023-10-10T03:33:02.594381887Z"         },         {             "contract_id":"aac33b31-7200-42e7-88aa-7daf9ac0364f,092b536e-c6eb-4335-b792-bd77ec18091d",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":0,             "start_time":"2023-10-10T03:23:26.212240962Z",             "end_time":"2023-11-09T03:23:26.212240962Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5643613,             "shard_hash":"QmUpXmNwjmUC7FQA1r5WTownhvQ4ZMDpAHHzXJz511sF6E",             "file_hash":"QmUpXmNwjmUC7FQA1r5WTownhvQ4ZMDpAHHzXJz511sF6E",             "last_modify_time":"2023-10-10T03:23:26.496798547Z"         },         {             "contract_id":"9df7a6d5-c3da-458e-a114-96eec98cd988,3df32f6a-5cf1-415f-88a9-b20dca3c6ce5",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":0,             "start_time":"2023-10-10T05:15:26.49553Z",             "end_time":"2023-11-09T05:15:26.49553Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5587293,             "shard_hash":"Qmd8dyEZh5BLvfhXcCrJum4zsS37chnU1FbYog9Sjwjg4H",             "file_hash":"Qmd8dyEZh5BLvfhXcCrJum4zsS37chnU1FbYog9Sjwjg4H",             "last_modify_time":"2023-10-10T05:15:37.113509Z"         },         {             "contract_id":"3d2a7786-6cd3-439e-b3c5-038e6ec3abe2,490c5c74-7e49-46c6-8847-ffd78ce34f1e",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":0,             "start_time":"2023-10-10T03:20:16.321831029Z",             "end_time":"2023-11-09T03:20:16.321831029Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5345567,             "shard_hash":"QmNvpinFeFxzMr6yMkBSqoUmLZiWNtBLMsvyq51msSaNrf",             "file_hash":"QmNvpinFeFxzMr6yMkBSqoUmLZiWNtBLMsvyq51msSaNrf",             "last_modify_time":"2023-10-10T03:20:16.9608126Z"         },         {             "contract_id":"0949be77-ac60-4ce2-899c-4cfee2f3cd8d,7c98ddfd-5416-47d1-ba78-86d3899b15e4",             "host_id":"16Uiu2HAkzGXDQBaMgR7KWbfEUmUdSYgob7pTwNSZKJtw77uqcfXR",             "renter_id":"16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E",             "status":0,             "start_time":"2023-10-10T03:26:38.183093901Z",             "end_time":"2023-11-09T03:26:38.183093901Z",             "next_escrow_time":"0001-01-01T00:00:00Z",             "compensation_paid":0,             "compensation_outstanding":0,             "unit_price":125000000,             "shard_size":5347615,             "shard_hash":"QmeegZc3Pd4xPpLCNGW6fnUeNVi8QS3yeT4ovHFa9JQPo7",             "file_hash":"QmeegZc3Pd4xPpLCNGW6fnUeNVi8QS3yeT4ovHFa9JQPo7",             "last_modify_time":"2023-10-10T03:26:38.51512748Z"         }     ] } `
> 
> This was a problem discovered a little earlier, so the contract time was then can see that of the 6 contracts, only one status is 2, indicating that the upload has been completed, and the other status is 0, indicating DRAFT status. But according to the logs the uploading of these contracts was completed
> 
> I have a lot of nodes, every day there are a large number of contract status anomalies, resulting in much less airdrop income, almost can not afford to pay the server fee, I hope to deal with it, thank you!

Hello. After check.
1, the first challenge was successful and subsequent challenges failed, you can check if the file exists first.
2, be sure to ensure network connectivity, network problems may lead to challenge failure.

BTFS nodes are spread all over the world, it is a normal situation for network problems to lead to failure.
Good luck!

**Comment by boringw** [comment]
I've checked a few times to make sure the file exists and the network is connected. but problem still exists.

"subsequent challenges failed", Does it mean that the challenge that GUARD followed up with failed?

Since the GUARD works in a black box right now, I'm trying to troubleshoot possible causes, but have no ideas.
So I'd like to ask a few questions to try to solve the problem.

1, are the "subsequent challenges" initiated by the guard?
2, How do the challenges initiated by the guard interact with the nodes?
3, are the challenges initiated by the guard done by the official nodes? If yes, is there an id of the node?

**Comment by yu-btc** [comment]
1. yes." Subsequent challenges" are initiated by a guard, which is a special role in the BTFS network that monitors the behaviour of nodes and ensures the health and security of the network.

2. A challenge initiated by a guard interacts with a node by communicating with the node through the Peer-to-Peer network protocol.

3. It is currently a stable node in the BTFS technology community, and will be optimised to become a random community node to achieve a fully distributed effect.

Have a nice day.

**Comment by boringw** [comment]
> 1. yes." Subsequent challenges" are initiated by a guard, which is a special role in the BTFS network that monitors the behaviour of nodes and ensures the health and security of the network.
> 2. A challenge initiated by a guard interacts with a node by communicating with the node through the Peer-to-Peer network protocol.
> 3. It is currently a stable node in the BTFS technology community, and will be optimised to become a random community node to achieve a fully distributed effect.
> 
> Have a nice day.

Thank you for your reply.
3，“become a random community node” Is this btips? https://github.com/bittorrent/BTIPs/blob/master/BTIPS/BTIP-50.md

Can you clarify the current guard node id, I'd like to further troubleshoot what the problem is, btips-50 should take a while
thanks

**Comment by yu-btc** [comment]
Yes, you understood exactly right. Btips-50 is still in build.

I don't have the relevant information to provide for the id you mentioned, sorry about that.

Thank you for your support.

**Comment by boringw** [comment]
> Yes, you understood exactly right. Btips-50 is still in build.
> 
> I don't have the relevant information to provide for the id you mentioned, sorry about that.
> 
> Thank you for your support.

Thank you for your reply.
I've tried a lot of things in the meantime with no luck, but I don't think it's the network, there's no problem with btfs network connectivity right now.

I noticed that other uploading nodes upload contracts every 5 minutes, but 16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E uploads contracts every 3 minutes, could this be the reason?

please check again, since only this node contract is massively invalid.It's not quite a host node problem

thanks

**Comment by yu-btc** [comment]
> > Yes, you understood exactly right. Btips-50 is still in build.
> > I don't have the relevant information to provide for the id you mentioned, sorry about that.
> > Thank you for your support.
> 
> Thank you for your reply. I've tried a lot of things in the meantime with no luck, but I don't think it's the network, there's no problem with btfs network connectivity right now.
> 
> I noticed that other uploading nodes upload contracts every 5 minutes, but 16Uiu2HAmJQ5imTUYAgQu6S69jQ2p2BdkVC96yvPSttsMoZVZes7E uploads contracts every 3 minutes, could this be the reason?
> 
> please check again, since only this node contract is massively invalid.It's not quite a host node problem
> 
> thanks

File uploads are community behaviour and we are willing to assist you in checking if network is working. Thank you for your feedback.
