### ISSUE TITLE
caught panic

### ISSUE THREAD

**Issue by disund** [bittorrent/go-btfs#399]
: runtime error: slice bounds out of range [:24] with capacity 1
goroutine 5235446 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate.func1()
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:202 +0x58
panic({0x2c83ac0, 0xc048f86d20})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc0399b8480, {0xc050b64b17, 0x1?, 0x1})
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc04ba742f0)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x403e660, 0xc04ba742f0})
        pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x280626911f0?, 0xc0399b8480})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x280626911f0?, 0xc0399b8480?})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0x0?, {0x280626911a0?, 0xc0399b8480})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:213 +0x146
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:322 +0x97
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112

**Comment by yu-btc** [comment]
https://github.com/bittorrent/go-btfs/issues/340
Hello, you can refer to this issue，Thanks for the feedback.
