### ISSUE TITLE
Migrate BTFS v1 to v2

### ISSUE THREAD

**Issue by akinto2006** [bittorrent/go-btfs#40]
Can someone post a guide on how to migrate v1 to v2 without loosing balances or the peer ID? I don't want to start out without any contracts again. I tried downloading the windows binary but with the following issues:

1. It is using the default folder for the repo location instead of the one I set before. I copied the whole correct repo folder from v1 and it displayed the right peer ID and address but I can't change the repo location.
2. It is saying that I need a minimum of 100 BTTC. This is fine but I am reluctant to transfer any funds to it as I am not sure if it is the same passphrase as the BTTOLD wallet I have in Tronlink and BTFS.
3. Is this already out of testnet?

**Comment by Sophia-yu-kk** [comment]
Currently BTFS 2.0 is still in the beta network stage and is parallel to BTFSV1.6.0. Later, an upgrade and migration plan will be announced.
