### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by disund** [bittorrent/go-btfs#400]
What am I doing wrong? Brand new machine, newly installed Win10, directly connected to a public IP with all ports open, but constantly getting error codes, and the node has been online for 4 days." 

	Initializing daemon...
go-btfs version: 2.3.3-5af9d82
Repo version: 10
System version: amd64/windows
Golang version: go1.18
Repo location: D:\btfs
Peer identity: 16Uiu2HAmN9fnzLq3Y2u1vqjiM7jk5Ep2xaTZWGqHsMcdCpDpQmZT

error 1
←[31mERROR←[0m  dht     go-libp2p-kad-dht@v0.20.0/dht_net.go:47 ignoring incoming dht message while not in server mode

error 2 
LastSendCheques  map[] <nil>

error 3

: runtime error: slice bounds out of range [:24] with capacity 1
goroutine 5235446 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate.func1()
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:202 +0x58
panic({0x2c83ac0, 0xc048f86d20})
/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc0399b8480, {0xc050b64b17, 0x1?, 0x1})
pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc04ba742f0)
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x403e660, 0xc04ba742f0})
pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x280626911f0?, 0xc0399b8480})
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x280626911f0?, 0xc0399b8480?})
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0x0?, {0x280626911a0?, 0xc0399b8480})
pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:213 +0x146
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:322 +0x97
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112

And why is the node consuming all resources on the computer - CPU 60%, memory 10GB, bandwidth 20mbits - and it seems like it's not reading from or writing to the hard disk? Only around 40MB in 4 days. Why?"

**Comment by yu-btc** [comment]
Hi, your feedback is a common tip and will not affect contract acquisition. The community developers will optimise the error message to make it easier to understand. You can ignore it.

You feedback resource consumption situation `CPU 60%, memory 10GB, bandwidth 20mbits - and it seems like it's not reading from or writing to the hard disk? Only around 40MB in 4 days.` , have relevant data screenshots can provide, I can help you look at.

**Comment by yu-btc** [comment]
You can reopen this issue if you need to, I'll close it for now as it's beyond feedback time.
