### ISSUE TITLE
Installation error for BTFS beta version 2.3.4

### ISSUE THREAD

**Issue by turbowebmaster** [bittorrent/go-btfs#401]
Hi dear staff,

today I tried to install on linux arm64 the new beta version of BTFS cloning it from GitHub; the problem is that the installation failed with this error:
...
$ sudo make install
/bin/bash: line 1: go: command not found
/bin/bash: line 1: go: command not found
/bin/bash: line 1: go: command not found
/bin/bash: line 1: go: command not found
make: *** [mk/golang.mk:115: check_go_version] Error 127

I have taken a look to the BTFS directory file "mk/golang.mk" and I have noticed that Go language is required  with 1.18 minimum version. I had already installed that Go version (I have verified the installation with the command: $ go version) but anyway I have thought to update Go to 1.21.5 version; unfortunaltely after the update the issue with BTFS installation persists with the same error described above.

I think that there is a problem in new BTFS code, isn't it?

Thank you very much for your attention and assistance.

**Comment by yu-btc** [comment]
This error is caused by the system not finding the go command. This is not a problem with the BTFS code. Thank you very much for your feedback!

**Comment by simbadMarino** [comment]
@turbowebmaster , make sure to follow the instructions to install go in linux before building go-btfs from source code: 
![image](https://github.com/bittorrent/go-btfs/assets/11146636/b621be01-3f4f-4fc3-893d-fb4395fbcfae)

P.S. if you already installed go just run: `export PATH=$PATH:/usr/local/go/bin` & then test installation by running: ` go version`

**Comment by turbowebmaster** [comment]
@simbadMarino, @yu-btc  thank you very much for you replies. I solved the issue. Go was not the problem because it was already correctly installed on my system when I opened this ticket. The problem was the command sudo that needed to have the path of go in its configuration; I used this command:

$ sudo visudo

And then I modified the sudo configuration adding the go path:

Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin"

This solved the problem. Bye!
