### ISSUE TITLE
[Feature] actually have a s3 compatible api

### ISSUE THREAD

**Issue by Motophan** [bittorrent/go-btfs#406]
https://github.com/bittorrent/BTIPs/blob/master/BTIPS/BTIP-25.md

This implies a s3 compatible api but there are a few things you have to support or it is not considered s3 compatible. Erasure / delete is one of them. 

When I tried to add my btfs node to rclone under a generic s3 endpoint I would get errors when I delete or move things. The reason I suspect this is happening is because btfs does not support erase / delete functions. When a delete command is run it will not respond w/ the exit status for the completion of the delete command. 

Why I think this: BTFS doesnt really "delete" files but stops renewing the files (is this correct?) and they fall off the network eventually. So there would be no reason to tell the client "yes its deleted" 

Solution: for clients who expect acknowledgement of deletion and / or require this (like rclone) just respond success and then hide any files when the client lists the bucket. 

The node could keep a list of files that are "deleted" and just "hide" them while cancelling all renewals for the files. This would fix the issue and only need some kind of table of "deleted" files. 

Alternatively my feature request is for rclone support. Rclone supports mounting so you can interact with btfs like a s3 bucket. Cheap cloud storage! Requesting a docs page on how to configure it if you have a node and wallet setup.

**Comment by yu-btc** [comment]
Thank you for your comments. After testing, we found that
1, we tested that the delete function is available and can be synchronized properly. the BTFS delete policy is not immediate, it will take a while. rclone deletes the files and BTFS will synchronize.

Secondly, mount this is a great feature, but this is provided by rclone itself, we are not currently doing integration specifically for rclone, so our s3 api is still necessary.

Thanks for the suggestion, will keep optimizing the project.
