### ISSUE TITLE
[Feature] rclone s3 endpoint instruction documentation

### ISSUE THREAD

**Issue by Motophan** [bittorrent/go-btfs#408]
https://github.com/bittorrent/go-btfs/issues/406

I feel this was closed improperly. 

How did you connect rclone to btfs?
What did you do?
Can you provide a endpoint example?

If you cannot do this then btfs is not s3 compatible because the generic s3 endpoint would work. 
If you were able to get rclone working please make a guide. I have been trying over and over but cant. 

Can you write the instructions down and put them into the docs?

**Comment by Motophan** [comment]
Can I pay for support?
I have been trying to get rclone working repeatedly and no one seems to care. 

If btfs is s3 compatible it will work. 
If btfs is not s3 compatible thats fine, but it says it is s3 compatible which means it would work.

**Comment by yu-btc** [comment]
I. Configuring rclone
1. rclone config Configuration
![image](https://github.com/bittorrent/go-btfs/assets/150118413/d69e7610-6160-4b7c-b92b-854902b46d1e)
2. Select your own configured remote
![image](https://github.com/bittorrent/go-btfs/assets/150118413/49c3ed70-32ed-469d-a8c8-f2cfd747bfdf)
3. provider> 31
![image](https://github.com/bittorrent/go-btfs/assets/150118413/d64d80e9-f80a-42c5-877b-9143bc2efc2d)
4. env_auth> false
![image](https://github.com/bittorrent/go-btfs/assets/150118413/13952082-0a4c-47af-a50d-cf3240eae217)
5. Enter the access_key_id and secret_access_key of the btfs.
![image](https://github.com/bittorrent/go-btfs/assets/150118413/996c9d8e-6c40-4663-adfd-0590de1545c9)
6. region>1
![image](https://github.com/bittorrent/go-btfs/assets/150118413/071df485-da31-4707-b361-7329398df330)
7. endpoint configuration:
![image](https://github.com/bittorrent/go-btfs/assets/150118413/8c26fcba-c448-4232-bd79-2df1c5173043)
8. acl configuration should be consistent with the permissions of the synchronized bucket.
![image](https://github.com/bittorrent/go-btfs/assets/150118413/6688a302-e639-4347-9c02-cda474061792)
9. Edit advanced config select n
![image](https://github.com/bittorrent/go-btfs/assets/150118413/ea9d2b9d-fc53-4997-aba6-68fd7eb69550)
10. Keep your remote Select default
![image](https://github.com/bittorrent/go-btfs/assets/150118413/17d90c82-d5f3-4b72-8d89-8176b01b9958)

**Comment by yu-btc** [comment]
II. rclone and btfs synchronization
1. rclone copy local file to btfs:  
     Command: rclone copy test.txt btfs-new01:/data
![image](https://github.com/bittorrent/go-btfs/assets/150118413/8078c947-f925-4015-889e-ea0e62f99591)
![image](https://github.com/bittorrent/go-btfs/assets/150118413/449c3a56-bc0e-4a27-8f07-49cb6b753c91)
![image](https://github.com/bittorrent/go-btfs/assets/150118413/cbe6e42c-db2d-48c6-adf2-1103605e4654)
2. rclone delete movie.mobi file under bucket
    Command: rclone delete btfs-new01:/data/movie.mobi
![image](https://github.com/bittorrent/go-btfs/assets/150118413/0a7c265c-67d0-4c9d-950f-2b4dc698f060)
![image](https://github.com/bittorrent/go-btfs/assets/150118413/653b70e7-4bf9-44aa-a329-42482d8797ac)
![image](https://github.com/bittorrent/go-btfs/assets/150118413/24da9783-e582-44a8-8447-b2c3187c48ae)

**Comment by yu-btc** [comment]
You can take a screenshot if you have a relevant error report.

**Comment by yu-btc** [comment]
Let's discuss about this issue here. It can also be referred to if anyone encounters a similar problem later on.

Actually,BTFS deletion doesn't work immediately, It takes a while, this is determined by the current BTFS mechanism.

**Comment by Motophan** [comment]
![KsrfAXb](https://github.com/bittorrent/go-btfs/assets/42502676/eae42b24-b3a1-4bb7-af9b-17850a92a804)
![image](https://github.com/bittorrent/go-btfs/assets/42502676/48f7b924-a88e-4b67-9abe-c786a384a319)
![image](https://github.com/bittorrent/go-btfs/assets/42502676/1dc99c5d-0928-4c76-a03b-aadd21e1f6fe)
![image](https://github.com/bittorrent/go-btfs/assets/42502676/ba5940db-c01a-438a-98d7-32b676caa0e1)
![image](https://github.com/bittorrent/go-btfs/assets/42502676/65e34be2-a844-4032-bb8a-d776702ae469)
![IqtRxMB](https://github.com/bittorrent/go-btfs/assets/42502676/82416582-0395-4840-a745-6d924fdc318e)

**Comment by yu-btc** [comment]
1, the operation steps can refer to my screenshot steps above.
2, The current S3 compatible interface is stored in the local BTFS node.
3, Storing on BTFS network is not supported at the moment. It will be taken into consideration later.

**Comment by Motophan** [comment]
im not sure what the point is for this then

if you cannot store it on btfs then you are just copying from one directory to another. 
You could use mv, copy, rsync, or a multitude of other tools to get your files into ~/.btfs/ since you cannot do anything with the files once they are in btfs
