### ISSUE TITLE
receive cheque, swapprotocol.SwapProtocol.Handler, error: rejecting cheque: vault not deployed by factory

### ISSUE THREAD

**Issue by ionutzuu** [bittorrent/go-btfs#41]
This is from my BTFS 2.0.1

--- upload init: start, shardSize:44631412, requestPid:16Uiu2HAmDEmbg3vqVQx2PkSa8NQXiHCqt4EL27EGz6ivKPKKbsfw, shardIndex:0 .
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid
receive handshake from peer peer_id:16Uiu2HAmDEmbg3vqVQx2PkSa8NQXiHCqt4EL27EGz6ivKPKKbsfw, chain_id:1029
receive cheque, requestPid:16Uiu2HAmDEmbg3vqVQx2PkSa8NQXiHCqt4EL27EGz6ivKPKKbsfw contractId:01a5112c-058d-4fbe-96cf-2ed1076fb17b,a8c20ba5-4aeb-453a-bbf7-cc23a99286ec
receive cheque, swapprotocol.SwapProtocol.Handler, error: rejecting cheque: vault not deployed by factory
IsPayStatus Current:contract,  hshPayStatus:paid
IsPayStatus Current:contract,  hshPayStatus:paid

I do not see the cheques in the dashboard!

My problems is how to deploy the vault or something like that. ( I've tried different nodes with clean repo folder and happens the same )

**Comment by Sophia-yu-kk** [comment]
Just delete the BTFS storage repo location. Then init it.
Regarding this reported error, we will optimize it in subsequent releases, and thank you for your support of the BTFS project.
