### ISSUE TITLE
runtime error[BUG]

### ISSUE THREAD

**Issue by asd976385560** [bittorrent/go-btfs#421]
Initializing daemon...
go-btfs version: 2.3.5-9fdd194
Repo version: 10
System version: amd64/windows
Golang version: go1.18
Repo location: D:\BTFS\btfs1
Peer identity: 16Uiu2HAmGCrWuTtEeQ1soiRKPdzdftV8crGAqqSvXVwYHzHogNzm
the address of Bttc format is:  
the address of Tron format is: 
Guide: http://127.0.0.1:5001/hostui
InitToken:  199 map
self vault: 
vault implementation is updated: 
Swarm listening on /ip4/127.0.0.1/tcp/6666
Swarm listening on /ip4/192.168.10.240/tcp/6666
Swarm listening on /ip6/240e:3a1:c69:e21::809/tcp/6666
Swarm listening on /ip6/240e:3a1:c69:e21:bb31:9ee8:564:a6e9/tcp/6666
Swarm listening on /ip6/::1/tcp/6666
Swarm listening on /p2p-circuit
Swarm announcing /ip4/117.89.40.69/tcp/41811
Swarm announcing /ip4/117.89.40.69/tcp/56675
Swarm announcing /ip4/127.0.0.1/tcp/6666
Swarm announcing /ip4/192.168.10.240/tcp/6666
Swarm announcing /ip6/240e:3a1:c69:e21:bb31:9ee8:564:a6e9/tcp/6666
Swarm announcing /ip6/::1/tcp/6666
API server listening on /ip4/127.0.0.1/tcp/5001
Dashboard: http://127.0.0.1:5001/dashboard
Gateway server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Experimental.Analytics is overridden by Experimental.StorageHostEnabled
Current host stats will be synced
Current host settings will be synced
caught panic: runtime error: slice bounds out of range [:24] with capacity 1
goroutine 4208626 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate.func1()
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:202 +0x58
panic({0x31cb3c0, 0xc07abb18c0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/libp2p/go-libp2p/p2p/net/pnet.(*pskConn).Read(0xc063bfb040, {0xc0341c87ce, 0x1?, 0x1})
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/pnet/psk_conn.go:43 +0x185
github.com/multiformats/go-multistream.(*byteReader).ReadByte(0xc009669790)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:328 +0x4e
github.com/multiformats/go-varint.ReadUvarint({0x4588f80, 0xc009669790})
        pkg/mod/github.com/multiformats/go-varint@v0.0.7/varint.go:80 +0x5a
github.com/multiformats/go-multistream.lpReadBuf({0x1c1e39a0890?, 0xc063bfb040})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:292 +0x94
github.com/multiformats/go-multistream.ReadNextTokenBytes({0x1c1e39a0890?, 0xc063bfb040?})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:275 +0x27
github.com/multiformats/go-multistream.ReadNextToken(...)
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:264
github.com/multiformats/go-multistream.(*MultistreamMuxer).Negotiate(0x13aac2d?, {0x1c1e39a0860?, 0xc063bfb040})
        pkg/mod/github.com/multiformats/go-multistream@v0.3.3/multistream.go:213 +0x146
github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity.func1()
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:322 +0x97
created by github.com/libp2p/go-libp2p/p2p/net/upgrader.(*upgrader).negotiateSecurity
        pkg/mod/github.com/libp2p/go-libp2p@v0.24.2/p2p/net/upgrader/upgrader.go:318 +0x112

**Comment by yu-btc** [comment]
This error can be ignored and will not affect the normal operation of the node. Thanks for the feedback
