### ISSUE TITLE
[Feature] Hope to add `btns` update binding `CID` function

### ISSUE THREAD

**Issue by hhun** [bittorrent/go-btfs#423]
IPFS can use `ipns name` to bind `content identifier`. After re-uploading the file, the old `ipns name` is bound to the new `content identifier`.
> ipfs key gen --type=rsa --size=2048 mykey
> ipfs name publish --key=mykey /ipfs/QmatmE9msSfkKxoffpHwNLNKgwZG8eT9Bud6YoPab52vpy
    Published to QmSrPmbaUKA3ZodhzPWZnpFgcPMFWF4QsxXbkWfEptTBJd: /ipfs/QmatmE9msSfkKxoffpHwNLNKgwZG8eT9Bud6YoPab52vpy

BTFS can only publish a new btns through `content identifier`, and cannot update the existing btns to bind a new `content identifier`

https://docs.btfs.io/docs/common-usage-1#file-pinning
https://docs.ipfs.tech/how-to/publish-ipns/#publishing-ipns-names-with-kubo

**Comment by yu-btc** [comment]
I have recorded your needs and will discuss them in the technical community. Thank you for your feedback.

**Comment by yu-btc** [comment]
I have recorded your needs and will discuss them in the technical community. Thank you for your feedback.
