### ISSUE TITLE
WBTT testnet fauce

### ISSUE THREAD

**Issue by simbadMarino** [bittorrent/go-btfs#43]
Is there a way to get testnet WBTT? I'm testing the renter side of BTFS 2.01 but I couldn't find any website to request WBTT test tokens to play around some of the features. Thanks!

**Comment by Jbekker** [comment]
It's documented here https://docs.btfs.io/v2.0/docs/btfs20-storage-rental#2-top-up-to-the-vault-address
And the faucet to get testnet BTT can be found here https://testfaucet.bt.io/#/

**Comment by simbadMarino** [comment]
It worked. Summarizing everything so anyone like me can quickly do it:

1. Get some tesnet BTT (BTTC chain) from https://testfaucet.bt.io/#/   (Bittorrent Chain Donau Testnet)
2. Swap your BTT to WBTT by sending X amount of BTT to 0x107742EB846b86CEaAF7528D5C85cddcad3e409A using Metamask
3. You will receive the same amount of WBTT in your wallet in a while. 

Note: Try with small BTT quantities first, looks like it has a limit (at least it didnt let me swap large amounts of BTT in the first try)
