### ISSUE TITLE
Error ignoring incoming dht

### ISSUE THREAD

**Issue by Raimis999** [bittorrent/go-btfs#443]
Hello, before i was getting sometimes btt to my account, but after i started to get this messages i get nothing where is the problem? It is for last 1 year allready. I even created a new node and its the same. Ports open, internet good, ssd good.

![btfs error](https://github.com/user-attachments/assets/7f6b3c2d-950d-40d5-a0e4-81bdb41a622b)
![btfs error full](https://github.com/user-attachments/assets/2da2ab2e-e760-4442-a473-87c6a4d128fe)

**Comment by chris110110** [comment]
Same issue here.

**Comment by yu-btc** [comment]
please ignore this error, this error does not affect contract acquisition. Thanks for you feedback.

**Comment by Raimis999** [comment]
But when i dont have this error i get btt, now i get nothing for 1 year, so there is a problemSent from my iPhoneOn 22 Jul 2024, at 10:29, yu-btc ***@***.***> wrote:﻿
Closed #443 as completed.
