### ISSUE TITLE
[BUG] documentation

### ISSUE THREAD

**Issue by karawitan** [bittorrent/go-btfs#444]
**Describe the bug**

Hi, the documentation at https://docs.btfs.io/v1.0/docs/deposit-btt-to-btfs , at "Obtain BTT Crypto Wallet Address" refers to a "CONVERT TOOL" within the tronide.io website, but no such thing is available . Is a newer doc available or someone is able to check and fix it ?

**To Reproduce**
login to tronide.io 
Look for a "Convert Tool" on the left side bar

**Expected behavior**
Find the Convert Tool

**Screenshots**

<img width="954" alt="image" src="https://github.com/user-attachments/assets/808a3485-68c4-406c-8e61-c840d9c8691a">

<img width="663" alt="image" src="https://github.com/user-attachments/assets/fe05be75-3db5-4619-a069-2b84659170a8">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Version [e.g. 2.2.1]

**Additional context**

**Comment by yu-btc** [comment]
Hello, thank you for your feedback. The related functions are no longer maintained since BTFSV2.0.

**Comment by simbadMarino** [comment]
To expand on the answer, you were using old docs, refer to this for newest docs: https://docs.btfs.io/docs/btfs-overview

Always review you are under the latest applicable docs for BTFS: 
![image](https://github.com/user-attachments/assets/ec284eef-5d8d-407c-b869-a713b5aaa2aa)
