### ISSUE TITLE
[BUG] documentation : btfs wallet: unknown command

### ISSUE THREAD

**Issue by karawitan** [bittorrent/go-btfs#445]
**Describe the bug**
The documentation at https://docs.btfs.io/v1.0/docs/deposit-btt-to-btfs suggests to use "btfs wallet" command once the TRX transfer has been done, but no such command exist as of btfs version 3.0.0.

**To Reproduce**
btfs version
btfs version 3.0.0

btfs wallet deposit 99
Error: Unknown Command "wallet"

**Expected behavior**

**Screenshots**
expected “BTFS wallet deposit Done”

**Desktop (please complete the following information):**
 - OS: macos 
 - Version 14.6.1

**Additional context**

**Comment by yu-btc** [comment]
Hello, thank you for your feedback. The related functions are no longer maintained since BTFS v2.0.
