### ISSUE TITLE
panic: qtls.ClientHelloInfo doesn't match

### ISSUE THREAD

**Issue by Rchua72** [bittorrent/go-btfs#45]
I am getting the error "panic: qtls.ClientHelloInfo doesn't match" whenever I try to initialize btfs.  If you look at the screenshot, I am in the ~/go-btfs/cmd/btfs folder and then I try to run the command "./btfs init" but I get the error.  My golang version is go1.17.6

![image](https://user-images.githubusercontent.com/6827300/150708031-43e1e8aa-f46d-4c48-a2d8-45e770852073.png)

**Comment by daniel-tron** [comment]
try build with golang 1.5
