### ISSUE TITLE
btfs-dashboard not working 

### ISSUE THREAD

**Issue by KPR-V** [bittorrent/go-btfs#456]
i have successfully run a node as said on the docs local dashboard
![image](https://github.com/user-attachments/assets/5f64236b-0ee2-4973-ab11-04164786125f)

 should work on the given link 
 [localhost:5001/dashboard](http://localhost:5001/)
 @whyrusleeping  @Stebalien @jbenet  @btc @taiyangc

**Comment by yu-btc** [comment]
https://docs.btfs.io/v2.3.4/docs/btfs20-dashboard#settings 
Hello, please refer to this document, because you may need to set the API port on the dashboard.
