### ISSUE TITLE
[BUG] The btfs storage upload repair command does not work

### ISSUE THREAD

**Issue by mantlik** [bittorrent/go-btfs#462]
**Describe the bug**
The `btfs storage upload repair` command finishes with a recovery from panic, or returning upload ID, but in either case no repair uploads are started for the stale or failed file shards. 

**To Reproduce**
1. Upload a file.
2. Watch upload status and if one or more shards did not make it from "DRAFT" to "UPLOADED" status after more than 15 minutes, proceed to the next step. Otherwise upload another file. Larger files have higher probability to not complete all shard uploads.
3. Execute command `btfs storage upload repair` for stale shards providing their shard hashes and all other required parameters.
4. Repair fails or finishes returning original upload ID of the file, but no upload of missing chunks is initiated.

**Expected behavior**
After successful submission of the  `btfs storage upload repair` command, process of uploading provided chunks should be started and should continue in the background. The `btfs storage upload status` command should reflect progress of the upload for the stale chunks and the upload should reach complete status after all chunks are uploaded.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version 3.0.0

**Additional context**
First of all, malfunctioning of the repair command is a critical problem, in fact a show stopper for serious renting on BTFS. The reason is that the guard client does not allow re-uploading of the same file twice.
Thus, if even a single contract of the file is not uploaded successfully, e.g. because the renter node lost connection to the corresponding host, there is no chance to upload the file at all, because:

- the already started file upload cannot be canceled or deleted
- the stale file upload cannot be repaired
- an attempt to re-upload the same file again will lead to the error `GuardClient: rpc error: code = Unknown desc = Persistence manager: such file hash already exist for such renter`

The only work around I was able to make up is to re-add the file with different chunking parameters and then upload it again. But this is not possible in all situations, e.g. for files uploaded using S3 API.

**Thoughts regarding the cause**
The repair code in the file `core/commands/storage/upload/upload/repair.go` seems to be outdated or very poorly designed, or both. Should be thoroughly reviewed and eventually reworked completely, I guess. 
Some changes will be likely needed for the downstream UploadShards function too.
There are multiple issues and even when I was trying to address or work around some of them, did always hit the wall again.
First of all, this part of the code will in most cases not work:
```
		ssId, _ := uh.SplitContractId(contracts[0].ContractId)
		shardIndexes := make([]int, 0)
		i := 0
		shardHashes := strings.Split(req.Arguments[1], ",")
		for _, contract := range contracts {
			if contract.ShardHash == shardHashes[i] {
				shardIndexes = append(shardIndexes, int(contract.ShardIndex))
				i++
			}
		}
```
Depending on the order, in which the hashes are provided in the command line, either some of them, or none will match hashes from the database.
The nested cycle would be needed instead of the if condition to match all command line provided hashes with the stored hashes and assign indexes to them.
The other issue is, that even when some hashes succeed to be identified, assigned indexes do not correspond to the chunk numbers and thus their upload attempt has to fail.
Another issue is that the downstream UploadShards function only works when all shard indexes are provided. My guess is that someewhere inside that function the panic is initiated when shard index goes out of range.
Finally, there is a challenge with tracing issues and failures in the repair code. There are no log outputs and no proper error handling, thus even if any process on the way fails, no trace can be found to diagnose it. Even when a panic is caught, no traceback is available.

**Comment by yu-btc** [comment]
Thanks for your feedback, we will check it. If the problem is confirmed, it will be optimized in the next version.
