### ISSUE TITLE
[BUG] Files added using S3-compatible API are not using reed-solomon chunking in version 3.0.0

### ISSUE THREAD

**Issue by mantlik** [bittorrent/go-btfs#463]
**Describe the bug**
When a file is uploaded to the node using S3-compatible API, it is chunked using default fixed size chunker instead of reed-solomon. This was not the case in the 2.x version.

**To Reproduce**
1. Upload a file using S3 API, e.g. with rclone.
2. Find uploaded file CID using node UI or file metadata.
3. Inspect the file using command `btfs object links <CID>`. 
Here is an example result - the file has fixed size chunks with no redundancy:
```
btfs object links QmTVPLh2VJ2orRmoK5AUH1X6FXsguh3pDvuMsD9KnzKhiT
QmeynaCE829pYT8vodEKbxRkcFzSpzsiCLshvLjH9dmVQf 262158 
Qmf3cYAHLTLguGT8PnmgM6br1vJ2k7gx6m2fBcsQt83gGN 262158 
QmTSeFLwbeJWfwPgRviVr2LyRTRrDPTvL9zsA2Fth9JJFu 262158 
QmXjNCGWAshGmFSqJyUTAxDhjicER6ZfGNudT81DQ31Nky 262158 
QmNq5SLHhpw8burmoS7nxiRcUqifAhqtf7662gGAWov51H 262158 
QmW2dw1xX6yn3T8zu8q8gAgdUV36TyH7VkjVT47v7zDoUN 40299 
``` 
4. Download the file using it's CID
```
btfs get QmTVPLh2VJ2orRmoK5AUH1X6FXsguh3pDvuMsD9KnzKhiT
Saving file(s) to QmTVPLh2VJ2orRmoK5AUH1X6FXsguh3pDvuMsD9KnzKhiT
 1.29 MiB / 1.29 MiB [===========================] 100.00% 0s
```
5. Add the file using reed-solomond chunking strategy
```
btfs add -s reed-solomon QmTVPLh2VJ2orRmoK5AUH1X6FXsguh3pDvuMsD9KnzKhiT
added QmQRDNGL8fQaQRVXuxNgVPmYVEgTaNwTNQzPP9RaVX9aCC QmTVPLh2VJ2orRmoK5AUH1X6FXsguh3pDvuMsD9KnzKhiT
 1.29 MiB / 1.29 MiB [===========================] 100.00%
```
6. Inspect new CID
This time the file is stored using 3x redundancy as expected:
```
btfs object links QmQRDNGL8fQaQRVXuxNgVPmYVEgTaNwTNQzPP9RaVX9aCC
QmYBytUxzTRZBWGBENsD8C7A3DNwhFxV7WTXGPbnshg39A 129     
QmU6x1jJkdW6ZcnKZQ25862p8FroZ3aYB23Dsip4eTci2j 4054899
```  

**Expected behavior**
Whether file is added using S3 API, or CLI, it should be chunked using reed-solomon strategy. Otherwise the file could not be uploaded to BTFS network.
In 2.x versions S3 API was using reed-solomon when adding files.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Version 3.0.0

**Additional context**
There is currently no way how to control how files are being added using S3 API.
To address this, one of the possible options could be addition of a configuration parameter to allow changing chunking strategy for S3-compatible API something like this:
```
  "S3CompatibleAPI": {
    "Enable": true,
    "Address": "127.0.0.1:6001",
    "HTTPHeaders": null,
    "Chunker": "reed-solomon"
  },
```
and make corresponding adjustments in the S3 code.

**Comment by yu-btc** [comment]
Thanks for your feedback, we will check it. If the problem is confirmed, it will be optimized in the next version.
