### ISSUE TITLE
BTFS 2.0.2 amd64 not runing

### ISSUE THREAD

**Issue by muyayoyo** [bittorrent/go-btfs#48]
Hello.
I´m running btfs amd64 version 2.0.1 properly since last 9 days. Today I have downloaded the new version (2.0.2) and replaced the executable by the new one. I tried run btfs daemon and it throw the folloging error:
"init settlement err:  init vault service: vault init: vault not deployed by factory".

If I restore the previous version everything works again. Should I run 
<img width="759" alt="error btfs 2 0 2" src="https://user-images.githubusercontent.com/83616786/151043352-36a4e01b-d208-4572-a635-511b12194eec.png">
any additional commands to update to version 2.0.2? I haven't found anything about update/upgrade on the Wiki.
Thank you.

**Comment by ZeroCool1974-BR** [comment]
Hi, I'm having the exact same problem running 2.0.2, but 2.0.1 runs perfect:

2.0.2:

Initializing daemon...
go-btfs version: 2.0.2-2970ddf
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: C:\Users\solra\.btfs
Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19
the private key of wallet import format is:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
the address of Bttc format is:  0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81
the address of Tron format is:  TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt
self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee
init settlement err:  init vault service: vault init: vault not deployed by factory

Error: init vault service: vault init: vault not deployed by factory

2.0.1:
Initializing daemon...
go-btfs version: 2.0.1-96bd86d
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: C:\Users\solra\.btfs
Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19
the private key of wallet import format is:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
the address of Bttc format is:  0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81
the address of Tron format is:  TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt
self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee
Swarm listening on /ip4/127.0.0.1/tcp/5002
Swarm listening on /ip4/192.168.100.49/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:19dc:15f2:193b:d309/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:39c3:2ae6:3663:15c3/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:99fa:65a0:a036:b838/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:a5ea:e2ed:5baa:b6b6/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:cd0a:5de8:db7e:7d32/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:d1a5:b714:37ae:529b/tcp/5002
Swarm listening on /ip6/2804:f24:c10d:6b00:d509:69ee:847a:70b2/tcp/5002
Swarm listening on /ip6/::1/tcp/5002
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/5002
Swarm announcing /ip4/179.109.46.75/tcp/5232
Swarm announcing /ip4/192.168.100.49/tcp/5002
Swarm announcing /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002
Swarm announcing /ip6/::1/tcp/5002
API server listening on /ip4/127.0.0.1/tcp/5002
Dashboard: http://127.0.0.1:5002/dashboard
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8082
Remote API server listening on /ip4/127.0.0.1/tcp/5102
Daemon is ready
Current host stats will be synced
Current host settings will be synced

Don't know what to do right now! Please help us!

**Comment by avm-xandry** [comment]
Everything work fo me. Try to do like said in the docs:

btfs daemon --chain-id 1029

https://docs.btfs.io/v2.0/docs/install-run-btfs20-node

**Comment by muyayoyo** [comment]
> Hi, I'm having the exact same problem running 2.0.2, but 2.0.1 runs perfect:
> 
> 2.0.2:
> 
> Initializing daemon... go-btfs version: 2.0.2-2970ddf Repo version: 10 System version: amd64/windows Golang version: go1.15.15 Repo location: C:\Users\solra.btfs Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19 the private key of wallet import format is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx the address of Bttc format is: 0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81 the address of Tron format is: TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee init settlement err: init vault service: vault init: vault not deployed by factory
> 
> Error: init vault service: vault init: vault not deployed by factory
> 
> 2.0.1: Initializing daemon... go-btfs version: 2.0.1-96bd86d Repo version: 10 System version: amd64/windows Golang version: go1.15.15 Repo location: C:\Users\solra.btfs Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19 the private key of wallet import format is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx the address of Bttc format is: 0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81 the address of Tron format is: TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee Swarm listening on /ip4/127.0.0.1/tcp/5002 Swarm listening on /ip4/192.168.100.49/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:19dc:15f2:193b:d309/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:39c3:2ae6:3663:15c3/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:99fa:65a0:a036:b838/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:a5ea:e2ed:5baa:b6b6/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:cd0a:5de8:db7e:7d32/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:d1a5:b714:37ae:529b/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:d509:69ee:847a:70b2/tcp/5002 Swarm listening on /ip6/::1/tcp/5002 Swarm listening on /p2p-circuit Swarm announcing /ip4/127.0.0.1/tcp/5002 Swarm announcing /ip4/179.109.46.75/tcp/5232 Swarm announcing /ip4/192.168.100.49/tcp/5002 Swarm announcing /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002 Swarm announcing /ip6/::1/tcp/5002 API server listening on /ip4/127.0.0.1/tcp/5002 Dashboard: http://127.0.0.1:5002/dashboard Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8082 Remote API server listening on /ip4/127.0.0.1/tcp/5102 Daemon is ready Current host stats will be synced Current host settings will be synced
> 
> Don't know what to do right now! Please help us!

Since we don´t have any support from the team (I´m sure they are to busy) I've been trying to get it to work.
If you have 2.0.1 installed and you try install (run) new versions, the error "init settlement err: init vault service: vault init: vault not deployed by factory" will be always present.

1.- You need first make a copy of "config" file and "blocks" directory under /users/YOURUSER/.btfs. 
2.- After that, erase whole ".btfs" directory.
3.- Then run the new version of btfs and follow all first steps like the first time you ran early version (2.0.0 or 2.01).

4.- After the new version is installed and running you need to stop daemon. 
5.- On /users/YOURUSER/.btfs direcctory replace the folder "blocks" with the copy from old version. 
6.- Open the config file you copied (from old version) and open the actual config file. 
7.- On new config file you need replace (from the data of old config file):

A) First, copy and paste:
  "Identity": {
    "Mnemonic": "your words",
    "PeerID": "your peerID",
    "PrivKey": "your private Key"
  },

B) Since we are on Testnet, copy and paste:
  "Services": {
    "EscrowDomain": "https://escrow-staging.btfs.io",
    "EscrowPubKeys": [
      "your data"
    ],
    "ExchangeDomain": "https://exchange-staging.bt.co",
    "FullnodeDomain": "grpc.trongrid.io:50051",
    "GuardDomain": "https://guard-staging.btfs.io",
    "GuardPubKeys": [
      "your data"
    ],
    "HubDomain": "https://hub-staging.btfs.io",
    "SolidityDomain": "grpc.trongrid.io:50052",
    "StatusServerDomain": "https://status-staging.btfs.io",
    "TrongridDomain": "https://api.shasta.trongrid.io"
  },

C) On "Experimental" object, replace HostsSyncMode value to TESTNET. 
    "HostsSyncMode": "TESTNET",

D) On "Swarm" object, replace Swarmkey value.
     "SwarmKey": "/key/swarm/psk/1.0.0/\n/base16/ your key",

You can make changes on storage later through the dashboard.

Now you need save the config file and run again the btfs daemon and your 2.0.2 version will be live with your actual score.
Make sure you do a backup first!

You can check my host: https://scan-test.btfs.io/#/node/16Uiu2HAmKegUL4vPy9ND9iVaXj6Sse8VYbTrvbJD7kpZ9HbZZjH5
Hope this help

**Comment by ZeroCool1974-BR** [comment]
> > Hi, I'm having the exact same problem running 2.0.2, but 2.0.1 runs perfect:
> > 2.0.2:
> > Initializing daemon... go-btfs version: 2.0.2-2970ddf Repo version: 10 System version: amd64/windows Golang version: go1.15.15 Repo location: C:\Users\solra.btfs Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19 the private key of wallet import format is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx the address of Bttc format is: 0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81 the address of Tron format is: TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee init settlement err: init vault service: vault init: vault not deployed by factory
> > Error: init vault service: vault init: vault not deployed by factory
> > 2.0.1: Initializing daemon... go-btfs version: 2.0.1-96bd86d Repo version: 10 System version: amd64/windows Golang version: go1.15.15 Repo location: C:\Users\solra.btfs Peer identity: 16Uiu2HAkwSVFHh88DQNx8EB93ZiK6nv1M7ujDcoTxmSg8rmfhj19 the private key of wallet import format is: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx the address of Bttc format is: 0xe9C4e68c1785986a6ca6a017BB2F509F891f9A81 the address of Tron format is: TXHGKeVjcZkPqFrc8w56aXnymDcFf45kEt self vault: 0x5e8454ea059e1deb09c9528b01f8c62cb0689cee Swarm listening on /ip4/127.0.0.1/tcp/5002 Swarm listening on /ip4/192.168.100.49/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:19dc:15f2:193b:d309/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:39c3:2ae6:3663:15c3/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:99fa:65a0:a036:b838/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:a5ea:e2ed:5baa:b6b6/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:cd0a:5de8:db7e:7d32/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:d1a5:b714:37ae:529b/tcp/5002 Swarm listening on /ip6/2804:f24:c10d:6b00:d509:69ee:847a:70b2/tcp/5002 Swarm listening on /ip6/::1/tcp/5002 Swarm listening on /p2p-circuit Swarm announcing /ip4/127.0.0.1/tcp/5002 Swarm announcing /ip4/179.109.46.75/tcp/5232 Swarm announcing /ip4/192.168.100.49/tcp/5002 Swarm announcing /ip6/2804:f24:c10d:6b00:80df:879:fdae:a6d8/tcp/5002 Swarm announcing /ip6/::1/tcp/5002 API server listening on /ip4/127.0.0.1/tcp/5002 Dashboard: http://127.0.0.1:5002/dashboard Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8082 Remote API server listening on /ip4/127.0.0.1/tcp/5102 Daemon is ready Current host stats will be synced Current host settings will be synced
> > Don't know what to do right now! Please help us!
> 
> Since we don´t have any support from the team (I´m sure they are to busy) I've been trying to get it to work. If you have 2.0.1 installed and you try install (run) new versions, the error "init settlement err: init vault service: vault init: vault not deployed by factory" will be always present.
> 
> 1.- You need first make a copy of "config" file and "blocks" directory under /users/YOURUSER/.btfs. 2.- After that, erase whole ".btfs" directory. 3.- Then run the new version of btfs and follow all first steps like the first time you ran early version (2.0.0 or 2.01).
> 
> 4.- After the new version is installed and running you need to stop daemon. 5.- On /users/YOURUSER/.btfs direcctory replace the folder "blocks" with the copy from old version. 6.- Open the config file you copied (from old version) and open the actual config file. 7.- On new config file you need replace (from the data of old config file):
> 
> A) First, copy and paste: "Identity": { "Mnemonic": "your words", "PeerID": "your peerID", "PrivKey": "your private Key" },
> 
> B) Since we are on Testnet, copy and paste: "Services": { "EscrowDomain": "https://escrow-staging.btfs.io", "EscrowPubKeys": [ "your data" ], "ExchangeDomain": "https://exchange-staging.bt.co", "FullnodeDomain": "grpc.trongrid.io:50051", "GuardDomain": "https://guard-staging.btfs.io", "GuardPubKeys": [ "your data" ], "HubDomain": "https://hub-staging.btfs.io", "SolidityDomain": "grpc.trongrid.io:50052", "StatusServerDomain": "https://status-staging.btfs.io", "TrongridDomain": "https://api.shasta.trongrid.io" },
> 
> C) On "Experimental" object, replace HostsSyncMode value to TESTNET. "HostsSyncMode": "TESTNET",
> 
> D) On "Swarm" object, replace Swarmkey value. "SwarmKey": "/key/swarm/psk/1.0.0/\n/base16/ your key",
> 
> You can make changes on storage later through the dashboard.
> 
> Now you need save the config file and run again the btfs daemon and your 2.0.2 version will be live with your actual score. Make sure you do a backup first!
> 
> You can check my host: https://scan-test.btfs.io/#/node/16Uiu2HAmKegUL4vPy9ND9iVaXj6Sse8VYbTrvbJD7kpZ9HbZZjH5 Hope this help

I'm not sure if I did the steps correctly but now I'm running 2.0.2 but my score dropped to 0. I can't run 2.0.1 anymore...
The last step on D what key I have to copy and paste there?

Thanks for your help! ;-)

**Comment by ZeroCool1974-BR** [comment]
I've done everything right, now my score is back to 4, thanks again! ;-)
