### ISSUE TITLE
[Feature] Make dashboard login opt-in for headless systems

### ISSUE THREAD

**Issue by simbadMarino** [bittorrent/go-btfs#487]
**Is your feature request related to a problem? Please describe.**
After v3.1 version UI login is required, this is good for security, but at the same time creates extra hurdles for BTFS headless or shared-library nodes, which won't necessarily have access to the dashboard UI

**Describe the solution you'd like**
Option 1) Make the login opt-in by creating a configuration parameter in the config file. Ideally, the login should be turned off by default
Option 2) Make the login feature configurable at compile time, creating a compiler flag to enable/disable this to avoid unnecessary go-btfs forks.

**Describe alternatives you've considered**
a) If it is not currently possible to turn the login off (maybe this is already possible but not documented) I'd need to refactor the code to disable the UI login so I can perform API calls towards my node. 
b) If there is a programmatic way yo setup the login process kindly point me to the documentation or describe in this issue solve my problem :) 

**Additional context**
I'm currently maintaining a [go-btfs fork focused on mobile](https://github.com/simbadMarino/btfs-sharedLib); however, while trying to bump the BTFS codebase to v3.1, I discovered the node is now requiring authentication, which completely breaks my node initialization routine as my app UI does not have a UI access to the dashboard.

**Comment by yu-btc** [comment]
After v3.1.0, BTFS UI login has enhanced security. The issue you raised can be resolved through configuration. We will submit your suggestions and issues to the development team and consider these improvements in subsequent versions.
