### ISSUE TITLE
Use case: go-btfs lite node

### ISSUE THREAD

**Issue by simbadMarino** [bittorrent/go-btfs#49]
I’m wondering if it’s possible to create a lite BTFS node which is limited to get data from peers to reduce the size of binary.

Motivation: This binary can be integrated by third party SW to retrieve large amount of data in a decentralized way without considerable impact on overall app size. 

Is this feasible ?

**Comment by Sophia-yu-kk** [comment]
Hi, the team currently has no plans to support this idea. Thank you for your support of the project.
