### ISSUE TITLE
Host Dashboard is not started

### ISSUE THREAD

**Issue by avm-xandry** [bittorrent/go-btfs#50]
Documentation said "Once your BTFS daemon has been launched and is running, simply paste the URL http://127.0.0.1:3000 into your browser to access the Host Dashboard", but HostUI has not started. I have tried with clean install and with upgraded. So the only way to configure host is the command line. Console output:

```
alex@server:~/go/bin> ./btfs daemon --chain-id 1029
Initializing daemon...
go-btfs version: 2.0.2-2970ddfd8
Repo version: 10
System version: amd64/linux
Golang version: go1.16.13
Repo location: /mnt/btfsdisk
Peer identity: 16Uiu2HAmGF9mmjdLmzhwF3TT8Nu7rGkv1Bw1fwoZJYzL6xvwANLb
the private key of wallet import format is:  XXX
the address of Bttc format is:  0x33fbaf80F25835ed216865128080C58568AaEdc3
the address of Tron format is:  TEi4yG8hcZynBX1y123jQb5V5pF6MReqiJ
self vault: 0x7226c87e83b9e798a6ca04d82447adcd9383f6cc 
approve WBTT to vault [0x7226c87e83b9e798a6ca04d82447adcd9383f6cc] at tx [0x73fe85df2cb9a096bb79572115a1c77edb66d8126c0e3fc68ff3950969875c11] 
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/172.17.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.6/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/fd01::19e0:daec:6c3e:3d96/tcp/4001
Swarm listening on /ip6/fd01::8172:877d:7f2e:c3b8/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/172.17.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.6/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/fd01::19e0:daec:6c3e:3d96/tcp/4001
Swarm announcing /ip6/fd01::8172:877d:7f2e:c3b8/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Dashboard: http://127.0.0.1:5001/dashboard
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Current host stats will be synced
Current host settings will be synced
```

**Comment by wuno** [comment]
I have had to screw around with this too. For me to access my dashboard, I have to go to this link - 

`http://localhost:5001`

Actually looks like this - 

`http://localhost:5001/btfs/bunchoflettershere/#/admin/dashboard`

Then to get the dashboard to connect to the network I had to update the URL in the settings view of the Dashboard to this - 

`http://127.0.0.1:5001`

I am still having all kinds of issues though. I was able to get all this working using Docker. I am trying to get it to build from source without Docker but just opened another issue due to fails.

**Comment by simbadMarino** [comment]
> I have had to screw around with this too. For me to access my dashboard, I have to go to this link -
> 
> `http://localhost:5001`
> 
> Actually looks like this -
> 
> `http://localhost:5001/btfs/bunchoflettershere/#/admin/dashboard`
> 
> Then to get the dashboard to connect to the network I had to update the URL in the settings view of the Dashboard to this -
> 
> `http://127.0.0.1:5001`
> 
> I am still having all kinds of issues though. I was able to get all this working using Docker. I am trying to get it to build from source without Docker but just opened another issue due to fails.


I had the same issue as Issue author and got it solved as you are suggesting 👍

**Comment by wuno** [comment]
@simbadMarino with your configurations is up time green for you? Mine still shows red even though it seems I am conntected. 

See image -
![Screenshot from 2022-01-30 19-10-43](https://user-images.githubusercontent.com/8263539/151726271-eeb2806d-b41d-41f7-91ea-e44cc3cea951.png)
 I want to believe it is all working but I don't understand why up time still shows 0%.

**Comment by neroxyr** [comment]
Followed the author steps and nothing. The page load but when I enter the dashboard it says "Looks like your node is not connected" The daemon is running btw

**Comment by wuno** [comment]
What URL do you have under the settings tab @neroxyr ?

**Comment by simbadMarino** [comment]
> @simbadMarino with your configurations is "up time" green for you? Mine still shows red even though it seems I am conntected.
> 
> See image - ![Screenshot from 2022-01-30 19-10-43](https://user-images.githubusercontent.com/8263539/151726271-eeb2806d-b41d-41f7-91ea-e44cc3cea951.png) I want to believe it is all working but I don't understand why up time still shows 0%.

Sorry for the delay, mine is red as well an now 600% lol, a glitch maybe but as long as your internet connection is stable it should go slowly up, my node needed around 5 to 6 days to get a 10 score with increases of 6% daily and the suddenly jumped to 600% lol
