### ISSUE TITLE
btfs command throws qtls.ClientHelloInfo doesn't match error

### ISSUE THREAD

**Issue by wuno** [bittorrent/go-btfs#51]
On Ubuntu 20.04 I complete setup for BTFS. After running `./btfs init`, I try to 

`btfs cat /btfs/.../readme` 

In fact anything I try to do with the command `btfs` throws the same error and I can not proceed with setting up my node. 

Error - 

```
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	pkg/mod/github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132
```

I have tried to build from source using go 1.15 / 1.16 / 1.17. All result in similar behavior.

**Comment by simbadMarino** [comment]
Try compiling using go 1.15.8, that worked for me when compiling 2.0.1 version, haven’t tried with v2.0.2 but will try this week 🙂

**Comment by wuno** [comment]
@simbadMarino I am getting the same error. I tried 1.15.8 and 1.15.15. Can you confirm that you were seeing the same error in my OP that was resolved by using the right version of Go to build?

**Comment by wuno** [comment]
**Golang version: go1.16.5** solves this issue. Also, I had to restart my terminal after running `btfs init` for any further `btfs` commands to work.
