### ISSUE TITLE
 Rating dropped

### ISSUE THREAD

**Issue by zhimipe** [bittorrent/go-btfs#53]
The latest version, but the rating has dropped.
![Screenshot (1)](https://user-images.githubusercontent.com/96413555/152237444-0252a098-4688-4bfe-8395-0d6f077a38c5.png)

In the daemon, it periodically writes this - ListReceiveChequeCmd map[] <nil>

**Comment by zhimipe** [comment]
> Version 2.0.2. HOST SCORE became 9. HOST SCORE HISTORY stopped displaying history. Yesterday the rating was 10. And in the history of the host, the rating for the last 60 days is also 10. ![Screenshot](https://user-images.githubusercontent.com/96413555/152165019-c7c5ebea-0f07-40e0-835f-f743a6b62b52.png) In the daemon, it periodically writes this - ListReceiveChequeCmd map[] ListReceiveChequeCmd map[] ![Безымянный](https://user-images.githubusercontent.com/96413555/152166275-d94766d4-7e6a-4e92-8025-24bec82ce43e.png)

**Comment by avm-xandry** [comment]
I can confirm the problem. However, it passes over time, you can check on my stats: https://scan-test.btfs.io/#/node/16Uiu2HAmGF9mmjdLmzhwF3TT8Nu7rGkv1Bw1fwoZJYzL6xvwANLb

**Comment by Sophia-yu-kk** [comment]
Through the browser to see the online time instability caused by the score drop

**Comment by avm-xandry** [comment]
My PC does not have online instability.
![Screenshot_20220208_132017](https://user-images.githubusercontent.com/15235430/152995286-7dbb1fe2-bb0c-4f5f-9fe5-56f8d5649b46.png)
![Screenshot_20220208_182341](https://user-images.githubusercontent.com/15235430/152995894-d67c0d5b-0943-4996-bd59-249ab37c2982.png)

This is btfs build from git. Uptime is 9 days.
I have Mysterium node on that PC which works fine.
