### ISSUE TITLE
No or zero uptime on Dashboard

### ISSUE THREAD

**Issue by satish4cs** [bittorrent/go-btfs#68]
Hi Team,

My node has been up for 4 days and the dashboard shows no up time.
What could be the problem?

Is it something that need to be fixed at client side or with a code fix?

I executed only 2 commands
```
/btfs init -p storage-host-testnet
/btfs daemon --chain-id 1029
```
![Screenshot from 2022-02-18 13-00-47](https://user-images.githubusercontent.com/13938447/154638029-070078d3-58a8-4fbf-8dc8-bb7a5562e1ee.png)

**Comment by Sophia-yu-kk** [comment]
please provide your node id, i will check it.

**Comment by satish4cs** [comment]
Here it is.
Peer identity: 16Uiu2HAmFQ8zdGNJtsdmaa5MdgMuvwmjadRvLtKuWcdHgf6dsvUN

**Comment by satish4cs** [comment]
[Sophia-yu-kk](https://github.com/Sophia-yu-kk), Could you help checking this?

16Uiu2HAmFQ8zdGNJtsdmaa5MdgMuvwmjadRvLtKuWcdHgf6dsvUN

> Here it is. Peer identity: 16Uiu2HAmFQ8zdGNJtsdmaa5MdgMuvwmjadRvLtKuWcdHgf6dsvUN



> Here it is. Peer identity: 16Uiu2HAmFQ8zdGNJtsdmaa5MdgMuvwmjadRvLtKuWcdHgf6dsvUN

Could help checking this?

**Comment by satish4cs** [comment]
> Here it is. Peer identity: 16Uiu2HAmFQ8zdGNJtsdmaa5MdgMuvwmjadRvLtKuWcdHgf6dsvUN

Could you help checking this?

**Comment by laocheng-cheng** [comment]
Hello,  I check that uptime is OKay，cloud you help to check it？

**Comment by Sophia-yu-kk** [comment]
The community has confirmed that the issue has been resolved. If you have any other questions, please feel free to submit an issue, the BTFS community appreciates your feedback!
