### ISSUE TITLE
[v2.1.0] Vault Init: Not a valid factory contract

### ISSUE THREAD

**Issue by pkyriacou** [bittorrent/go-btfs#73]
I have just upgraded from version 2.0.2 to 2.1.0 (simply changed over the executable file), and I execute the below command to start the btfs deamon:

> .\btfs-windows-amd64.exe daemon --chain-id 1029

I then get the following error:
> Error: init vault service: vault init: not a valid factory contract

I am on Windows 11 21H2, AMD64 architecture.

Kindly please advise how to fix. I have reverted back to 2.0.2 executables and it works as expected.

**Comment by Nanook994** [comment]
.\btfs-windows-amd64.exe daemon  = Mainnet

.\btfs-windows-amd64.exe daemon --chain-id 1029  = Testnet

**Comment by pkyriacou** [comment]
OK, I have just tried again with chain-id 199 and it seems to work. Transferred some BTT to BTTC network and node is now online on v 2.1.0 on BTTC Mainnet
