### ISSUE TITLE
how can use web3js sendTrans on bttc mainet?

### ISSUE THREAD

**Issue by boringw** [bittorrent/go-btfs#77]
`var privateKey = sss.arryString[i];
	  
	  var adress = web3.eth.accounts.privateKeyToAccount(privateKey).address;
      console.log(`privateKey: ${privateKey}  ${i} TNumber: ${sss.tNumber}`); 
	  
	  var abi = [{"inputs":[{"internalType":"address","name":"fund","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType":"address","name":"spender","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"constant":true,"inputs":[{"internalType":"address","name":"src","type":"address"},{"internalType":"address","name":"guy","type":"address"}],"name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"address","name":"guy","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"src","type":"address"},{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"}];

	  var TokenContract =new  web3.eth.Contract(abi,'0x0000000000000000000000000000000000001010');

	  var userBalance = await TokenContract.methods.balanceOf(adress).call();
	  
	  console.log(`SNND balance is: ${userBalance}`);
	  
	  var  userBalanceInt = web3.utils.toBN(userBalance);
	  if (userBalanceInt == 0) {
        continue;
      }
	  
	  nonce = await web3.eth.getTransactionCount(adress);
	  //const common1 = ethereumjs_common.forCustomChain('mainnet', { networkId: 199, chainId: 199, name: 'btt' }, 'muirGlacier');
	  
	  var rawTx = {
                from: adress,
                to: '0x3D6f3acA36F9e3A0834b67F28AEf2d4CE804cc1b',
                value: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
                nonce: web3.utils.toHex(nonce),
                gasLimit: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
                gasPrice: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
				data:TokenContract.methods.transfer('0x3D6f3acA36F9e3A0834b67F28AEf2d4CE804cc1b', web3.utils.toHex(web3.utils.toWei('1', 'ether'))).encodeABI()
            };
	var signprivateKey = Buffer.from(privateKey, 'hex');
	  //var rawTransaction = {"from":myAddress, "gasPrice":web3.utils.toHex(2 * 1e9),"gasLimit":web3.utils.toHex(210000),"to":contractAddress,"value":"0x0","data":contract.methods.transfer(toAddress, amount).encodeABI(),"nonce":web3.utils.toHex(count)} 
	var tx = new Tx(rawTx);
	await tx.sign(signprivateKey);
	var serializedTx = tx.serialize();
	//var signedTx = await web3.eth.accounts.sign(rawTx,privateKey);
	var txHash = await web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'));`

this code can get balance, but can not send Transaction, trow err:invalid sender
please help me very thanks

**Comment by simbadMarino** [comment]
> `var privateKey = sss.arryString[i];
> 
> ```
>   var adress = web3.eth.accounts.privateKeyToAccount(privateKey).address;
>   console.log(`privateKey: ${privateKey}  ${i} TNumber: ${sss.tNumber}`); 
>   
>   var abi = [{"inputs":[{"internalType":"address","name":"fund","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"owner","type":"address"},{"indexed":true,"internalType":"address","name":"spender","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"constant":true,"inputs":[{"internalType":"address","name":"src","type":"address"},{"internalType":"address","name":"guy","type":"address"}],"name":"allowance","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"approve","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"internalType":"address","name":"guy","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"subtractedValue","type":"uint256"}],"name":"decreaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"guy","type":"address"},{"internalType":"uint256","name":"addedValue","type":"uint256"}],"name":"increaseAllowance","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"name","outputs":[{"internalType":"string","name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"transfer","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"internalType":"address","name":"src","type":"address"},{"internalType":"address","name":"dst","type":"address"},{"internalType":"uint256","name":"sad","type":"uint256"}],"name":"transferFrom","outputs":[{"internalType":"bool","name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"}];
> 
>   var TokenContract =new  web3.eth.Contract(abi,'0x0000000000000000000000000000000000001010');
> 
>   var userBalance = await TokenContract.methods.balanceOf(adress).call();
>   
>   console.log(`SNND balance is: ${userBalance}`);
>   
>   var  userBalanceInt = web3.utils.toBN(userBalance);
>   if (userBalanceInt == 0) {
>     continue;
>   }
>   
>   nonce = await web3.eth.getTransactionCount(adress);
>   //const common1 = ethereumjs_common.forCustomChain('mainnet', { networkId: 199, chainId: 199, name: 'btt' }, 'muirGlacier');
>   
>   var rawTx = {
>             from: adress,
>             to: '0x3D6f3acA36F9e3A0834b67F28AEf2d4CE804cc1b',
>             value: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
>             nonce: web3.utils.toHex(nonce),
>             gasLimit: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
>             gasPrice: web3.utils.toHex(web3.utils.toWei('1', 'ether')),
> 			data:TokenContract.methods.transfer('0x3D6f3acA36F9e3A0834b67F28AEf2d4CE804cc1b', web3.utils.toHex(web3.utils.toWei('1', 'ether'))).encodeABI()
>         };
> var signprivateKey = Buffer.from(privateKey, 'hex');
>   //var rawTransaction = {"from":myAddress, "gasPrice":web3.utils.toHex(2 * 1e9),"gasLimit":web3.utils.toHex(210000),"to":contractAddress,"value":"0x0","data":contract.methods.transfer(toAddress, amount).encodeABI(),"nonce":web3.utils.toHex(count)} 
> var tx = new Tx(rawTx);
> await tx.sign(signprivateKey);
> var serializedTx = tx.serialize();
> //var signedTx = await web3.eth.accounts.sign(rawTx,privateKey);
> var txHash = await web3.eth.sendSignedTransaction('0x' + serializedTx.toString('hex'));`
> ```
> 
> this code can get balance, but can not send Transaction, trow err:invalid sender please help me very thanks

Are you trying to find a way to send BTT or WBTT to another address?
