### ISSUE TITLE
Same Host ID on multiple hosts after upgrade

### ISSUE THREAD

**Issue by pkyriacou** [bittorrent/go-btfs#78]
Hello,

I have just upgraded my 2 BTFS nodes from v1.6 to v2.1, transferred the required BTT on BTTC network to allow for the contract creation and the nodes are now running. After checking, I noticed that the Host ID for both nodes is the same! 

**The facts:**
1. The two nodes were initially created via the BitTorrent client using the same mnemonic phrase. 
2. I have noticed that the two nodes have different vault addresses.
3. Checking on BTFS Scan using the Host ID shows only the information of the last node to come online.
4. On the 2.1.0 dashboard, it says that the nodes have no contracts, whereas on the 1.6 dashboards, both nodes had contracts.
5. If I try to return to 1.6, both nodes have the same Host ID again.

I have disabled the smaller node for now, to avoid any conflicts. 

**Questions:**

1. Is there a way to salvage one of the 2 nodes without having to recreate it? I don't want to lose existing contracts and score.
2. Is it possible to use the same BTTC wallet for multiple nodes?

**Comment by Sophia-yu-kk** [comment]
The same private key will generate two identical node IDs. It is also normal to have two vault contract addresses.
1，You can keep the node that has the contract and is able to keep gaining
2，It is not recommended that multiple nodes use one wallet, which would effectively be one node as well.
