### ISSUE TITLE
In Windows 10 it doesn't work

### ISSUE THREAD

**Issue by alcaspa** [bittorrent/go-btfs#84]
I can't get it to work for Windows 10, is there a tutorial? Thank you!

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/install-run-btfs20-node
https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.1.0
This is the official v2.1.0 documentation for your reference. If you encounter specific error messages, you can continue to feedback to us.
