### ISSUE TITLE
Dont have transfer old config from 2.0.1 to 2.1.0

### ISSUE THREAD

**Issue by InTeamLife** [bittorrent/go-btfs#85]
Hello.  I updated my btfs from 2.0.1 to 2.1.0 strictly according to the instructions from the documentation, everything went well.  I sent 100btt to my wallet and btfs rolled me back to 2.0.1, I tried to update again and now btfs stops there.  And my config works well on 2.0.1 so far.
![IMG_20220221_212313_774](https://user-images.githubusercontent.com/30119373/155103069-43c2cf8a-9f92-4c93-9142-4c1d16befb5b.jpg)

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet

This is the latest BTFS upgrade document. If you have any error reporting information, please feel free to contact us. Thank you very much for your support!

**Comment by InTeamLife** [comment]
The bottom line is that I was completely updated according to this instruction https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet and the process does not go further

**Comment by InTeamLife** [comment]
> https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet
> 
> This is the latest BTFS upgrade document. If you have any error reporting information, please feel free to contact us. Thank you very much for your support!

The bottom line is that I was completely updated according to this instruction https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet and the process does not go further

**Comment by Ne2pp** [comment]
Why the issue closed? It hasn't been resolved yet.
We tried to transfer his config file, also returning to version 1.6.0, when we run version 2.1.0 - nothing happens, everything is as in the image above.
