### ISSUE TITLE
I am getting 'Resource Temporarily unavailable' message 

### ISSUE THREAD

**Issue by Rchua72** [bittorrent/go-btfs#86]
I am upgrading my BTFS version 1 to 2.1.  I am getting a 'resource temporarily unavailable' message when I try to run the command './btfs daemon --chain-id 199'

Please see screenshot below

![image](https://user-images.githubusercontent.com/6827300/155288864-a4252b54-71b7-4510-96d5-7b3f1d8c8959.png)

**Comment by Sophia-yu-kk** [comment]
Your question is a system problem, we found a similar explanation for your reference
https://stackoverflow.com/questions/7635440/error-on-accept-resource-temporarily-unavailable
