### ISSUE TITLE
switching from testnet to mainnet

### ISSUE THREAD

**Issue by Ne2pp** [bittorrent/go-btfs#87]
As I understand it, the test is over and we need to upgrade to version 2.1.0 (mainnet). I transferred the config from version 2.0.2 (testnet).
What do I need to do next to finally move to the mainnet? Host ID: 16Uiu2HAmGKNPU3qXw1LAMmUCTqpPjoUxvPsZgjoAjpa28KVBMY5b
![image](https://user-images.githubusercontent.com/69204619/155335706-9e45a5b3-887a-4455-b5ee-cbd2d5c267ea.png)

If the test is not completed, please indicate where I can follow the news and next steps.
Thanks

**Comment by Sophia-yu-kk** [comment]
We do not recommend upgrading from the test network to the main network, as data cannot be migrated. It is possible to get NFT badge rewards by participating in the test network, we suggest you save your private key and redeem it after the subsequent opening of the redemption portal.

If you encounter difficulties in the upgrade process, you can refer to the upgrade tutorial we have prepared for you ，https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet
