### ISSUE TITLE
Memory usage is increasing

### ISSUE THREAD

**Issue by asd976385560** [bittorrent/go-btfs#93]
![image](https://user-images.githubusercontent.com/41860268/155936623-5ba1ba53-2e82-405a-8a3b-f98c727df868.png)
![image](https://user-images.githubusercontent.com/41860268/155936733-4687f7f8-a1a4-449a-b7d4-5f4f665766e1.png)
![image](https://user-images.githubusercontent.com/41860268/155936778-6c80b808-014c-44fb-8e09-80b27170ef73.png)
![image](https://user-images.githubusercontent.com/41860268/155936925-33cf3822-d6fe-4b09-8c75-fa88705423d7.png)

15GB Memory?

**Comment by Sophia-yu-kk** [comment]
Yes, this is a known issue. It will be optimized later. Thank you very much for your feedback.
