### ISSUE TITLE
Upgrade is not possible?

### ISSUE THREAD

**Issue by AlterX76** [bittorrent/go-btfs#94]
On Windows, just downloaded the new binary from 2.0.2 to 2.1.0:

Initializing daemon...
go-btfs version: 2.1.0-56bba50
Repo version: 10
System version: amd64/windows
Golang version: go1.15.15
Repo location: C:\Users\storage\.btfs
Peer identity: ...
the address of Bttc format is:  ...
the address of Tron format is:  ...
init settlement err:  init vault service: vault init: not a valid factory contract

**Comment by AlterX76** [comment]
Looks like I get the same error even on a fresh linux arm device, after the init!

**Comment by Sophia-yu-kk** [comment]
https://docs.btfs.io/docs/tutorials-on-upgrading-btfs-v10-to-btfs-v20-mainnet#solutions-to-common-errors--init-settlement-err-init-vault-service-vault-init-not-a-valid-factory-contract

please refer this FAQ，is a known issue，the doc will help you to solve this problem.

**Comment by VitaliyAT** [comment]
Great decision - install 1.6 first )))) Why not from alfa version, some 0.0.0.1? No normal installation and work - no support from users. Do 2.2 with normal work, without this raining dance.
